package com.primehr.performancemanagement.domain;
import com.primehr.rsp.domain.RspAuditedEntity;import com.primehr.shared.exception.IllegalLifecycleTransitionException;import jakarta.persistence.*;import java.time.*;import java.util.*;
@Entity @Table(name="spms_cycle",uniqueConstraints=@UniqueConstraint(name="uk_spms_cycle_code",columnNames={"agency_id","normalized_code"}))
public class PerformanceCycle extends RspAuditedEntity {public enum Status{DRAFT,OPEN,CLOSED,CANCELLED}
 @Column(nullable=false,length=80)private String code;@Column(name="normalized_code",nullable=false,length=80)private String normalizedCode;@Column(nullable=false,length=200)private String name;
 @Column(name="period_start",nullable=false)private LocalDate periodStart;@Column(name="period_end",nullable=false)private LocalDate periodEnd;@Column(name="policy_version_id",nullable=false,length=36)private String policyVersionId;@Column(nullable=false,length=60)private String timezone;@Column(name="coverage_scope",nullable=false,length=30)private String coverageScope;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private Status status;@Column(name="calendar_revision",nullable=false)private int calendarRevision;@Column(name="opened_by",length=100)private String openedBy;@Column(name="opened_at")private Instant openedAt;@Column(name="closed_by",length=100)private String closedBy;@Column(name="closed_at")private Instant closedAt;@Column(name="cancelled_by",length=100)private String cancelledBy;@Column(name="cancelled_at")private Instant cancelledAt;@Column(name="transition_reason",length=1000)private String transitionReason;
 protected PerformanceCycle(){}public PerformanceCycle(String agency,String code,String name,LocalDate from,LocalDate to,String policy,String timezone){super(agency);status=Status.DRAFT;apply(code,name,from,to,policy,timezone);coverageScope="AGENCY_WIDE";}
 public void update(String code,String name,LocalDate from,LocalDate to,String policy,String timezone){draft();apply(code,name,from,to,policy,timezone);}
 public void open(String actor,String reason,Instant at){draft();openedBy=requiredText(actor,"actor");transitionReason=requiredText(reason,"reason");openedAt=Objects.requireNonNull(at);status=Status.OPEN;}
 public void close(String actor,String reason,Instant at){if(status!=Status.OPEN)throw new IllegalLifecycleTransitionException("Only an open cycle may be closed");closedBy=requiredText(actor,"actor");transitionReason=requiredText(reason,"reason");closedAt=Objects.requireNonNull(at);status=Status.CLOSED;}
 public void cancel(String actor,String reason,Instant at){if(status!=Status.DRAFT&&status!=Status.OPEN)throw new IllegalLifecycleTransitionException("Only a draft or open cycle may be cancelled");cancelledBy=requiredText(actor,"actor");transitionReason=requiredText(reason,"reason");cancelledAt=Objects.requireNonNull(at);status=Status.CANCELLED;}
 public void calendarChanged(){draft();calendarRevision++;}
 private void apply(String c,String n,LocalDate from,LocalDate to,String policy,String zone){code=requiredText(c,"code");normalizedCode=code.toUpperCase(Locale.ROOT);name=requiredText(n,"name");periodStart=Objects.requireNonNull(from,"periodStart");periodEnd=Objects.requireNonNull(to,"periodEnd");if(to.isBefore(from))throw new IllegalArgumentException("periodEnd cannot precede periodStart");policyVersionId=requiredText(policy,"policyVersionId");timezone=requiredText(zone,"timezone");ZoneId.of(timezone);}
 private void draft(){if(status!=Status.DRAFT)throw new IllegalLifecycleTransitionException("Only a draft cycle may be edited or opened");}
 public String getCode(){return code;}public String getNormalizedCode(){return normalizedCode;}public String getName(){return name;}public LocalDate getPeriodStart(){return periodStart;}public LocalDate getPeriodEnd(){return periodEnd;}public String getPolicyVersionId(){return policyVersionId;}public String getTimezone(){return timezone;}public String getCoverageScope(){return coverageScope;}public Status getStatus(){return status;}public int getCalendarRevision(){return calendarRevision;}public String getTransitionReason(){return transitionReason;}
}
