package com.primehr.performancemanagement.domain;
import com.primehr.rsp.domain.RspAuditedEntity;import jakarta.persistence.*;import java.time.*;
@Entity@Table(name="spms_coaching_action_item")public class PerformanceCoachingActionItem extends RspAuditedEntity{
 public enum Status{OPEN,IN_PROGRESS,COMPLETED,CANCELLED}
 @Column(name="monitoring_case_id",nullable=false,length=36)private String monitoringCaseId;@Column(name="coaching_session_id",nullable=false,length=36)private String coachingSessionId;@Column(nullable=false,length=3000)private String description;@Column(name="accountable_employee_no",nullable=false,length=100)private String accountableEmployeeNo;@Column(name="due_date",nullable=false)private LocalDate dueDate;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private Status status;@Column(name="progress_note",length=3000)private String progressNote;@Column(name="completed_at")private Instant completedAt;@Column(name="verified_by",length=100)private String verifiedBy;@Column(name="verified_at")private Instant verifiedAt;@Column(name="reopen_reason",length=2000)private String reopenReason;
 protected PerformanceCoachingActionItem(){}public PerformanceCoachingActionItem(String a,String c,String s,String d,String accountable,LocalDate due){super(a);monitoringCaseId=requiredText(c,"monitoringCaseId");coachingSessionId=requiredText(s,"coachingSessionId");description=requiredText(d,"description");accountableEmployeeNo=requiredText(accountable,"accountableEmployeeNo");dueDate=java.util.Objects.requireNonNull(due,"dueDate");status=Status.OPEN;}
 public void progress(String note,boolean complete,Instant at){if(status==Status.CANCELLED)throw new IllegalStateException("Cancelled action item cannot be updated");progressNote=requiredText(note,"progressNote");status=complete?Status.COMPLETED:Status.IN_PROGRESS;completedAt=complete?at:null;verifiedBy=null;verifiedAt=null;reopenReason=null;}
 public void verify(String actor,Instant at){if(status!=Status.COMPLETED)throw new IllegalStateException("Only a completed action item may be verified");verifiedBy=requiredText(actor,"actor");verifiedAt=at;}
 public void reopen(String reason){if(status!=Status.COMPLETED)throw new IllegalStateException("Only a completed action item may be reopened");String validated=requiredText(reason,"reason");status=Status.IN_PROGRESS;verifiedBy=null;verifiedAt=null;completedAt=null;reopenReason=validated;}
 public String getMonitoringCaseId(){return monitoringCaseId;}public String getCoachingSessionId(){return coachingSessionId;}public String getDescription(){return description;}public String getAccountableEmployeeNo(){return accountableEmployeeNo;}public LocalDate getDueDate(){return dueDate;}public Status getStatus(){return status;}public String getProgressNote(){return progressNote;}public Instant getCompletedAt(){return completedAt;}public String getVerifiedBy(){return verifiedBy;}public Instant getVerifiedAt(){return verifiedAt;}public String getReopenReason(){return reopenReason;}
}
