package com.primehr.performancemanagement.domain;
import com.primehr.rsp.domain.RspAuditedEntity;import jakarta.persistence.*;import java.time.*;
@Entity@Table(name="spms_mid_cycle_review",uniqueConstraints=@UniqueConstraint(name="uk_spms_mid_cycle_case",columnNames={"agency_id","monitoring_case_id"}))public class PerformanceMidCycleReview extends RspAuditedEntity{
 public enum Status{DRAFT,SUBMITTED,ACKNOWLEDGED,CLOSED_WITHOUT_ACKNOWLEDGMENT,SUPERSEDED,VOIDED}
 @Column(name="monitoring_case_id",nullable=false,length=36)private String monitoringCaseId;@Column(name="snapshot_update_count",nullable=false)private int snapshotUpdateCount;@Column(name="snapshot_open_action_count",nullable=false)private int snapshotOpenActionCount;@Column(name="snapshot_missing_evidence_count",nullable=false)private int snapshotMissingEvidenceCount;@Column(name="supervisor_narrative",nullable=false,length=4000)private String supervisorNarrative;@Column(name="employee_narrative",length=4000)private String employeeNarrative;@Column(name="amendment_recommended",nullable=false)private boolean amendmentRecommended;@Column(name="amendment_reason",length=2000)private String amendmentReason;@Enumerated(EnumType.STRING)@Column(nullable=false,length=40)private Status status;@Column(name="submitted_by",length=100)private String submittedBy;@Column(name="submitted_at")private Instant submittedAt;@Column(name="acknowledged_by",length=100)private String acknowledgedBy;@Column(name="acknowledged_at")private Instant acknowledgedAt;@Column(name="closure_reason",length=2000)private String closureReason;
 protected PerformanceMidCycleReview(){}public PerformanceMidCycleReview(String a,String c,int updates,int open,int missing,String supervisor,String employee,boolean amendment,String reason){super(a);monitoringCaseId=requiredText(c,"monitoringCaseId");snapshotUpdateCount=updates;snapshotOpenActionCount=open;snapshotMissingEvidenceCount=missing;status=Status.DRAFT;edit(supervisor,employee,amendment,reason);}
 public void edit(String supervisor,String employee,boolean amendment,String reason){if(status!=Status.DRAFT)throw new IllegalStateException("Only a draft mid-cycle review may be edited");supervisorNarrative=requiredText(supervisor,"supervisorNarrative");employeeNarrative=optionalText(employee);amendmentRecommended=amendment;amendmentReason=amendment?requiredText(reason,"amendmentReason"):null;}
 public void submit(String actor,Instant at){if(status!=Status.DRAFT)throw new IllegalStateException("Only a draft mid-cycle review may be submitted");status=Status.SUBMITTED;submittedBy=requiredText(actor,"actor");submittedAt=at;}
 public void acknowledge(String actor,String narrative,Instant at){if(status!=Status.SUBMITTED)throw new IllegalStateException("Only a submitted mid-cycle review may be acknowledged");employeeNarrative=optionalText(narrative);status=Status.ACKNOWLEDGED;acknowledgedBy=requiredText(actor,"actor");acknowledgedAt=at;}
 public void closeWithoutAcknowledgment(String reason){if(status!=Status.SUBMITTED)throw new IllegalStateException("Only a submitted mid-cycle review may be closed without acknowledgment");String validated=requiredText(reason,"reason");status=Status.CLOSED_WITHOUT_ACKNOWLEDGMENT;closureReason=validated;}
 public String getMonitoringCaseId(){return monitoringCaseId;}public int getSnapshotUpdateCount(){return snapshotUpdateCount;}public int getSnapshotOpenActionCount(){return snapshotOpenActionCount;}public int getSnapshotMissingEvidenceCount(){return snapshotMissingEvidenceCount;}public String getSupervisorNarrative(){return supervisorNarrative;}public String getEmployeeNarrative(){return employeeNarrative;}public boolean isAmendmentRecommended(){return amendmentRecommended;}public String getAmendmentReason(){return amendmentReason;}public Status getStatus(){return status;}public String getSubmittedBy(){return submittedBy;}public Instant getSubmittedAt(){return submittedAt;}public String getAcknowledgedBy(){return acknowledgedBy;}public Instant getAcknowledgedAt(){return acknowledgedAt;}public String getClosureReason(){return closureReason;}
}
