package com.primehr.performancemanagement.domain;import com.primehr.rsp.domain.RspAuditedEntity;import com.primehr.shared.exception.IllegalLifecycleTransitionException;import jakarta.persistence.*;import java.time.*;import java.util.*;
@Entity @Table(name="spms_pmt",uniqueConstraints=@UniqueConstraint(name="uk_spms_pmt_code",columnNames={"agency_id","normalized_code"}))
public class PerformanceManagementTeam extends RspAuditedEntity{public enum Status{DRAFT,ACTIVE,INACTIVE}
 @Column(nullable=false,length=80)private String code;@Column(name="normalized_code",nullable=false,length=80)private String normalizedCode;@Column(nullable=false,length=200)private String name;@Column(name="mandate_reference",nullable=false,length=1000)private String mandateReference;@Column(name="effective_from",nullable=false)private LocalDate effectiveFrom;@Column(name="effective_to")private LocalDate effectiveTo;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private Status status;@Column(name="roster_revision",nullable=false)private int rosterRevision;@Column(name="activated_by",length=100)private String activatedBy;@Column(name="activated_at")private Instant activatedAt;@Column(name="deactivated_by",length=100)private String deactivatedBy;@Column(name="deactivated_at")private Instant deactivatedAt;@Column(name="transition_reason",length=1000)private String transitionReason;
 protected PerformanceManagementTeam(){}public PerformanceManagementTeam(String agency,String code,String name,String mandate,LocalDate from,LocalDate to){super(agency);status=Status.DRAFT;apply(code,name,mandate,from,to);}
 public void requireDraft(){draft();}public void update(String code,String name,String mandate,LocalDate from,LocalDate to){draft();apply(code,name,mandate,from,to);}public void rosterChanged(){draft();rosterRevision++;}
 public void activate(String actor,String reason,Instant at){draft();activatedBy=requiredText(actor,"actor");transitionReason=requiredText(reason,"reason");activatedAt=Objects.requireNonNull(at);status=Status.ACTIVE;}
 public void deactivate(String actor,String reason,Instant at){if(status!=Status.ACTIVE)throw new IllegalLifecycleTransitionException("Only an active PMT may be deactivated");deactivatedBy=requiredText(actor,"actor");transitionReason=requiredText(reason,"reason");deactivatedAt=Objects.requireNonNull(at);LocalDate day=at.atZone(ZoneId.of("Asia/Manila")).toLocalDate();LocalDate end=day.isBefore(effectiveFrom)?effectiveFrom:day;if(effectiveTo==null||effectiveTo.isAfter(end))effectiveTo=end;status=Status.INACTIVE;}
 public boolean effectiveOn(LocalDate day){return status==Status.ACTIVE&&!day.isBefore(effectiveFrom)&&(effectiveTo==null||!day.isAfter(effectiveTo));}
 private void apply(String c,String n,String mandate,LocalDate from,LocalDate to){code=requiredText(c,"code");normalizedCode=code.toUpperCase(Locale.ROOT);name=requiredText(n,"name");mandateReference=requiredText(mandate,"mandateReference");effectiveFrom=Objects.requireNonNull(from,"effectiveFrom");effectiveTo=to;if(to!=null&&to.isBefore(from))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");}private void draft(){if(status!=Status.DRAFT)throw new IllegalLifecycleTransitionException("Only a draft PMT may be edited");}
 public String getCode(){return code;}public String getNormalizedCode(){return normalizedCode;}public String getName(){return name;}public String getMandateReference(){return mandateReference;}public LocalDate getEffectiveFrom(){return effectiveFrom;}public LocalDate getEffectiveTo(){return effectiveTo;}public Status getStatus(){return status;}public int getRosterRevision(){return rosterRevision;}public String getTransitionReason(){return transitionReason;}
}
