package com.primehr.performancemanagement.domain;
import com.primehr.rsp.domain.RspAuditedEntity;import jakarta.persistence.*;import java.time.*;
@Entity@Table(name="spms_commitment_version",uniqueConstraints=@UniqueConstraint(name="uk_spms_commitment_version",columnNames={"agency_id","commitment_id","definition_version"}))
public class PerformanceCommitmentVersion extends RspAuditedEntity{
 public enum Status{DRAFT,AMENDMENT_DRAFT,SUBMITTED,IN_REVIEW,RETURNED,REJECTED,APPROVED,WITHDRAWN,VOIDED,SUPERSEDED}
 @Column(name="commitment_id",nullable=false,length=36)private String commitmentId;@Column(name="assignment_id",nullable=false,length=36)private String assignmentId;@Column(name="definition_version",nullable=false)private int definitionVersion;@Column(name="supersedes_id",length=36)private String supersedesId;
 @Column(name="cycle_id",nullable=false,length=36)private String cycleId;@Column(name="policy_version_id",nullable=false,length=36)private String policyVersionId;@Column(name="template_version_id",nullable=false,length=36)private String templateVersionId;@Column(name="rating_scale_version_id",nullable=false,length=36)private String ratingScaleVersionId;@Column(name="objective_version_ids",length=4000)private String objectiveVersionIds;
 @Column(name="form_type",nullable=false,length=20)private String formType;@Column(name="form_label",nullable=false,length=200)private String formLabel;@Column(name="period_start",nullable=false)private LocalDate periodStart;@Column(name="period_end",nullable=false)private LocalDate periodEnd;@Column(name="calendar_revision",nullable=false)private int calendarRevision;
 @Column(name="subject_type",nullable=false,length=30)private String subjectType;@Column(name="subject_id",nullable=false)private Long subjectId;@Column(name="subject_code",length=80)private String subjectCode;@Column(name="subject_name",nullable=false,length=200)private String subjectName;@Column(name="area_id")private Long areaId;@Column(name="area_name",length=200)private String areaName;@Column(name="business_unit_id",nullable=false)private Long businessUnitId;@Column(name="business_unit_name",nullable=false,length=200)private String businessUnitName;
 @Column(name="owner_employee_id",nullable=false)private Long ownerEmployeeId;@Column(name="owner_employee_no",nullable=false,length=100)private String ownerEmployeeNo;@Column(name="owner_name",nullable=false,length=300)private String ownerName;@Column(name="owner_appointment_id",nullable=false)private Long ownerAppointmentId;@Column(name="owner_job_position_id",nullable=false)private Long ownerJobPositionId;@Column(name="owner_plantilla_id",nullable=false)private Long ownerPlantillaId;
 @Column(name="organization_fingerprint",nullable=false,length=64)private String organizationFingerprint;@Column(name="participant_fingerprint",nullable=false,length=64)private String participantFingerprint;@Column(name="assignment_fingerprint",nullable=false,length=64)private String assignmentFingerprint;@Column(name="content_fingerprint",nullable=false,length=64)private String contentFingerprint;@Column(name="source_fetched_at",nullable=false)private Instant sourceFetchedAt;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=24)private Status status;@Column(name="content_revision",nullable=false)private int contentRevision;@Column(name="lifecycle_revision",nullable=false)private int lifecycleRevision;
 protected PerformanceCommitmentVersion(){}public PerformanceCommitmentVersion(String a,String root,String assignment,int number,String prior,PerformanceCycle cycle,PerformanceTemplateVersion template,PerformancePlanAssignment p,String objectives,String assignmentFp,String contentFp,Instant fetched){super(a);commitmentId=requiredText(root,"commitmentId");assignmentId=requiredText(assignment,"assignmentId");if(number<1)throw new IllegalArgumentException("definitionVersion must be positive");definitionVersion=number;supersedesId=optionalText(prior);cycleId=cycle.getId();policyVersionId=cycle.getPolicyVersionId();templateVersionId=template.getId();ratingScaleVersionId=template.getRatingScaleVersionId();objectiveVersionIds=optionalText(objectives);formType=p.getFormType();formLabel=template.getFormLabel();periodStart=cycle.getPeriodStart();periodEnd=cycle.getPeriodEnd();calendarRevision=cycle.getCalendarRevision();subjectType=p.getSubjectType().name();subjectId=p.getSubjectId();subjectCode=p.getSubjectCode();subjectName=p.getSubjectName();areaId=p.getAreaId();areaName=p.getAreaName();businessUnitId=p.getRoutingBusinessUnitId();businessUnitName=p.getRoutingBusinessUnitName();ownerEmployeeId=p.getOwnerEmployeeId();ownerEmployeeNo=p.getOwnerEmployeeNo();ownerName=p.getOwnerName();ownerAppointmentId=p.getOwnerAppointmentId();ownerJobPositionId=p.getOwnerJobPositionId();ownerPlantillaId=p.getOwnerPlantillaId();organizationFingerprint=p.getOrganizationFingerprint();participantFingerprint=p.getParticipantFingerprint();assignmentFingerprint=requiredText(assignmentFp,"assignmentFingerprint");contentFingerprint=requiredText(contentFp,"contentFingerprint");sourceFetchedAt=fetched;status=Status.DRAFT;}
 public PerformanceCommitmentVersion(String agency,PerformanceCommitmentVersion source,int number,String contentFingerprint,Instant fetched){super(agency);commitmentId=source.commitmentId;assignmentId=source.assignmentId;definitionVersion=number;supersedesId=source.getId();cycleId=source.cycleId;policyVersionId=source.policyVersionId;templateVersionId=source.templateVersionId;ratingScaleVersionId=source.ratingScaleVersionId;objectiveVersionIds=source.objectiveVersionIds;formType=source.formType;formLabel=source.formLabel;periodStart=source.periodStart;periodEnd=source.periodEnd;calendarRevision=source.calendarRevision;subjectType=source.subjectType;subjectId=source.subjectId;subjectCode=source.subjectCode;subjectName=source.subjectName;areaId=source.areaId;areaName=source.areaName;businessUnitId=source.businessUnitId;businessUnitName=source.businessUnitName;ownerEmployeeId=source.ownerEmployeeId;ownerEmployeeNo=source.ownerEmployeeNo;ownerName=source.ownerName;ownerAppointmentId=source.ownerAppointmentId;ownerJobPositionId=source.ownerJobPositionId;ownerPlantillaId=source.ownerPlantillaId;organizationFingerprint=source.organizationFingerprint;participantFingerprint=source.participantFingerprint;assignmentFingerprint=source.assignmentFingerprint;this.contentFingerprint=requiredText(contentFingerprint,"contentFingerprint");sourceFetchedAt=fetched;status=Status.AMENDMENT_DRAFT;contentRevision=source.contentRevision;}
 public void contentChanged(String fp){editable();contentFingerprint=requiredText(fp,"contentFingerprint");contentRevision++;}private void editable(){if(status!=Status.DRAFT&&status!=Status.AMENDMENT_DRAFT&&status!=Status.RETURNED)throw new IllegalStateException("Only an editable commitment may change");}
 public void submit(boolean resubmission){if(status!=Status.DRAFT&&status!=Status.AMENDMENT_DRAFT&&status!=Status.RETURNED)throw new IllegalStateException("Only a draft, amendment draft, or returned commitment may be submitted");status=Status.SUBMITTED;lifecycleRevision++;if(resubmission)contentRevision++;}
 public void recommended(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment may be recommended");status=Status.IN_REVIEW;lifecycleRevision++;}
 public void returned(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment may be returned");status=Status.RETURNED;lifecycleRevision++;}
 public void approved(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment may be approved");status=Status.APPROVED;lifecycleRevision++;}
 public void rejected(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment may be rejected");status=Status.REJECTED;lifecycleRevision++;}
 public void withdrawn(){if(status!=Status.SUBMITTED)throw new IllegalStateException("Only a newly submitted commitment may be withdrawn");status=Status.WITHDRAWN;lifecycleRevision++;}
 public void voided(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment may be voided");status=Status.VOIDED;lifecycleRevision++;}
 public void routeRebased(){if(status!=Status.SUBMITTED&&status!=Status.IN_REVIEW)throw new IllegalStateException("Only an in-flight commitment route may be rebased");status=Status.SUBMITTED;lifecycleRevision++;}
 public void superseded(){if(status!=Status.APPROVED)throw new IllegalStateException("Only an approved commitment may be superseded");status=Status.SUPERSEDED;lifecycleRevision++;}
 public String getCommitmentId(){return commitmentId;}public String getAssignmentId(){return assignmentId;}public int getDefinitionVersion(){return definitionVersion;}public String getSupersedesId(){return supersedesId;}public String getCycleId(){return cycleId;}public String getPolicyVersionId(){return policyVersionId;}public String getTemplateVersionId(){return templateVersionId;}public String getRatingScaleVersionId(){return ratingScaleVersionId;}public String getObjectiveVersionIds(){return objectiveVersionIds;}public String getFormType(){return formType;}public String getFormLabel(){return formLabel;}public LocalDate getPeriodStart(){return periodStart;}public LocalDate getPeriodEnd(){return periodEnd;}public int getCalendarRevision(){return calendarRevision;}public String getSubjectType(){return subjectType;}public Long getSubjectId(){return subjectId;}public String getSubjectCode(){return subjectCode;}public String getSubjectName(){return subjectName;}public Long getAreaId(){return areaId;}public String getAreaName(){return areaName;}public Long getBusinessUnitId(){return businessUnitId;}public String getBusinessUnitName(){return businessUnitName;}public Long getOwnerEmployeeId(){return ownerEmployeeId;}public String getOwnerEmployeeNo(){return ownerEmployeeNo;}public String getOwnerName(){return ownerName;}public Long getOwnerAppointmentId(){return ownerAppointmentId;}public Long getOwnerJobPositionId(){return ownerJobPositionId;}public Long getOwnerPlantillaId(){return ownerPlantillaId;}public String getOrganizationFingerprint(){return organizationFingerprint;}public String getParticipantFingerprint(){return participantFingerprint;}public String getAssignmentFingerprint(){return assignmentFingerprint;}public String getContentFingerprint(){return contentFingerprint;}public Instant getSourceFetchedAt(){return sourceFetchedAt;}public Status getStatus(){return status;}public int getContentRevision(){return contentRevision;}public int getLifecycleRevision(){return lifecycleRevision;}
}
