package com.primehr.performancemanagement.domain;
import com.primehr.rsp.domain.RspAuditedEntity;import jakarta.persistence.*;import java.time.*;
@Entity@Table(name="spms_rating_appeal",uniqueConstraints=@UniqueConstraint(name="uk_spms_appeal_final",columnNames={"agency_id","final_rating_id"}))
public class PerformanceRatingAppeal extends RspAuditedEntity{
 public enum Status{DRAFT,SUBMITTED,UPHELD,MODIFIED,REMANDED,DISMISSED}
 @Column(name="final_rating_id",nullable=false,length=36)private String finalRatingId;@Column(name="rating_case_id",nullable=false,length=36)private String ratingCaseId;@Column(name="appellant_employee_no",nullable=false,length=100)private String appellantEmployeeNo;@Column(nullable=false,length=4000)private String grounds;@Column(name="requested_remedy",nullable=false,length=2000)private String requestedRemedy;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private Status status;@Column(name="submitted_at")private Instant submittedAt;@Column(name="decided_by",length=100)private String decidedBy;@Column(name="decided_at")private Instant decidedAt;@Column(name="decision_reason",length=4000)private String decisionReason;@Column(name="successor_final_rating_id",length=36)private String successorFinalRatingId;
 protected PerformanceRatingAppeal(){}public PerformanceRatingAppeal(String a,String f,String c,String employee,String grounds,String remedy){super(a);finalRatingId=requiredText(f,"finalRatingId");ratingCaseId=requiredText(c,"ratingCaseId");appellantEmployeeNo=requiredText(employee,"appellantEmployeeNo");status=Status.DRAFT;update(grounds,remedy);}
 public void update(String g,String r){if(status!=Status.DRAFT)throw new IllegalStateException("Only a draft appeal may be edited");grounds=requiredText(g,"grounds");requestedRemedy=requiredText(r,"requestedRemedy");}public void submit(Instant at){if(status!=Status.DRAFT)throw new IllegalStateException("Only a draft appeal may be submitted");status=Status.SUBMITTED;submittedAt=at;}public void decide(Status outcome,String reason,String successor,String actor,Instant at){if(status!=Status.SUBMITTED)throw new IllegalStateException("Only a submitted appeal may be decided");if(outcome!=Status.UPHELD&&outcome!=Status.MODIFIED&&outcome!=Status.REMANDED&&outcome!=Status.DISMISSED)throw new IllegalArgumentException("Invalid appeal outcome");if(outcome==Status.MODIFIED&&(successor==null||successor.isBlank()))throw new IllegalArgumentException("Modified appeal requires a successor rating");status=outcome;decisionReason=requiredText(reason,"decisionReason");successorFinalRatingId=optionalText(successor);decidedBy=requiredText(actor,"actor");decidedAt=at;}
 public String getFinalRatingId(){return finalRatingId;}public String getRatingCaseId(){return ratingCaseId;}public String getAppellantEmployeeNo(){return appellantEmployeeNo;}public String getGrounds(){return grounds;}public String getRequestedRemedy(){return requestedRemedy;}public Status getStatus(){return status;}public Instant getSubmittedAt(){return submittedAt;}public String getDecidedBy(){return decidedBy;}public Instant getDecidedAt(){return decidedAt;}public String getDecisionReason(){return decisionReason;}public String getSuccessorFinalRatingId(){return successorFinalRatingId;}
}
