package com.primehr.performancemanagement.domain;

import com.primehr.rsp.domain.RspAuditedEntity;
import com.primehr.shared.exception.IllegalLifecycleTransitionException;
import jakarta.persistence.*;
import java.time.*;import java.util.*;

@Entity @Table(name="spms_policy_version",uniqueConstraints=@UniqueConstraint(name="uk_spms_policy_version",columnNames={"agency_id","policy_id","definition_version"}))
public class PerformancePolicyVersion extends RspAuditedEntity {
 public enum Frequency{ANNUAL,SEMI_ANNUAL,QUARTERLY,CUSTOM} public enum Status{DRAFT,PUBLISHED,RETIRED}
 @Column(name="policy_id",nullable=false,length=36)private String policyId;@Column(name="definition_version",nullable=false)private int definitionVersion;
 @Column(name="supersedes_id",length=36)private String supersedesId;@Column(nullable=false,length=200)private String title;@Column(length=2000)private String description;
 @Column(name="legal_basis",nullable=false,length=1000)private String legalBasis;@Column(name="display_label",nullable=false,length=120)private String displayLabel;
 @Enumerated(EnumType.STRING)@Column(name="cycle_frequency",nullable=false,length=20)private Frequency cycleFrequency;
 @Column(name="requires_mid_cycle_review",nullable=false)private boolean requiresMidCycleReview;@Column(name="requires_self_assessment",nullable=false)private boolean requiresSelfAssessment;
 @Column(name="requires_pmt_calibration",nullable=false)private boolean requiresPmtCalibration;@Column(name="requires_acknowledgment",nullable=false)private boolean requiresAcknowledgment;
 @Column(name="requires_appeal",nullable=false)private boolean requiresAppeal;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private Status status;
 @Column(name="effective_from")private LocalDate effectiveFrom;@Column(name="effective_to")private LocalDate effectiveTo;@Column(name="published_by",length=100)private String publishedBy;
 @Column(name="published_at")private Instant publishedAt;@Column(name="retired_by",length=100)private String retiredBy;@Column(name="retired_at")private Instant retiredAt;@Column(name="retirement_reason",length=1000)private String retirementReason;
 protected PerformancePolicyVersion(){}
 public PerformancePolicyVersion(String agency,String policy,int number,String prior,String title,String description,String legalBasis,String label,Frequency frequency,boolean mid,boolean self,boolean calibration,boolean acknowledgment,boolean appeal){super(agency);if(number<1)throw new IllegalArgumentException("definitionVersion must be positive");policyId=requiredText(policy,"policyId");definitionVersion=number;supersedesId=optionalText(prior);status=Status.DRAFT;apply(title,description,legalBasis,label,frequency,mid,self,calibration,acknowledgment,appeal);}
 public void update(String title,String description,String legalBasis,String label,Frequency frequency,boolean mid,boolean self,boolean calibration,boolean acknowledgment,boolean appeal){draft();apply(title,description,legalBasis,label,frequency,mid,self,calibration,acknowledgment,appeal);}
 public void publish(LocalDate from,LocalDate to,String actor,Instant at){draft();if(from==null)throw new IllegalArgumentException("effectiveFrom is required");if(to!=null&&to.isBefore(from))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");effectiveFrom=from;effectiveTo=to;publishedBy=requiredText(actor,"actor");publishedAt=Objects.requireNonNull(at);status=Status.PUBLISHED;}
 public void retire(String actor,String reason,Instant at){if(status!=Status.PUBLISHED)throw new IllegalLifecycleTransitionException("Only a published policy may be retired");retiredBy=requiredText(actor,"actor");retirementReason=requiredText(reason,"reason");retiredAt=Objects.requireNonNull(at);LocalDate day=at.atZone(ZoneId.of("Asia/Manila")).toLocalDate();LocalDate end=day.isBefore(effectiveFrom)?effectiveFrom:day;if(effectiveTo==null||effectiveTo.isAfter(end))effectiveTo=end;status=Status.RETIRED;}
 public void supersede(LocalDate successorFrom,String actor,Instant at){if(status!=Status.PUBLISHED)throw new IllegalLifecycleTransitionException("Only a published policy may be superseded");if(successorFrom==null||!successorFrom.isAfter(effectiveFrom))throw new IllegalArgumentException("A successor must become effective after its predecessor");effectiveTo=successorFrom.minusDays(1);retiredBy=requiredText(actor,"actor");retirementReason="Superseded by a published revision";retiredAt=Objects.requireNonNull(at);status=Status.RETIRED;}
 public boolean effectiveOn(LocalDate day){return status==Status.PUBLISHED&&!day.isBefore(effectiveFrom)&&(effectiveTo==null||!day.isAfter(effectiveTo));}
 private void apply(String t,String d,String basis,String label,Frequency f,boolean mid,boolean self,boolean calibration,boolean acknowledgment,boolean appeal){title=requiredText(t,"title");description=optionalText(d);legalBasis=requiredText(basis,"legalBasis");displayLabel=requiredText(label,"displayLabel");cycleFrequency=Objects.requireNonNull(f,"cycleFrequency");requiresMidCycleReview=mid;requiresSelfAssessment=self;requiresPmtCalibration=calibration;requiresAcknowledgment=acknowledgment;requiresAppeal=appeal;}
 private void draft(){if(status!=Status.DRAFT)throw new IllegalLifecycleTransitionException("Published policy versions are immutable; create a revision");}
 public String getPolicyId(){return policyId;}public int getDefinitionVersion(){return definitionVersion;}public String getSupersedesId(){return supersedesId;}public String getTitle(){return title;}public String getDescription(){return description;}public String getLegalBasis(){return legalBasis;}public String getDisplayLabel(){return displayLabel;}public Frequency getCycleFrequency(){return cycleFrequency;}public boolean isRequiresMidCycleReview(){return requiresMidCycleReview;}public boolean isRequiresSelfAssessment(){return requiresSelfAssessment;}public boolean isRequiresPmtCalibration(){return requiresPmtCalibration;}public boolean isRequiresAcknowledgment(){return requiresAcknowledgment;}public boolean isRequiresAppeal(){return requiresAppeal;}public Status getStatus(){return status;}public LocalDate getEffectiveFrom(){return effectiveFrom;}public LocalDate getEffectiveTo(){return effectiveTo;}public String getPublishedBy(){return publishedBy;}public Instant getPublishedAt(){return publishedAt;}public String getRetiredBy(){return retiredBy;}public Instant getRetiredAt(){return retiredAt;}public String getRetirementReason(){return retirementReason;}
}
