package com.primehr.rsp.screening.domain;
import com.primehr.rsp.domain.RspAuditedEntity; import jakarta.persistence.*; import java.math.BigDecimal; import java.util.Locale;
@Entity @Table(name="rsp_screening_policy_criterion",uniqueConstraints=@UniqueConstraint(name="uk_rsp_screening_criterion_code",columnNames={"agency_id","policy_id","normalized_code"}))
public class ScreeningCriterion extends RspAuditedEntity {
 public enum Category { REQUIRED_DOCUMENT, EDUCATION, TRAINING, EXPERIENCE, ELIGIBILITY, LICENSE, COMPETENCY_PREREQUISITE, SCREENING_QUESTION }
 public enum EvaluationMode { PRESENCE, NUMERIC_THRESHOLD, DATE_OR_DURATION, MANUAL_REVIEW, DECLARATION }
 @Column(name="policy_id",nullable=false,length=36) private String policyId; @Column(nullable=false,length=80) private String code; @Column(name="normalized_code",nullable=false,length=80) private String normalizedCode; @Column(nullable=false,length=300) private String label; @Column(name="internal_instructions",length=2000) private String internalInstructions; @Column(name="public_guidance",length=1000) private String publicGuidance; @Enumerated(EnumType.STRING) @Column(nullable=false,length=40) private Category category; @Enumerated(EnumType.STRING) @Column(name="evaluation_mode",nullable=false,length=30) private EvaluationMode evaluationMode; @Column(name="source_key",length=100) private String sourceKey; @Column(name="threshold_value",precision=19,scale=4) private BigDecimal thresholdValue; @Column(name="threshold_unit",length=30) private String thresholdUnit; @Column(nullable=false) private boolean mandatory; @Column(nullable=false) private boolean disqualifying; @Column(name="allows_not_applicable",nullable=false) private boolean allowsNotApplicable; @Column(name="requires_remarks",nullable=false) private boolean requiresRemarks; @Column(name="requires_evidence",nullable=false) private boolean requiresEvidence; @Column(name="display_order",nullable=false) private int displayOrder;
 protected ScreeningCriterion() {}
 public ScreeningCriterion(String agency,String policyId,String code,String label,String instructions,String guidance,Category category,EvaluationMode mode,String sourceKey,BigDecimal threshold,String unit,boolean mandatory,boolean disqualifying,boolean allowsNa,boolean remarks,boolean evidence,int order){super(agency);this.policyId=requiredText(policyId,"policyId");this.code=requiredText(code,"code");normalizedCode=this.code.toUpperCase(Locale.ROOT);this.label=requiredText(label,"label");internalInstructions=optionalText(instructions);publicGuidance=optionalText(guidance);this.category=java.util.Objects.requireNonNull(category);evaluationMode=java.util.Objects.requireNonNull(mode);this.sourceKey=optionalText(sourceKey);thresholdValue=threshold;thresholdUnit=optionalText(unit);this.mandatory=mandatory;this.disqualifying=disqualifying;allowsNotApplicable=allowsNa;requiresRemarks=remarks;requiresEvidence=evidence;if(order<0)throw new IllegalArgumentException("displayOrder cannot be negative");displayOrder=order;validate();}
 private void validate(){if(disqualifying&&!mandatory)throw new IllegalArgumentException("A disqualifying criterion must be mandatory");if((evaluationMode==EvaluationMode.NUMERIC_THRESHOLD||evaluationMode==EvaluationMode.DATE_OR_DURATION)&&(thresholdValue==null||thresholdUnit==null))throw new IllegalArgumentException("Numeric and duration thresholds require value and unit");if((evaluationMode==EvaluationMode.PRESENCE||evaluationMode==EvaluationMode.NUMERIC_THRESHOLD||evaluationMode==EvaluationMode.DATE_OR_DURATION||evaluationMode==EvaluationMode.DECLARATION)&&sourceKey==null)throw new IllegalArgumentException("Objective criteria require sourceKey");if(evaluationMode==EvaluationMode.MANUAL_REVIEW&&(thresholdValue!=null||thresholdUnit!=null||sourceKey!=null))throw new IllegalArgumentException("Manual review cannot define an automatic source or threshold");}
 public String getPolicyId(){return policyId;} public String getCode(){return code;} public String getLabel(){return label;} public String getInternalInstructions(){return internalInstructions;} public String getPublicGuidance(){return publicGuidance;} public Category getCategory(){return category;} public EvaluationMode getEvaluationMode(){return evaluationMode;} public String getSourceKey(){return sourceKey;} public BigDecimal getThresholdValue(){return thresholdValue;} public String getThresholdUnit(){return thresholdUnit;} public boolean isMandatory(){return mandatory;} public boolean isDisqualifying(){return disqualifying;} public boolean isAllowsNotApplicable(){return allowsNotApplicable;} public boolean isRequiresRemarks(){return requiresRemarks;} public boolean isRequiresEvidence(){return requiresEvidence;} public int getDisplayOrder(){return displayOrder;}
}
