package com.primehr.rsp.screening.domain;
import com.primehr.rsp.domain.RspAuditedEntity; import jakarta.persistence.*; import java.util.Locale;
@Entity @Table(name="rsp_screening_reason_code",uniqueConstraints=@UniqueConstraint(name="uk_rsp_screening_reason_code",columnNames={"agency_id","policy_id","normalized_code"}))
public class ScreeningReasonCode extends RspAuditedEntity {
 public enum Outcome { QUALIFIED, DISQUALIFIED }
 @Column(name="policy_id",nullable=false,length=36) private String policyId; @Column(nullable=false,length=80) private String code; @Column(name="normalized_code",nullable=false,length=80) private String normalizedCode; @Column(nullable=false,length=300) private String label; @Column(name="public_safe_text",nullable=false,length=1000) private String publicSafeText; @Enumerated(EnumType.STRING) @Column(name="outcome_compatibility",nullable=false,length=20) private Outcome outcomeCompatibility; @Column(name="remarks_required",nullable=false) private boolean remarksRequired; @Column(name="display_order",nullable=false) private int displayOrder;
 protected ScreeningReasonCode(){} public ScreeningReasonCode(String agency,String policy,String code,String label,String safe,Outcome outcome,boolean remarks,int order){super(agency);policyId=requiredText(policy,"policyId");this.code=requiredText(code,"code");normalizedCode=this.code.toUpperCase(Locale.ROOT);this.label=requiredText(label,"label");publicSafeText=requiredText(safe,"publicSafeText");outcomeCompatibility=java.util.Objects.requireNonNull(outcome);remarksRequired=remarks;if(order<0)throw new IllegalArgumentException("displayOrder cannot be negative");displayOrder=order;}
 public String getPolicyId(){return policyId;} public String getCode(){return code;} public String getLabel(){return label;} public String getPublicSafeText(){return publicSafeText;} public Outcome getOutcomeCompatibility(){return outcomeCompatibility;} public boolean isRemarksRequired(){return remarksRequired;} public int getDisplayOrder(){return displayOrder;}
}
