package com.primehr.rsp.screening.domain;
import com.primehr.rsp.domain.RspAuditedEntity; import jakarta.persistence.*; import org.hibernate.annotations.Nationalized; import java.time.Instant; import java.util.Objects;
@Entity @Table(name="rsp_screening_finding",uniqueConstraints=@UniqueConstraint(name="uk_rsp_screening_finding",columnNames={"agency_id","case_id","criterion_id"}))
public class ScreeningFinding extends RspAuditedEntity {
 public enum Result { MET, NOT_MET, NEEDS_REVIEW, NOT_APPLICABLE }
 @Column(name="case_id",nullable=false,length=36) private String caseId; @Column(name="criterion_id",nullable=false,length=36) private String criterionId; @Column(name="criterion_code",nullable=false,length=80) private String criterionCode; @Nationalized @Column(name="criterion_label",nullable=false,length=300) private String criterionLabel; @Column(nullable=false) private boolean mandatory; @Column(nullable=false) private boolean disqualifying; @Column(name="allows_not_applicable",nullable=false) private boolean allowsNotApplicable; @Column(name="requires_remarks",nullable=false) private boolean requiresRemarks; @Column(name="requires_evidence",nullable=false) private boolean requiresEvidence; @Column(name="display_order",nullable=false) private int displayOrder; @Enumerated(EnumType.STRING) @Column(length=30) private Result result; @Nationalized @Column(length=2000) private String remarks; @Column(name="human_confirmed",nullable=false) private boolean humanConfirmed; @Column(name="confirmed_by",length=100) private String confirmedBy; @Column(name="confirmed_at") private Instant confirmedAt;
 protected ScreeningFinding(){} public ScreeningFinding(String agency,String caseId,ScreeningCriterion c){super(agency);this.caseId=requiredText(caseId,"caseId");criterionId=requiredText(c.getId(),"criterionId");criterionCode=c.getCode();criterionLabel=c.getLabel();mandatory=c.isMandatory();disqualifying=c.isDisqualifying();allowsNotApplicable=c.isAllowsNotApplicable();requiresRemarks=c.isRequiresRemarks();requiresEvidence=c.isRequiresEvidence();displayOrder=c.getDisplayOrder();}
 public void record(Result result,String remarks,String actor,Instant at){this.result=Objects.requireNonNull(result);if(result==Result.NOT_APPLICABLE&&!allowsNotApplicable)throw new IllegalArgumentException("Criterion does not permit NOT_APPLICABLE");this.remarks=optionalText(remarks);if(requiresRemarks&&this.remarks==null)throw new IllegalArgumentException("Remarks are required");humanConfirmed=true;confirmedBy=requiredText(actor,"actor");confirmedAt=Objects.requireNonNull(at);}
 public String getCaseId(){return caseId;} public String getCriterionId(){return criterionId;} public String getCriterionCode(){return criterionCode;} public String getCriterionLabel(){return criterionLabel;} public boolean isMandatory(){return mandatory;} public boolean isDisqualifying(){return disqualifying;} public boolean isAllowsNotApplicable(){return allowsNotApplicable;} public boolean isRequiresRemarks(){return requiresRemarks;} public boolean isRequiresEvidence(){return requiresEvidence;} public int getDisplayOrder(){return displayOrder;} public Result getResult(){return result;} public String getRemarks(){return remarks;} public boolean isHumanConfirmed(){return humanConfirmed;} public String getConfirmedBy(){return confirmedBy;} public Instant getConfirmedAt(){return confirmedAt;}
}
