package com.primehr.performancemanagement.application;
import com.primehr.performancemanagement.api.PerformanceManagementDtos.*;import com.primehr.performancemanagement.domain.*;import com.primehr.performancemanagement.infrastructure.*;import com.primehr.shared.audit.PrimeHrAuditService;import com.primehr.shared.exception.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service @Transactional public class PerformancePolicyServiceImpl implements PerformancePolicyService{
 private final PerformancePolicyRepository policies;private final PerformancePolicyVersionRepository versions;private final PrimeHrAuditService audit;
 public PerformancePolicyServiceImpl(PerformancePolicyRepository p,PerformancePolicyVersionRepository v,PrimeHrAuditService a){policies=p;versions=v;audit=a;}
 @Override@Transactional(readOnly=true)public List<PolicyResponse>list(String agency){return versions.findByAgencyIdOrderByCreatedAtDesc(agency).stream().map(v->response(agency,v)).toList();}
 @Override@Transactional(readOnly=true)public PolicyResponse get(String agency,String id){return response(agency,version(agency,id));}
 @Override public PolicyResponse create(String agency,PolicyInput r,String correlation){if(r.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");String normalized=r.code().trim().toUpperCase(Locale.ROOT);if(policies.existsByAgencyIdAndNormalizedCode(agency,normalized))throw new IllegalArgumentException("Performance policy code already exists");PerformancePolicy p=policies.saveAndFlush(new PerformancePolicy(agency,r.code()));PerformancePolicyVersion v=versions.saveAndFlush(createVersion(agency,p.getId(),1,null,r));PolicyResponse after=response(agency,v);audit.record(agency,"CREATE_PERFORMANCE_POLICY_DRAFT","SPMS_POLICY_VERSION",v.getId(),1,v.getVersion(),null,after,null,correlation);return after;}
 @Override public PolicyResponse update(String agency,String id,PolicyInput r,String correlation){PerformancePolicyVersion v=version(agency,id);requireVersion(v.getVersion(),r.recordVersion());PerformancePolicy p=policy(agency,v.getPolicyId());if(!p.getCode().equalsIgnoreCase(r.code()))throw new IllegalArgumentException("Policy code is stable; create a separate policy for a new code");PolicyResponse before=response(agency,v);v.update(r.title(),r.description(),r.legalBasis(),r.displayLabel(),r.cycleFrequency(),r.requiresMidCycleReview(),r.requiresSelfAssessment(),r.requiresPmtCalibration(),r.requiresAcknowledgment(),r.requiresAppeal());v=versions.saveAndFlush(v);PolicyResponse after=response(agency,v);audit.record(agency,"UPDATE_PERFORMANCE_POLICY_DRAFT","SPMS_POLICY_VERSION",id,v.getDefinitionVersion(),v.getVersion(),before,after,null,correlation);return after;}
 @Override public PolicyResponse publish(String agency,String id,PolicyTransition r,String correlation){PerformancePolicyVersion v=version(agency,id);requireVersion(v.getVersion(),r.recordVersion());List<PerformancePolicyVersion> overlaps=versions.overlapping(agency,r.effectiveFrom(),r.effectiveTo()==null?LocalDate.of(9999,12,31):r.effectiveTo());PerformancePolicyVersion prior=v.getSupersedesId()==null?null:version(agency,v.getSupersedesId());if(prior!=null&&(!r.effectiveFrom().isAfter(prior.getEffectiveFrom())))throw new IllegalArgumentException("A revision must become effective after its predecessor");if(overlaps.stream().anyMatch(x->prior==null||!x.getId().equals(prior.getId())))throw new IllegalArgumentException("A published policy is already effective in the requested interval");String actor=audit.currentActor();Instant now=Instant.now();PolicyResponse before=response(agency,v);v.publish(r.effectiveFrom(),r.effectiveTo(),actor,now);v=versions.saveAndFlush(v);if(prior!=null){prior.supersede(r.effectiveFrom(),actor,now);versions.saveAndFlush(prior);}PolicyResponse after=response(agency,v);audit.record(agency,"PUBLISH_PERFORMANCE_POLICY","SPMS_POLICY_VERSION",id,v.getDefinitionVersion(),v.getVersion(),before,after,r.reason(),correlation);return after;}
 @Override public PolicyResponse revision(String agency,String id,VersionTransition r,String correlation){PerformancePolicyVersion prior=version(agency,id);requireVersion(prior.getVersion(),r.recordVersion());if(prior.getStatus()!=PerformancePolicyVersion.Status.PUBLISHED)throw new IllegalArgumentException("Only a published policy can have a revision");int number=versions.findByAgencyIdAndPolicyIdOrderByDefinitionVersionDesc(agency,prior.getPolicyId()).stream().mapToInt(PerformancePolicyVersion::getDefinitionVersion).max().orElse(0)+1;PerformancePolicyVersion v=versions.saveAndFlush(new PerformancePolicyVersion(agency,prior.getPolicyId(),number,prior.getId(),prior.getTitle(),prior.getDescription(),prior.getLegalBasis(),prior.getDisplayLabel(),prior.getCycleFrequency(),prior.isRequiresMidCycleReview(),prior.isRequiresSelfAssessment(),prior.isRequiresPmtCalibration(),prior.isRequiresAcknowledgment(),prior.isRequiresAppeal()));PolicyResponse after=response(agency,v);audit.record(agency,"CREATE_PERFORMANCE_POLICY_REVISION","SPMS_POLICY_VERSION",v.getId(),number,v.getVersion(),null,after,r.reason(),correlation);return after;}
 @Override public PolicyResponse retire(String agency,String id,VersionTransition r,String correlation){PerformancePolicyVersion v=version(agency,id);requireVersion(v.getVersion(),r.recordVersion());PolicyResponse before=response(agency,v);v.retire(audit.currentActor(),r.reason(),Instant.now());v=versions.saveAndFlush(v);PolicyResponse after=response(agency,v);audit.record(agency,"RETIRE_PERFORMANCE_POLICY","SPMS_POLICY_VERSION",id,v.getDefinitionVersion(),v.getVersion(),before,after,r.reason(),correlation);return after;}
 @Override@Transactional(readOnly=true)public PolicyResponse effective(String agency,LocalDate on){return versions.overlapping(agency,on,on).stream().filter(v->v.effectiveOn(on)).findFirst().map(v->response(agency,v)).orElseThrow(()->new ResourceNotFoundException("No performance policy is effective on the requested date"));}
 private PerformancePolicyVersion createVersion(String a,String p,int n,String prior,PolicyInput r){return new PerformancePolicyVersion(a,p,n,prior,r.title(),r.description(),r.legalBasis(),r.displayLabel(),r.cycleFrequency(),r.requiresMidCycleReview(),r.requiresSelfAssessment(),r.requiresPmtCalibration(),r.requiresAcknowledgment(),r.requiresAppeal());}
 private PolicyResponse response(String agency,PerformancePolicyVersion v){PerformancePolicy p=policy(agency,v.getPolicyId());return new PolicyResponse(v.getId(),p.getId(),p.getCode(),v.getTitle(),v.getDescription(),v.getLegalBasis(),v.getDisplayLabel(),v.getCycleFrequency().name(),v.getDefinitionVersion(),v.getSupersedesId(),v.getStatus().name(),v.getEffectiveFrom(),v.getEffectiveTo(),v.getPublishedBy(),v.getPublishedAt(),v.getRetiredBy(),v.getRetiredAt(),v.getRetirementReason(),v.isRequiresMidCycleReview(),v.isRequiresSelfAssessment(),v.isRequiresPmtCalibration(),v.isRequiresAcknowledgment(),v.isRequiresAppeal(),v.getVersion());}
 private PerformancePolicyVersion version(String a,String id){return versions.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance policy version not found"));}private PerformancePolicy policy(String a,String id){return policies.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance policy not found"));}static void requireVersion(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticConflictException("Expected recordVersion "+expected+" but current version is "+actual);}
}
