package com.primehr.performancemanagement.application;

import com.primehr.integration.administrative.*;
import com.primehr.integration.humanresource.*;
import com.primehr.performancemanagement.api.PerformanceCommitmentWorkflowDtos.*;
import com.primehr.performancemanagement.domain.*;
import com.primehr.performancemanagement.infrastructure.*;
import com.primehr.shared.audit.PrimeHrAuditService;
import com.primehr.shared.exception.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service @Transactional
public class PerformanceCommitmentWorkflowServiceImpl implements PerformanceCommitmentWorkflowService {
    private static final String OFFICE_ROUTE="PERFORMANCE_OFFICE_COMMITMENT", EMPLOYEE_ROUTE="PERFORMANCE_INDIVIDUAL_COMMITMENT";
    private final PerformanceCommitmentVersionRepository versions; private final PerformanceCommitmentRouteRepository routes;
    private final PerformanceCommitmentRouteStepRepository steps; private final PerformanceCommitmentActionRepository actions;
    private final PerformanceCycleMilestoneRepository milestones; private final PerformancePlanAssignmentRepository assignments;
    private final PerformanceCommitmentService commitments; private final AdministrativePerformancePlanningClient administrative;
    private final HumanResourcePerformanceParticipantClient humanResource; private final PrimeHrAuditService audit;
    public PerformanceCommitmentWorkflowServiceImpl(PerformanceCommitmentVersionRepository v,PerformanceCommitmentRouteRepository r,PerformanceCommitmentRouteStepRepository s,PerformanceCommitmentActionRepository a,PerformanceCycleMilestoneRepository m,PerformancePlanAssignmentRepository p,PerformanceCommitmentService c,AdministrativePerformancePlanningClient ad,HumanResourcePerformanceParticipantClient hr,PrimeHrAuditService au){versions=v;routes=r;steps=s;actions=a;milestones=m;assignments=p;commitments=c;administrative=ad;humanResource=hr;audit=au;}

    @Override @Transactional(readOnly=true) public WorkflowResponse get(String agency,String id,String actor,PermissionDataScope scope){PerformanceCommitmentVersion v=version(agency,id);access(agency,v,actor,scope);return response(agency,v);}
    @Override public WorkflowResponse submit(String agency,String id,Command c,String token,String actor,PermissionDataScope scope,String correlation){PerformanceCommitmentVersion v=version(agency,id);owner(v,actor,scope);PerformanceCommitmentAction prior=idempotent(agency,id,c.requestKey(),v.getStatus()==PerformanceCommitmentVersion.Status.RETURNED?PerformanceCommitmentAction.Type.RESUBMIT:PerformanceCommitmentAction.Type.SUBMIT);if(prior!=null)return response(agency,v);check(v,c,false);boolean resubmit=v.getStatus()==PerformanceCommitmentVersion.Status.RETURNED;window(agency,v,PerformanceCycleMilestone.Type.PLANNING_OPEN,PerformanceCycleMilestone.Type.PLANNING_DUE,c);var ready=commitments.readiness(agency,id,token,actor,PermissionDataScope.AGENCY_WIDE);if(!ready.ready())throw new IllegalArgumentException(String.join("; ",ready.errors()));PerformancePlanAssignment assignment=assignments.findByIdAndAgencyId(v.getAssignmentId(),agency).orElseThrow(()->new ResourceNotFoundException("Performance plan assignment not found"));AdministrativePerformancePlanningClient.ApprovalRoute source=administrative.approvalRoute(v.getBusinessUnitId(),"EMPLOYEE".equals(v.getSubjectType())?EMPLOYEE_ROUTE:OFFICE_ROUTE,token);if(!resubmit&&!Objects.equals(source.sourceFingerprint(),assignment.getRouteFingerprint()))throw new IllegalArgumentException("Approval route changed after assignment activation");PerformanceCommitmentRoute old=routes.findFirstByAgencyIdAndCommitmentVersionIdOrderByRouteRevisionDesc(agency,id).orElse(null);if(old!=null)old.finish(PerformanceCommitmentRoute.Status.SUPERSEDED);int revision=old==null?1:old.getRouteRevision()+1;PerformanceCommitmentRoute route=snapshot(agency,v,source,revision,token,actor);String before=v.getStatus().name();v.submit(resubmit);v=versions.saveAndFlush(v);record(agency,v,route,null,resubmit?PerformanceCommitmentAction.Type.RESUBMIT:PerformanceCommitmentAction.Type.SUBMIT,c,before,correlation);return response(agency,v);}
    @Override public WorkflowResponse withdraw(String agency,String id,Command c,String actor,PermissionDataScope scope,String correlation){PerformanceCommitmentVersion v=version(agency,id);owner(v,actor,scope);if(idempotent(agency,id,c.requestKey(),PerformanceCommitmentAction.Type.WITHDRAW)!=null)return response(agency,v);check(v,c,true);PerformanceCommitmentRoute route=current(agency,id);if(actions.countByAgencyIdAndRouteIdAndTypeIn(agency,route.getId(),List.of(PerformanceCommitmentAction.Type.RECOMMEND,PerformanceCommitmentAction.Type.RETURN,PerformanceCommitmentAction.Type.APPROVE,PerformanceCommitmentAction.Type.REJECT))>0)throw new IllegalStateException("A commitment may be withdrawn only before the first route decision");String before=v.getStatus().name();v.withdrawn();route.finish(PerformanceCommitmentRoute.Status.WITHDRAWN);skipPending(agency,route);versions.saveAndFlush(v);record(agency,v,route,null,PerformanceCommitmentAction.Type.WITHDRAW,c,before,correlation);return response(agency,v);}
    @Override public WorkflowResponse recommend(String agency,String id,Command c,String token,String actor,String correlation){return decide(agency,id,c,token,actor,PerformanceCommitmentAction.Type.RECOMMEND,correlation);}
    @Override public WorkflowResponse returnForChanges(String agency,String id,Command c,String token,String actor,String correlation){return decide(agency,id,c,token,actor,PerformanceCommitmentAction.Type.RETURN,correlation);}
    @Override public WorkflowResponse approve(String agency,String id,Command c,String token,String actor,String correlation){return decide(agency,id,c,token,actor,PerformanceCommitmentAction.Type.APPROVE,correlation);}
    @Override public WorkflowResponse reject(String agency,String id,Command c,String token,String actor,String correlation){return decide(agency,id,c,token,actor,PerformanceCommitmentAction.Type.REJECT,correlation);}
    @Override public WorkflowResponse voidRecord(String agency,String id,Command c,String actor,String correlation){PerformanceCommitmentVersion v=version(agency,id);if(idempotent(agency,id,c.requestKey(),PerformanceCommitmentAction.Type.VOID)!=null)return response(agency,v);check(v,c,c.routeRevision()!=null);reason(c);PerformanceCommitmentRoute route=routes.findFirstByAgencyIdAndCommitmentVersionIdOrderByRouteRevisionDesc(agency,id).orElse(null);String before=v.getStatus().name();v.voided();if(route!=null){route.finish(PerformanceCommitmentRoute.Status.VOIDED);skipPending(agency,route);}versions.saveAndFlush(v);record(agency,v,route,null,PerformanceCommitmentAction.Type.VOID,c,before,correlation);return response(agency,v);}
    @Override public WorkflowResponse rebase(String agency,String id,Command c,String token,String actor,String correlation){PerformanceCommitmentVersion v=version(agency,id);if(idempotent(agency,id,c.requestKey(),PerformanceCommitmentAction.Type.ROUTE_REBASE)!=null)return response(agency,v);check(v,c,true);reason(c);PerformanceCommitmentRoute old=current(agency,id);if(actions.countByAgencyIdAndRouteIdAndTypeIn(agency,old.getId(),List.of(PerformanceCommitmentAction.Type.RECOMMEND,PerformanceCommitmentAction.Type.RETURN,PerformanceCommitmentAction.Type.APPROVE,PerformanceCommitmentAction.Type.REJECT))>0)throw new IllegalStateException("A route may be rebased only before its first decision");var source=administrative.approvalRoute(v.getBusinessUnitId(),"EMPLOYEE".equals(v.getSubjectType())?EMPLOYEE_ROUTE:OFFICE_ROUTE,token);old.finish(PerformanceCommitmentRoute.Status.SUPERSEDED);skipPending(agency,old);PerformanceCommitmentRoute route=snapshot(agency,v,source,old.getRouteRevision()+1,token,actor);String before=v.getStatus().name();v.routeRebased();versions.saveAndFlush(v);record(agency,v,route,null,PerformanceCommitmentAction.Type.ROUTE_REBASE,c,before,correlation);return response(agency,v);}

    private WorkflowResponse decide(String agency,String id,Command c,String token,String actor,PerformanceCommitmentAction.Type type,String correlation){PerformanceCommitmentVersion v=version(agency,id);if(idempotent(agency,id,c.requestKey(),type)!=null)return response(agency,v);check(v,c,true);reason(c);window(agency,v,PerformanceCycleMilestone.Type.PLANNING_OPEN,PerformanceCycleMilestone.Type.APPROVAL_DUE,c);PerformanceCommitmentRoute route=current(agency,id);PerformanceCommitmentRouteStep step=steps.findByAgencyIdAndRouteIdAndLevel(agency,route.getId(),route.getCurrentLevel()).orElseThrow(()->new IllegalStateException("Current route step is missing"));if(!step.getEmployeeNo().equalsIgnoreCase(actor))throw new AccessDeniedException("Only the current route actor may decide");HumanResourceAssessmentSubject current=humanResource.getByEmployeeNo(actor,token);if(!current.eligible()||!Objects.equals(current.sourceFingerprint(),step.getParticipantFingerprint()))throw new IllegalArgumentException("Current route actor appointment source changed");String before=v.getStatus().name();Instant now=Instant.now();switch(type){case RECOMMEND->{if(step.getActionType()!=PerformanceCommitmentRouteStep.ActionType.RECOMMEND)throw new IllegalStateException("The final route step cannot recommend");step.decide(PerformanceCommitmentRouteStep.Status.RECOMMENDED,actor,c.reason(),now);PerformanceCommitmentRouteStep next=steps.findByAgencyIdAndRouteIdAndLevel(agency,route.getId(),step.getLevel()+1).orElseThrow(()->new IllegalStateException("The next route step is missing"));next.makeCurrent();route.advance(next.getLevel());v.recommended();}case RETURN->{step.decide(PerformanceCommitmentRouteStep.Status.RETURNED,actor,c.reason(),now);route.finish(PerformanceCommitmentRoute.Status.RETURNED);skipPending(agency,route);v.returned();}case APPROVE->{if(step.getActionType()!=PerformanceCommitmentRouteStep.ActionType.APPROVE)throw new IllegalStateException("Only the final route step may approve");step.decide(PerformanceCommitmentRouteStep.Status.APPROVED,actor,c.reason(),now);route.finish(PerformanceCommitmentRoute.Status.COMPLETED);v.approved();}case REJECT->{if(step.getActionType()!=PerformanceCommitmentRouteStep.ActionType.APPROVE)throw new IllegalStateException("Only the final route step may reject");step.decide(PerformanceCommitmentRouteStep.Status.REJECTED,actor,c.reason(),now);route.finish(PerformanceCommitmentRoute.Status.REJECTED);v.rejected();}default->throw new IllegalArgumentException("Unsupported route decision");}versions.saveAndFlush(v);steps.saveAndFlush(step);record(agency,v,route,step,type,c,before,correlation);return response(agency,v);}
    private PerformanceCommitmentRoute snapshot(String agency,PerformanceCommitmentVersion v,AdministrativePerformancePlanningClient.ApprovalRoute source,int revision,String token,String actor){List<AdministrativePerformancePlanningClient.ApprovalRouteStep> configured=source.steps()==null?List.of():source.steps();if(configured.isEmpty()||configured.size()!=source.configuredMaximum())throw new IllegalArgumentException("Approval route must contain every configured level");Set<Long> people=new HashSet<>();for(int n=1;n<=configured.size();n++){var row=configured.get(n-1);if(row.level()!=n)throw new IllegalArgumentException("Approval route levels must be contiguous");if(!people.add(row.employeeId()))throw new IllegalArgumentException("Approval route actors must be unique");}PerformanceCommitmentRoute route=routes.saveAndFlush(new PerformanceCommitmentRoute(agency,v.getId(),revision,source.requestCode(),source.businessUnitId(),v.getOrganizationFingerprint(),source.sourceFingerprint(),v.getContentFingerprint(),v.getContentRevision(),actor,Instant.now()));for(int n=1;n<=configured.size();n++){var row=configured.get(n-1);HumanResourceAssessmentSubject person=humanResource.get(row.employeeId(),token);var membership=administrative.membership(row.employeeId(),token);if(!person.eligible()||person.appointmentId()==null||person.jobPositionId()==null||person.plantillaId()==null)throw new IllegalArgumentException("Every route actor requires an eligible active appointment");if(!Objects.equals(membership.businessUnitId(),v.getBusinessUnitId()))throw new IllegalArgumentException("Every route actor must belong to the routing Business Unit");if(n==configured.size()&&person.employeeNo().equalsIgnoreCase(v.getOwnerEmployeeNo()))throw new IllegalArgumentException("The accountable owner cannot finally approve the commitment");steps.save(new PerformanceCommitmentRouteStep(agency,route.getId(),n,n==configured.size()?PerformanceCommitmentRouteStep.ActionType.APPROVE:PerformanceCommitmentRouteStep.ActionType.RECOMMEND,person.employeeId(),person.employeeNo(),person.displayName(),person.appointmentId(),person.jobPositionId(),person.plantillaId(),person.sourceFingerprint(),membership.sourceFingerprint()));}steps.flush();return route;}
    private void window(String agency,PerformanceCommitmentVersion v,PerformanceCycleMilestone.Type openType,PerformanceCycleMilestone.Type dueType,Command c){Instant now=Instant.now();Map<PerformanceCycleMilestone.Type,PerformanceCycleMilestone> map=new EnumMap<>(PerformanceCycleMilestone.Type.class);for(var m:milestones.findByAgencyIdAndCycleIdOrderByDisplayOrderAsc(agency,v.getCycleId()))map.put(m.getType(),m);PerformanceCycleMilestone open=map.get(openType),due=map.get(dueType);boolean valid=open!=null&&due!=null&&!now.isBefore(open.getStartsAt())&&!now.isAfter(due.getEndsAt()==null?due.getStartsAt():due.getEndsAt());if(valid)return;if(!c.overrideWindow())throw new IllegalStateException("The required "+openType+"/"+dueType+" cycle window is closed or missing");if(c.overrideMilestone()==null||!c.overrideMilestone().equals(dueType.name()))throw new IllegalArgumentException("Window override must name the missed milestone "+dueType);reason(c);}
    private void record(String agency,PerformanceCommitmentVersion v,PerformanceCommitmentRoute route,PerformanceCommitmentRouteStep step,PerformanceCommitmentAction.Type type,Command c,String before,String correlation){if(type==PerformanceCommitmentAction.Type.APPROVE&&v.getSupersedesId()!=null){PerformanceCommitmentVersion prior=version(agency,v.getSupersedesId());prior.superseded();versions.saveAndFlush(prior);}PerformanceCommitmentAction action=actions.saveAndFlush(new PerformanceCommitmentAction(agency,v.getId(),route==null?null:route.getId(),step==null?null:step.getId(),type,c.requestKey(),audit.currentActor(),before,v.getStatus().name(),v.getContentRevision(),v.getLifecycleRevision(),route==null?null:route.getRouteRevision(),c.reason(),c.overrideWindow()?c.overrideMilestone():null,Instant.now()));audit.record(agency,"PERFORMANCE_COMMITMENT_"+type,"SPMS_COMMITMENT_VERSION",v.getId(),null,v.getVersion(),Map.of("status",before),Map.of("status",v.getStatus().name(),"actionId",action.getId()),c.reason(),correlation);}
    private PerformanceCommitmentAction idempotent(String agency,String id,String key,PerformanceCommitmentAction.Type expected){if(key==null||key.isBlank())throw new IllegalArgumentException("requestKey is required");var found=actions.findByAgencyIdAndCommitmentVersionIdAndRequestKey(agency,id,key.trim());if(found.isEmpty())return null;if(found.get().getType()!=expected)throw new OptimisticConflictException("requestKey was already used for another action");return found.get();}
    private void check(PerformanceCommitmentVersion v,Command c,boolean route){if(v.getVersion()!=c.recordVersion())throw new OptimisticConflictException("The commitment recordVersion is stale");if(v.getContentRevision()!=c.contentRevision()||v.getLifecycleRevision()!=c.lifecycleRevision())throw new OptimisticConflictException("The commitment content or lifecycle revision is stale");if(route&&(c.routeRevision()==null||current(v.getAgencyId(),v.getId()).getRouteRevision()!=c.routeRevision()))throw new OptimisticConflictException("The commitment route revision is stale");}
    private void owner(PerformanceCommitmentVersion v,String actor,PermissionDataScope scope){if(scope!=PermissionDataScope.AGENCY_WIDE&&!v.getOwnerEmployeeNo().equalsIgnoreCase(actor))throw new AccessDeniedException("Only the accountable owner may perform this transition");}
    private void access(String agency,PerformanceCommitmentVersion v,String actor,PermissionDataScope scope){if(scope==PermissionDataScope.AGENCY_WIDE||v.getOwnerEmployeeNo().equalsIgnoreCase(actor))return;boolean assigned=routes.findFirstByAgencyIdAndCommitmentVersionIdOrderByRouteRevisionDesc(agency,v.getId()).stream().flatMap(r->steps.findByAgencyIdAndRouteIdOrderByLevelAsc(agency,r.getId()).stream()).anyMatch(s->s.getEmployeeNo().equalsIgnoreCase(actor));if(!assigned)throw new AccessDeniedException("Commitment is outside the permitted ownership or assigned-task scope");}
    private void skipPending(String agency,PerformanceCommitmentRoute route){List<PerformanceCommitmentRouteStep> all=steps.findByAgencyIdAndRouteIdOrderByLevelAsc(agency,route.getId());all.forEach(PerformanceCommitmentRouteStep::cancel);steps.saveAll(all);}
    private static void reason(Command c){if(c.reason()==null||c.reason().isBlank())throw new IllegalArgumentException("A reason is required");}
    private PerformanceCommitmentRoute current(String agency,String id){return routes.findFirstByAgencyIdAndCommitmentVersionIdOrderByRouteRevisionDesc(agency,id).orElseThrow(()->new IllegalStateException("Commitment route was not found"));}
    private PerformanceCommitmentVersion version(String agency,String id){return versions.findByIdAndAgencyId(id,agency).orElseThrow(()->new ResourceNotFoundException("Performance commitment version not found"));}
    private WorkflowResponse response(String agency,PerformanceCommitmentVersion v){List<RouteResponse> routeResponses=routes.findByAgencyIdAndCommitmentVersionIdOrderByRouteRevisionAsc(agency,v.getId()).stream().map(r->new RouteResponse(r.getId(),r.getRouteRevision(),r.getRequestCode(),r.getBusinessUnitId(),r.getOrganizationFingerprint(),r.getRouteFingerprint(),r.getSubmittedContentFingerprint(),r.getSubmittedContentRevision(),r.getCurrentLevel(),r.getStatus().name(),r.getSubmittedBy(),r.getSubmittedAt(),steps.findByAgencyIdAndRouteIdOrderByLevelAsc(agency,r.getId()).stream().map(s->new StepResponse(s.getId(),s.getLevel(),s.getActionType().name(),s.getEmployeeId(),s.getEmployeeNo(),s.getEmployeeName(),s.getAppointmentId(),s.getJobPositionId(),s.getPlantillaId(),s.getParticipantFingerprint(),s.getOrganizationFingerprint(),s.getStatus().name(),s.getDecidedBy(),s.getDecidedAt(),s.getDecisionReason())).toList())).toList();List<ActionResponse> actionResponses=actions.findByAgencyIdAndCommitmentVersionIdOrderByActedAtAsc(agency,v.getId()).stream().map(x->new ActionResponse(x.getId(),x.getRouteId(),x.getRouteStepId(),x.getType().name(),x.getRequestKey(),x.getActorEmployeeNo(),x.getPriorStatus(),x.getResultStatus(),x.getContentRevision(),x.getLifecycleRevision(),x.getRouteRevision(),x.getReason(),x.getOverrideMilestone(),x.getActedAt())).toList();return new WorkflowResponse(commitments.get(agency,v.getId(),v.getOwnerEmployeeNo(),PermissionDataScope.AGENCY_WIDE),routeResponses,actionResponses);}
}
