package com.primehr.performancemanagement.application;

import com.primehr.integration.administrative.AdministrativePerformancePlanningClient;
import com.primehr.integration.humanresource.*;
import com.primehr.performancemanagement.api.PerformancePlanAssignmentDtos.*;
import com.primehr.performancemanagement.domain.*;
import com.primehr.performancemanagement.infrastructure.*;
import com.primehr.shared.audit.PrimeHrAuditService;
import com.primehr.shared.exception.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;

@Service @Transactional
public class PerformancePlanAssignmentServiceImpl implements PerformancePlanAssignmentService {
    private static final String OFFICE_ROUTE="PERFORMANCE_OFFICE_COMMITMENT", EMPLOYEE_ROUTE="PERFORMANCE_INDIVIDUAL_COMMITMENT";
    private final PerformancePlanAssignmentRepository assignments;private final PerformancePlanAssignmentObjectiveRepository links;
    private final PerformanceCycleRepository cycles;private final PerformanceTemplateVersionRepository templates;
    private final PerformanceObjectiveVersionRepository objectives;private final AdministrativePerformancePlanningClient administrative;
    private final HumanResourcePerformanceParticipantClient humanResource;private final PrimeHrAuditService audit;
    public PerformancePlanAssignmentServiceImpl(PerformancePlanAssignmentRepository a,PerformancePlanAssignmentObjectiveRepository l,
            PerformanceCycleRepository c,PerformanceTemplateVersionRepository t,PerformanceObjectiveVersionRepository o,
            AdministrativePerformancePlanningClient ad,HumanResourcePerformanceParticipantClient hr,PrimeHrAuditService au){assignments=a;links=l;cycles=c;templates=t;objectives=o;administrative=ad;humanResource=hr;audit=au;}
    @Override @Transactional(readOnly=true)public List<AssignmentResponse>list(String a){return assignments.findByAgencyIdOrderByCreatedAtDesc(a).stream().map(x->response(a,x)).toList();}
    @Override @Transactional(readOnly=true)public AssignmentResponse get(String a,String id){return response(a,assignment(a,id));}
    @Override public AssignmentResponse create(String a,AssignmentInput i,String token,String c){if(i.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");Resolved r=resolve(a,i,token,true);if(assignments.existsByAgencyIdAndCycleIdAndSubjectTypeAndSubjectIdAndFormType(a,i.cycleId(),i.subjectType(),i.subjectId(),r.template().getFormType().name()))throw new IllegalArgumentException("An assignment already exists for the cycle, subject and form type");PerformancePlanAssignment x=assignments.saveAndFlush(make(a,i,r));replace(a,x.getId(),r.objectiveIds());return audited(a,"CREATE_PERFORMANCE_PLAN_ASSIGNMENT_DRAFT",assignments.saveAndFlush(x),null,c,null);}
    @Override public AssignmentResponse update(String a,String id,AssignmentInput i,String token,String c){PerformancePlanAssignment x=assignment(a,id);check(x.getVersion(),i.recordVersion());Resolved r=resolve(a,i,token,true);AssignmentResponse before=response(a,x);apply(x,i,r);replace(a,id,r.objectiveIds());return audited(a,"UPDATE_PERFORMANCE_PLAN_ASSIGNMENT_DRAFT",assignments.saveAndFlush(x),before,c,null);}
    @Override public AssignmentResponse activate(String a,String id,Transition i,String token,String c){PerformancePlanAssignment x=assignment(a,id);check(x.getVersion(),i.recordVersion());AssignmentInput input=new AssignmentInput(x.getCycleId(),x.getTemplateVersionId(),x.getSubjectType(),x.getSubjectId(),x.getRoutingBusinessUnitId(),x.getOwnerEmployeeId(),links.findByAgencyIdAndAssignmentIdOrderByDisplayOrder(a,id).stream().map(PerformancePlanAssignmentObjective::getObjectiveVersionId).toList(),x.getVersion());Resolved r=resolve(a,input,token,false);List<String> errors=fingerprintErrors(x,r);if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));AssignmentResponse before=response(a,x);x.activate(audit.currentActor(),i.reason(),Instant.now());return audited(a,"ACTIVATE_PERFORMANCE_PLAN_ASSIGNMENT",assignments.saveAndFlush(x),before,c,i.reason());}
    @Override public AssignmentResponse retire(String a,String id,Transition i,String c){PerformancePlanAssignment x=assignment(a,id);check(x.getVersion(),i.recordVersion());AssignmentResponse before=response(a,x);x.retire(audit.currentActor(),i.reason(),Instant.now());return audited(a,"RETIRE_PERFORMANCE_PLAN_ASSIGNMENT",assignments.saveAndFlush(x),before,c,i.reason());}
    @Override @Transactional(readOnly=true)public ReadinessResponse readiness(String a,String id,String token){PerformancePlanAssignment x=assignment(a,id);try{AssignmentInput input=new AssignmentInput(x.getCycleId(),x.getTemplateVersionId(),x.getSubjectType(),x.getSubjectId(),x.getRoutingBusinessUnitId(),x.getOwnerEmployeeId(),links.findByAgencyIdAndAssignmentIdOrderByDisplayOrder(a,id).stream().map(PerformancePlanAssignmentObjective::getObjectiveVersionId).toList(),x.getVersion());Resolved r=resolve(a,input,token,false);List<String> e=fingerprintErrors(x,r);return new ReadinessResponse(e.isEmpty(),e);}catch(IllegalArgumentException|ResourceNotFoundException ex){return new ReadinessResponse(false,List.of(ex.getMessage()));}}
    private Resolved resolve(String a,AssignmentInput i,String token,boolean draft){PerformanceCycle cycle=cycles.findByIdAndAgencyId(i.cycleId(),a).orElseThrow(()->new ResourceNotFoundException("Performance cycle not found"));if(cycle.getStatus()==PerformanceCycle.Status.CANCELLED||cycle.getStatus()==PerformanceCycle.Status.CLOSED)throw new IllegalArgumentException("Assignments require a draft or open cycle");PerformanceTemplateVersion template=templates.findByIdAndAgencyId(i.templateVersionId(),a).orElseThrow(()->new ResourceNotFoundException("Performance template version not found"));if(template.getStatus()!=PerformanceTemplateVersion.Status.PUBLISHED||!contains(template.getEffectiveFrom(),template.getEffectiveTo(),cycle.getPeriodStart(),cycle.getPeriodEnd()))throw new IllegalArgumentException("A published template effective for the whole cycle is required");if(!template.getPolicyVersionId().equals(cycle.getPolicyVersionId()))throw new IllegalArgumentException("Template and cycle must use the same policy version");validateForm(i.subjectType(),template.getFormType());HumanResourceAssessmentSubject owner=humanResource.get(i.ownerEmployeeId(),token);if(!owner.eligible()||owner.appointmentId()==null||owner.jobPositionId()==null||owner.plantillaId()==null)throw new IllegalArgumentException("The assignment owner requires an eligible active appointment");var membership=administrative.membership(i.ownerEmployeeId(),token);Subject subject=subject(i,owner,membership,token);var route=administrative.approvalRoute(subject.routingBusinessUnitId(),i.subjectType()==PerformancePlanAssignment.SubjectType.EMPLOYEE?EMPLOYEE_ROUTE:OFFICE_ROUTE,token);List<String> ids=i.objectiveVersionIds().stream().distinct().toList();if(ids.size()!=i.objectiveVersionIds().size())throw new IllegalArgumentException("Objective versions must be unique");for(String id:ids)validateObjective(a,id,cycle,subject);return new Resolved(cycle,template,owner,membership,subject,route,ids);}
    private Subject subject(AssignmentInput i,HumanResourceAssessmentSubject owner,AdministrativePerformancePlanningClient.PersonnelMembership membership,String token){if(!Objects.equals(owner.employeeId(),membership.employeeId()))throw new IllegalArgumentException("HR and Administrative employee identities do not match");return switch(i.subjectType()){case EMPLOYEE->{if(!Objects.equals(i.subjectId(),owner.employeeId()))throw new IllegalArgumentException("Employee assignment subject must be the owner employee");var org=administrative.organization("BUSINESS_UNIT",membership.businessUnitId(),token);yield new Subject(owner.employeeNo(),owner.displayName(),membership.areaId(),membership.areaName(),membership.businessUnitId(),membership.businessUnitName(),membership.sourceFingerprint(),org);}case BUSINESS_UNIT->{if(!Objects.equals(i.subjectId(),membership.businessUnitId()))throw new IllegalArgumentException("Assignment owner must belong to the Business Unit subject");var org=administrative.organization("BUSINESS_UNIT",i.subjectId(),token);yield new Subject(org.code(),org.name(),org.areaId(),org.areaName(),org.id(),org.name(),org.sourceFingerprint(),org);}case AREA->{if(!Objects.equals(i.subjectId(),membership.areaId()))throw new IllegalArgumentException("Assignment owner must belong to the Area subject");if(i.routingBusinessUnitId()==null)throw new IllegalArgumentException("Area assignments require routingBusinessUnitId");var org=administrative.organization("AREA",i.subjectId(),token);var route=administrative.organization("BUSINESS_UNIT",i.routingBusinessUnitId(),token);if(!Objects.equals(route.areaId(),org.id()))throw new IllegalArgumentException("The routing Business Unit must belong to the Area subject");yield new Subject(org.code(),org.name(),org.id(),org.name(),route.id(),route.name(),org.sourceFingerprint(),org);}};}
    private void validateObjective(String a,String id,PerformanceCycle cycle,Subject s){PerformanceObjectiveVersion o=objectives.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance objective version not found: "+id));if(o.getStatus()!=PerformanceObjectiveVersion.Status.PUBLISHED||!contains(o.getEffectiveFrom(),o.getEffectiveTo(),cycle.getPeriodStart(),cycle.getPeriodEnd()))throw new IllegalArgumentException("Every assigned objective must be published and effective for the whole cycle");if(!o.getPolicyVersionId().equals(cycle.getPolicyVersionId()))throw new IllegalArgumentException("Objective and cycle policy versions must match");if(o.getLevel()==PerformanceObjectiveVersion.Level.AREA&&!Objects.equals(o.getOrganizationId(),s.areaId()))throw new IllegalArgumentException("Area objective is outside the assignment organization");if(o.getLevel()==PerformanceObjectiveVersion.Level.BUSINESS_UNIT&&!Objects.equals(o.getOrganizationId(),s.routingBusinessUnitId()))throw new IllegalArgumentException("Business Unit objective is outside the assignment organization");}
    private static void validateForm(PerformancePlanAssignment.SubjectType type,PerformanceTemplateVersion.FormType form){if(type==PerformancePlanAssignment.SubjectType.EMPLOYEE&&form!=PerformanceTemplateVersion.FormType.IPCR&&form!=PerformanceTemplateVersion.FormType.CUSTOM)throw new IllegalArgumentException("Employee assignments require IPCR or CUSTOM templates");if(type!=PerformancePlanAssignment.SubjectType.EMPLOYEE&&form==PerformanceTemplateVersion.FormType.IPCR)throw new IllegalArgumentException("Office assignments cannot use IPCR templates");}
    private static List<String> fingerprintErrors(PerformancePlanAssignment x,Resolved r){List<String> e=new ArrayList<>();if(!x.getOrganizationFingerprint().equals(r.subject().fingerprint()))e.add("Organization membership changed; update the draft before activation");if(!x.getParticipantFingerprint().equals(r.owner().sourceFingerprint()))e.add("Owner appointment changed; update the draft before activation");if(!x.getRouteFingerprint().equals(r.route().sourceFingerprint()))e.add("Approval route changed; update the draft before activation");return e;}
    private PerformancePlanAssignment make(String a,AssignmentInput i,Resolved r){Subject s=r.subject();HumanResourceAssessmentSubject o=r.owner();return new PerformancePlanAssignment(a,i.cycleId(),i.templateVersionId(),i.subjectType(),i.subjectId(),s.code(),s.name(),s.areaId(),s.areaName(),s.routingBusinessUnitId(),s.routingBusinessUnitName(),o.employeeId(),o.employeeNo(),o.displayName(),o.appointmentId(),o.jobPositionId(),o.plantillaId(),r.template().getFormType().name(),s.fingerprint(),o.sourceFingerprint(),r.route().sourceFingerprint());}
    private void apply(PerformancePlanAssignment x,AssignmentInput i,Resolved r){Subject s=r.subject();HumanResourceAssessmentSubject o=r.owner();x.update(i.cycleId(),i.templateVersionId(),i.subjectType(),i.subjectId(),s.code(),s.name(),s.areaId(),s.areaName(),s.routingBusinessUnitId(),s.routingBusinessUnitName(),o.employeeId(),o.employeeNo(),o.displayName(),o.appointmentId(),o.jobPositionId(),o.plantillaId(),r.template().getFormType().name(),s.fingerprint(),o.sourceFingerprint(),r.route().sourceFingerprint());}
    private void replace(String a,String id,List<String> objectiveIds){links.deleteByAgencyIdAndAssignmentId(a,id);links.flush();int n=1;for(String objectiveId:objectiveIds)links.save(new PerformancePlanAssignmentObjective(a,id,objectiveId,n++));links.flush();}
    private AssignmentResponse response(String a,PerformancePlanAssignment x){return new AssignmentResponse(x.getId(),x.getCycleId(),x.getTemplateVersionId(),x.getSubjectType().name(),x.getSubjectId(),x.getSubjectCode(),x.getSubjectName(),x.getAreaId(),x.getAreaName(),x.getRoutingBusinessUnitId(),x.getRoutingBusinessUnitName(),x.getOwnerEmployeeId(),x.getOwnerEmployeeNo(),x.getOwnerName(),x.getOwnerAppointmentId(),x.getOwnerJobPositionId(),x.getOwnerPlantillaId(),x.getFormType(),x.getOrganizationFingerprint(),x.getParticipantFingerprint(),x.getRouteFingerprint(),x.getStatus().name(),x.getVersion(),links.findByAgencyIdAndAssignmentIdOrderByDisplayOrder(a,x.getId()).stream().map(PerformancePlanAssignmentObjective::getObjectiveVersionId).toList());}
    private AssignmentResponse audited(String a,String action,PerformancePlanAssignment x,AssignmentResponse before,String c,String reason){AssignmentResponse after=response(a,x);audit.record(a,action,"SPMS_PLAN_ASSIGNMENT",x.getId(),null,x.getVersion(),before,after,reason,c);return after;}
    private PerformancePlanAssignment assignment(String a,String id){return assignments.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance plan assignment not found"));}private static boolean contains(LocalDate outerFrom,LocalDate outerTo,LocalDate innerFrom,LocalDate innerTo){return outerFrom!=null&&!innerFrom.isBefore(outerFrom)&&(outerTo==null||(innerTo!=null&&!innerTo.isAfter(outerTo)));}private static void check(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticConflictException("Expected recordVersion "+expected+" but current version is "+actual);}
    private record Subject(String code,String name,Long areaId,String areaName,Long routingBusinessUnitId,String routingBusinessUnitName,String fingerprint,AdministrativePerformancePlanningClient.OrganizationTarget organization){}private record Resolved(PerformanceCycle cycle,PerformanceTemplateVersion template,HumanResourceAssessmentSubject owner,AdministrativePerformancePlanningClient.PersonnelMembership membership,Subject subject,AdministrativePerformancePlanningClient.ApprovalRoute route,List<String> objectiveIds){}
}
