package com.primehr.performancemanagement.application;

import com.primehr.performancemanagement.api.PerformanceTemplateDtos.*;
import com.primehr.performancemanagement.domain.*;
import com.primehr.performancemanagement.infrastructure.*;
import com.primehr.shared.audit.PrimeHrAuditService;
import com.primehr.shared.exception.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.*;
import java.util.*;

@Service @Transactional
public class PerformanceTemplateServiceImpl implements PerformanceTemplateService {
    private static final BigDecimal HUNDRED=new BigDecimal("100");
    private final PerformanceTemplateRepository roots; private final PerformanceTemplateVersionRepository versions;
    private final PerformanceTemplateSectionRepository sections; private final PerformanceTemplateItemRepository items;
    private final PerformancePolicyVersionRepository policies; private final PerformanceRatingScaleVersionRepository scales;
    private final PerformanceRatingBandRepository bands; private final PerformanceSuccessIndicatorVersionRepository indicators;
    private final PrimeHrAuditService audit;
    public PerformanceTemplateServiceImpl(PerformanceTemplateRepository r,PerformanceTemplateVersionRepository v,
            PerformanceTemplateSectionRepository s,PerformanceTemplateItemRepository i,PerformancePolicyVersionRepository p,
            PerformanceRatingScaleVersionRepository rs,PerformanceRatingBandRepository b,
            PerformanceSuccessIndicatorVersionRepository si,PrimeHrAuditService a){roots=r;versions=v;sections=s;items=i;policies=p;scales=rs;bands=b;indicators=si;audit=a;}
    @Override @Transactional(readOnly=true) public List<TemplateResponse> list(String a){return versions.findByAgencyIdOrderByCreatedAtDesc(a).stream().map(v->response(a,v)).toList();}
    @Override @Transactional(readOnly=true) public TemplateResponse get(String a,String id){return response(a,version(a,id));}
    @Override public TemplateResponse create(String a,TemplateInput i,String c){if(i.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");bindings(a,i.policyVersionId(),i.ratingScaleVersionId(),false);String code=i.code().trim().toUpperCase(Locale.ROOT);if(roots.existsByAgencyIdAndNormalizedCode(a,code))throw new IllegalArgumentException("Template code already exists");PerformanceTemplate root=roots.saveAndFlush(new PerformanceTemplate(a,i.code()));PerformanceTemplateVersion v=versions.saveAndFlush(make(a,root.getId(),1,null,i));return audited(a,"CREATE_PERFORMANCE_TEMPLATE_DRAFT",v,null,c,null);}
    @Override public TemplateResponse update(String a,String id,TemplateInput i,String c){PerformanceTemplateVersion v=version(a,id);check(v.getVersion(),i.recordVersion());if(!root(a,v.getTemplateId()).getCode().equalsIgnoreCase(i.code()))throw new IllegalArgumentException("Template code is stable");bindings(a,i.policyVersionId(),i.ratingScaleVersionId(),false);TemplateResponse before=response(a,v);v.update(i.policyVersionId(),i.ratingScaleVersionId(),i.title(),i.description(),i.formType(),i.formLabel(),i.legalBasis());return audited(a,"UPDATE_PERFORMANCE_TEMPLATE_DRAFT",versions.saveAndFlush(v),before,c,null);}
    @Override public TemplateResponse structure(String a,String id,StructureInput i,String c){PerformanceTemplateVersion v=version(a,id);check(v.getVersion(),i.recordVersion());List<String> errors=validate(a,v,i.sections(),null,null);if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));TemplateResponse before=response(a,v);for(PerformanceTemplateSection s:sectionRows(a,id))items.deleteByAgencyIdAndSectionId(a,s.getId());sections.deleteByAgencyIdAndTemplateVersionId(a,id);sections.flush();for(SectionInput in:i.sections().stream().sorted(Comparator.comparingInt(SectionInput::displayOrder)).toList()){PerformanceTemplateSection s=sections.saveAndFlush(new PerformanceTemplateSection(a,id,in.type(),in.code(),in.title(),in.description(),in.weightPercent(),in.displayOrder()));items.saveAll(in.items().stream().map(x->new PerformanceTemplateItem(a,s.getId(),x.indicatorVersionId(),x.labelOverride(),x.weightPercent(),x.required(),x.evidenceOverride(),x.displayOrder())).toList());}v.structureChanged();return audited(a,"REPLACE_PERFORMANCE_TEMPLATE_STRUCTURE",versions.saveAndFlush(v),before,c,null);}
    @Override public TemplateResponse revision(String a,String id,Transition i,String c){PerformanceTemplateVersion old=version(a,id);check(old.getVersion(),i.recordVersion());if(old.getStatus()!=PerformanceTemplateVersion.Status.PUBLISHED)throw new IllegalArgumentException("Only a published template can have a revision");int n=versions.findByAgencyIdAndTemplateIdOrderByDefinitionVersionDesc(a,old.getTemplateId()).stream().mapToInt(PerformanceTemplateVersion::getDefinitionVersion).max().orElse(0)+1;PerformanceTemplateVersion v=versions.saveAndFlush(new PerformanceTemplateVersion(a,old.getTemplateId(),old.getPolicyVersionId(),old.getRatingScaleVersionId(),n,old.getId(),old.getTitle(),old.getDescription(),old.getFormType(),old.getFormLabel(),old.getLegalBasis()));copy(a,old.getId(),v.getId());v.structureChanged();return audited(a,"CREATE_PERFORMANCE_TEMPLATE_REVISION",versions.saveAndFlush(v),null,c,i.reason());}
    @Override public TemplateResponse publish(String a,String id,Transition i,String c){PerformanceTemplateVersion v=version(a,id);check(v.getVersion(),i.recordVersion());Binding binding=bindings(a,v.getPolicyVersionId(),v.getRatingScaleVersionId(),true);validateEffectiveInterval(i.effectiveFrom(),i.effectiveTo(),binding.policy(),binding.scale());List<String> errors=validate(a,v,currentStructure(a,id),i.effectiveFrom(),i.effectiveTo());if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));TemplateResponse before=response(a,v);Instant now=Instant.now();String actor=audit.currentActor();if(v.getSupersedesId()!=null){PerformanceTemplateVersion prior=version(a,v.getSupersedesId());prior.supersede(i.effectiveFrom(),actor,now);versions.saveAndFlush(prior);}v.publish(i.effectiveFrom(),i.effectiveTo(),actor,now);return audited(a,"PUBLISH_PERFORMANCE_TEMPLATE",versions.saveAndFlush(v),before,c,i.reason());}
    @Override public TemplateResponse retire(String a,String id,Transition i,String c){PerformanceTemplateVersion v=version(a,id);check(v.getVersion(),i.recordVersion());TemplateResponse before=response(a,v);v.retire(audit.currentActor(),i.reason(),Instant.now());return audited(a,"RETIRE_PERFORMANCE_TEMPLATE",versions.saveAndFlush(v),before,c,i.reason());}
    @Override @Transactional(readOnly=true) public ReadinessResponse readiness(String a,String id){PerformanceTemplateVersion v=version(a,id);List<String> errors=validate(a,v,currentStructure(a,id),v.getEffectiveFrom(),v.getEffectiveTo());return new ReadinessResponse(errors.isEmpty(),errors);}
    @Override @Transactional(readOnly=true) public PreviewResponse preview(String a,String id,PreviewInput i){PerformanceTemplateVersion v=version(a,id);List<String> errors=validate(a,v,currentStructure(a,id),v.getEffectiveFrom(),v.getEffectiveTo());if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));Map<String,BigDecimal> scores=new HashMap<>();for(ItemScore s:i.scores())if(scores.put(s.itemId(),s.indicatorScore())!=null)throw new IllegalArgumentException("Item scores must be unique");BigDecimal overall=BigDecimal.ZERO;List<SectionScore> results=new ArrayList<>();for(PerformanceTemplateSection section:sectionRows(a,id)){BigDecimal sectionScore=BigDecimal.ZERO;for(PerformanceTemplateItem item:itemRows(a,section.getId())){BigDecimal score=Optional.ofNullable(scores.get(item.getId())).orElseThrow(()->new IllegalArgumentException("Missing item score under ERROR policy: "+item.getId()));sectionScore=sectionScore.add(score.multiply(item.getWeightPercent()).divide(HUNDRED,8,RoundingMode.HALF_UP));}BigDecimal contribution=sectionScore.multiply(section.getWeightPercent()).divide(HUNDRED,8,RoundingMode.HALF_UP);overall=overall.add(contribution);results.add(new SectionScore(section.getId(),sectionScore,contribution));}PerformanceRatingScaleVersion scale=scale(a,v.getRatingScaleVersionId());BigDecimal rounded=overall.setScale(scale.getRoundingScale(),scale.getRoundingMode());PerformanceRatingBand band=bands.findByAgencyIdAndRatingScaleVersionIdOrderByDisplayOrder(a,scale.getId()).stream().filter(b->rounded.compareTo(b.getLowerBound())>=0&&rounded.compareTo(b.getUpperBound())<=0).findFirst().orElseThrow(()->new IllegalArgumentException("Overall score is outside the template rating scale"));return new PreviewResponse(rounded,band.getId(),band.getLabel(),results,"sum(section(sum(indicatorScore * itemWeight / 100)) * sectionWeight / 100)");}
    private List<SectionInput> currentStructure(String a,String id){return sectionRows(a,id).stream().map(s->new SectionInput(s.getType(),s.getCode(),s.getTitle(),s.getDescription(),s.getWeightPercent(),s.getDisplayOrder(),itemRows(a,s.getId()).stream().map(x->new ItemInput(x.getIndicatorVersionId(),x.getLabelOverride(),x.getWeightPercent(),x.isRequired(),x.getEvidenceOverride(),x.getDisplayOrder())).toList())).toList();}
    private List<String> validate(String a,PerformanceTemplateVersion v,List<SectionInput> rows,LocalDate effectiveFrom,LocalDate effectiveTo){List<String> e=new ArrayList<>();if(rows==null||rows.isEmpty()){e.add("At least one section is required");return e;}if(rows.stream().map(SectionInput::weightPercent).reduce(BigDecimal.ZERO,BigDecimal::add).compareTo(HUNDRED)!=0)e.add("Section weights must total 100");Set<String> codes=new HashSet<>();Set<Integer> orders=new HashSet<>();for(SectionInput s:rows){String code=normalize(s.code());if(!codes.add(code)||!orders.add(s.displayOrder()))e.add("Section codes and display orders must be unique");if(s.items()==null||s.items().isEmpty()){e.add("Every section requires at least one item");continue;}if(s.items().stream().map(ItemInput::weightPercent).reduce(BigDecimal.ZERO,BigDecimal::add).compareTo(HUNDRED)!=0)e.add("Item weights must total 100 in every section");Set<String> ids=new HashSet<>();Set<Integer> itemOrders=new HashSet<>();for(ItemInput x:s.items()){if(!ids.add(x.indicatorVersionId())||!itemOrders.add(x.displayOrder()))e.add("Section indicator versions and item orders must be unique");PerformanceSuccessIndicatorVersion indicator=indicators.findByIdAndAgencyId(x.indicatorVersionId(),a).orElse(null);if(indicator==null||indicator.getStatus()!=PerformanceSuccessIndicatorVersion.Status.PUBLISHED)e.add("Template items must reference published success-indicator versions");else{if(!indicator.getPolicyVersionId().equals(v.getPolicyVersionId())||!indicator.getRatingScaleVersionId().equals(v.getRatingScaleVersionId()))e.add("Template item policy and rating scale versions must match the template exactly");if(effectiveFrom!=null&&!contains(indicator.getEffectiveFrom(),indicator.getEffectiveTo(),effectiveFrom,effectiveTo))e.add("Template effectivity must be contained by every success-indicator version");if(indicator.isRequiresEvidence()&&x.evidenceOverride()!=null&&x.evidenceOverride().isBlank())e.add("An evidence override cannot weaken an indicator evidence requirement");}}}return e;}
    private void copy(String a,String from,String to){for(PerformanceTemplateSection s:sectionRows(a,from)){PerformanceTemplateSection d=sections.saveAndFlush(new PerformanceTemplateSection(a,to,s.getType(),s.getCode(),s.getTitle(),s.getDescription(),s.getWeightPercent(),s.getDisplayOrder()));items.saveAll(itemRows(a,s.getId()).stream().map(x->new PerformanceTemplateItem(a,d.getId(),x.getIndicatorVersionId(),x.getLabelOverride(),x.getWeightPercent(),x.isRequired(),x.getEvidenceOverride(),x.getDisplayOrder())).toList());}}
    private TemplateResponse audited(String a,String action,PerformanceTemplateVersion v,TemplateResponse before,String c,String reason){TemplateResponse after=response(a,v);audit.record(a,action,"SPMS_TEMPLATE_VERSION",v.getId(),v.getDefinitionVersion(),v.getVersion(),before,after,reason,c);return after;}
    private TemplateResponse response(String a,PerformanceTemplateVersion v){List<SectionResponse> s=sectionRows(a,v.getId()).stream().map(x->new SectionResponse(x.getId(),x.getType().name(),x.getCode(),x.getTitle(),x.getDescription(),x.getWeightPercent(),x.getDisplayOrder(),itemRows(a,x.getId()).stream().map(i->new ItemResponse(i.getId(),i.getIndicatorVersionId(),i.getLabelOverride(),i.getWeightPercent(),i.isRequired(),i.getEvidenceOverride(),i.getDisplayOrder())).toList())).toList();return new TemplateResponse(v.getId(),v.getTemplateId(),root(a,v.getTemplateId()).getCode(),v.getTitle(),v.getDescription(),v.getFormType().name(),v.getFormLabel(),v.getLegalBasis(),v.getPolicyVersionId(),v.getRatingScaleVersionId(),v.getCoverageScope(),v.getAggregation(),v.getMissingValuePolicy(),v.getDefinitionVersion(),v.getSupersedesId(),v.getStatus().name(),v.getEffectiveFrom(),v.getEffectiveTo(),v.getVersion(),s);}
    private PerformanceTemplateVersion make(String a,String root,int n,String prior,TemplateInput i){return new PerformanceTemplateVersion(a,root,i.policyVersionId(),i.ratingScaleVersionId(),n,prior,i.title(),i.description(),i.formType(),i.formLabel(),i.legalBasis());}
    private Binding bindings(String a,String p,String s,boolean pub){PerformancePolicyVersion policy=policies.findByIdAndAgencyId(p,a).orElseThrow(()->new ResourceNotFoundException("Performance policy version not found"));PerformanceRatingScaleVersion scale=scale(a,s);if(!scale.getPolicyVersionId().equals(policy.getId()))throw new IllegalArgumentException("Template policy and rating scale must match exactly");if(pub&&(policy.getStatus()!=PerformancePolicyVersion.Status.PUBLISHED||scale.getStatus()!=PerformanceRatingScaleVersion.Status.PUBLISHED))throw new IllegalArgumentException("Published policy and rating scale versions are required");return new Binding(policy,scale);}
    private void validateEffectiveInterval(LocalDate from,LocalDate to,PerformancePolicyVersion policy,PerformanceRatingScaleVersion scale){if(from==null)throw new IllegalArgumentException("effectiveFrom is required");if(to!=null&&to.isBefore(from))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");if(!contains(policy.getEffectiveFrom(),policy.getEffectiveTo(),from,to)||!contains(scale.getEffectiveFrom(),scale.getEffectiveTo(),from,to))throw new IllegalArgumentException("Template effectivity must be contained by its exact policy and rating-scale versions");}
    private static boolean contains(LocalDate outerFrom,LocalDate outerTo,LocalDate innerFrom,LocalDate innerTo){return outerFrom!=null&&!innerFrom.isBefore(outerFrom)&&(outerTo==null||(innerTo!=null&&!innerTo.isAfter(outerTo)));}
    private record Binding(PerformancePolicyVersion policy,PerformanceRatingScaleVersion scale){}
    private List<PerformanceTemplateSection> sectionRows(String a,String v){return sections.findByAgencyIdAndTemplateVersionIdOrderByDisplayOrder(a,v);} private List<PerformanceTemplateItem> itemRows(String a,String s){return items.findByAgencyIdAndSectionIdOrderByDisplayOrder(a,s);} private PerformanceTemplateVersion version(String a,String id){return versions.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Template version not found"));} private PerformanceTemplate root(String a,String id){return roots.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Template not found"));} private PerformanceRatingScaleVersion scale(String a,String id){return scales.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Rating scale version not found"));}
    private static String normalize(String value){return value==null?null:value.trim().toUpperCase(Locale.ROOT);} private static void check(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticConflictException("Expected recordVersion "+expected+" but current version is "+actual);}
}
