package com.primehr.performancemanagement.application;

import com.primehr.integration.administrative.AdministrativePerformancePlanningClient;
import com.primehr.performancemanagement.api.PerformanceObjectiveDtos.*;
import com.primehr.performancemanagement.domain.*;
import com.primehr.performancemanagement.infrastructure.*;
import com.primehr.shared.audit.PrimeHrAuditService;
import com.primehr.shared.exception.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;

@Service @Transactional
public class PerformanceObjectiveServiceImpl implements PerformanceObjectiveService {
    private final PerformanceObjectiveRepository roots; private final PerformanceObjectiveVersionRepository versions;
    private final PerformancePolicyVersionRepository policies; private final PerformanceSuccessIndicatorVersionRepository indicators;
    private final AdministrativePerformancePlanningClient administrative; private final PrimeHrAuditService audit;
    public PerformanceObjectiveServiceImpl(PerformanceObjectiveRepository r,PerformanceObjectiveVersionRepository v,
            PerformancePolicyVersionRepository p,PerformanceSuccessIndicatorVersionRepository i,
            AdministrativePerformancePlanningClient a,PrimeHrAuditService au){roots=r;versions=v;policies=p;indicators=i;administrative=a;audit=au;}
    @Override @Transactional(readOnly=true) public List<ObjectiveResponse> list(String a){return versions.findByAgencyIdOrderByCreatedAtDesc(a).stream().map(v->response(a,v)).toList();}
    @Override @Transactional(readOnly=true) public ObjectiveResponse get(String a,String id){return response(a,version(a,id));}
    @Override public ObjectiveResponse create(String a,ObjectiveInput i,String token,String c){if(i.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");var org=organization(i.level(),i.organizationId(),token);validateBindings(a,i,org==null?null:org.areaId());String code=i.code().trim().toUpperCase(Locale.ROOT);if(roots.existsByAgencyIdAndNormalizedCode(a,code))throw new IllegalArgumentException("Objective code already exists");PerformanceObjective root=roots.saveAndFlush(new PerformanceObjective(a,i.code()));PerformanceObjectiveVersion v=versions.saveAndFlush(make(a,root.getId(),1,null,i,org));return audited(a,"CREATE_PERFORMANCE_OBJECTIVE_DRAFT",v,null,c,null);}
    @Override public ObjectiveResponse update(String a,String id,ObjectiveInput i,String token,String c){PerformanceObjectiveVersion v=version(a,id);check(v.getVersion(),i.recordVersion());if(!root(a,v.getObjectiveId()).getCode().equalsIgnoreCase(i.code()))throw new IllegalArgumentException("Objective code is stable");var org=organization(i.level(),i.organizationId(),token);validateBindings(a,i,org==null?null:org.areaId());ObjectiveResponse before=response(a,v);apply(v,i,org);return audited(a,"UPDATE_PERFORMANCE_OBJECTIVE_DRAFT",versions.saveAndFlush(v),before,c,null);}
    @Override public ObjectiveResponse revision(String a,String id,Transition i,String token,String c){PerformanceObjectiveVersion old=version(a,id);check(old.getVersion(),i.recordVersion());if(old.getStatus()!=PerformanceObjectiveVersion.Status.PUBLISHED)throw new IllegalArgumentException("Only a published objective can have a revision");var org=refresh(old,token);int n=versions.findByAgencyIdAndObjectiveIdOrderByDefinitionVersionDesc(a,old.getObjectiveId()).stream().mapToInt(PerformanceObjectiveVersion::getDefinitionVersion).max().orElse(0)+1;PerformanceObjectiveVersion v=versions.saveAndFlush(new PerformanceObjectiveVersion(a,old.getObjectiveId(),n,old.getId(),old.getTitle(),old.getObjectiveStatement(),old.getExpectedOutcome(),old.getStrategyReference(),old.getLevel(),old.getOrganizationId(),org==null?null:org.code(),org==null?null:org.name(),org==null?null:org.areaId(),old.getParentObjectiveVersionId(),old.getPolicyVersionId(),old.getIndicatorVersionId(),old.getTargetValue(),old.getTargetFrom(),old.getTargetTo(),old.getUnitOfMeasure(),org==null?null:org.sourceFingerprint()));return audited(a,"CREATE_PERFORMANCE_OBJECTIVE_REVISION",v,null,c,i.reason());}
    @Override public ObjectiveResponse publish(String a,String id,Transition i,String token,String c){PerformanceObjectiveVersion v=version(a,id);check(v.getVersion(),i.recordVersion());var org=refresh(v,token);List<String> errors=errors(a,v,i.effectiveFrom(),i.effectiveTo(),org);if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));ObjectiveResponse before=response(a,v);Instant now=Instant.now();String actor=audit.currentActor();if(v.getSupersedesId()!=null){PerformanceObjectiveVersion prior=version(a,v.getSupersedesId());prior.supersede(i.effectiveFrom(),actor,now);versions.saveAndFlush(prior);}v.publish(i.effectiveFrom(),i.effectiveTo(),actor,now);return audited(a,"PUBLISH_PERFORMANCE_OBJECTIVE",versions.saveAndFlush(v),before,c,i.reason());}
    @Override public ObjectiveResponse retire(String a,String id,Transition i,String c){PerformanceObjectiveVersion v=version(a,id);check(v.getVersion(),i.recordVersion());ObjectiveResponse before=response(a,v);v.retire(audit.currentActor(),i.reason(),Instant.now());return audited(a,"RETIRE_PERFORMANCE_OBJECTIVE",versions.saveAndFlush(v),before,c,i.reason());}
    @Override @Transactional(readOnly=true) public ReadinessResponse readiness(String a,String id,String token){PerformanceObjectiveVersion v=version(a,id);var org=refresh(v,token);List<String> errors=errors(a,v,v.getEffectiveFrom(),v.getEffectiveTo(),org);return new ReadinessResponse(errors.isEmpty(),errors);}
    private List<String> errors(String a,PerformanceObjectiveVersion v,LocalDate from,LocalDate to,AdministrativePerformancePlanningClient.OrganizationTarget org){List<String> e=new ArrayList<>();if(from==null)e.add("effectiveFrom is required");if(from!=null&&to!=null&&to.isBefore(from))e.add("effectiveTo cannot precede effectiveFrom");PerformancePolicyVersion p=policies.findByIdAndAgencyId(v.getPolicyVersionId(),a).orElse(null);if(p==null||p.getStatus()!=PerformancePolicyVersion.Status.PUBLISHED)e.add("A published policy version is required");else if(from!=null&&!contains(p.getEffectiveFrom(),p.getEffectiveTo(),from,to))e.add("Objective effectivity must be contained by the policy version");if(v.getIndicatorVersionId()!=null){PerformanceSuccessIndicatorVersion x=indicators.findByIdAndAgencyId(v.getIndicatorVersionId(),a).orElse(null);if(x==null||x.getStatus()!=PerformanceSuccessIndicatorVersion.Status.PUBLISHED)e.add("A published success-indicator version is required");else{if(!x.getPolicyVersionId().equals(v.getPolicyVersionId()))e.add("Objective policy and success indicator policy must match");if(from!=null&&!contains(x.getEffectiveFrom(),x.getEffectiveTo(),from,to))e.add("Objective effectivity must be contained by the success indicator");}}if(org!=null&&!org.sourceFingerprint().equals(v.getSourceFingerprint()))e.add("Organization source changed; refresh the draft before publication");validateParent(a,v.getLevel(),v.getParentAreaId(),v.getParentObjectiveVersionId(),from,to,e);return e;}
    private void validateBindings(String a,ObjectiveInput i,Long parentAreaId){if(policies.findByIdAndAgencyId(i.policyVersionId(),a).isEmpty())throw new ResourceNotFoundException("Performance policy version not found");if(i.indicatorVersionId()!=null&&indicators.findByIdAndAgencyId(i.indicatorVersionId(),a).isEmpty())throw new ResourceNotFoundException("Success-indicator version not found");List<String> e=new ArrayList<>();validateParent(a,i.level(),parentAreaId,i.parentObjectiveVersionId(),null,null,e);if(!e.isEmpty())throw new IllegalArgumentException(String.join("; ",e));}
    private void validateParent(String a,PerformanceObjectiveVersion.Level level,Long parentAreaId,String parentId,LocalDate from,LocalDate to,List<String> e){if(level==PerformanceObjectiveVersion.Level.AGENCY){if(parentId!=null)e.add("Agency objectives cannot have a parent");return;}if(parentId==null){e.add("Area and Business Unit objectives require a parent objective");return;}PerformanceObjectiveVersion p=versions.findByIdAndAgencyId(parentId,a).orElse(null);if(p==null){e.add("Parent objective version not found");return;}if(p.getStatus()!=PerformanceObjectiveVersion.Status.PUBLISHED)e.add("Parent objective must be published");if(level==PerformanceObjectiveVersion.Level.AREA&&p.getLevel()!=PerformanceObjectiveVersion.Level.AGENCY)e.add("Area objectives must descend from an agency objective");if(level==PerformanceObjectiveVersion.Level.BUSINESS_UNIT&&!(p.getLevel()==PerformanceObjectiveVersion.Level.AGENCY||p.getLevel()==PerformanceObjectiveVersion.Level.AREA))e.add("Business Unit objectives must descend from an agency or area objective");if(level==PerformanceObjectiveVersion.Level.BUSINESS_UNIT&&p.getLevel()==PerformanceObjectiveVersion.Level.AREA&&!Objects.equals(p.getOrganizationId(),parentAreaId))e.add("Business Unit objective and Area parent must share the same authoritative Area");if(from!=null&&!contains(p.getEffectiveFrom(),p.getEffectiveTo(),from,to))e.add("Objective effectivity must be contained by its parent objective");}
    private AdministrativePerformancePlanningClient.OrganizationTarget organization(PerformanceObjectiveVersion.Level level,Long id,String token){if(level==PerformanceObjectiveVersion.Level.AGENCY){if(id!=null)throw new IllegalArgumentException("Agency objectives cannot reference organizationId");return null;}if(id==null)throw new IllegalArgumentException("organizationId is required");return administrative.organization(level.name(),id,token);}
    private AdministrativePerformancePlanningClient.OrganizationTarget refresh(PerformanceObjectiveVersion v,String token){return organization(v.getLevel(),v.getOrganizationId(),token);}
    private PerformanceObjectiveVersion make(String a,String root,int n,String prior,ObjectiveInput i,AdministrativePerformancePlanningClient.OrganizationTarget o){return new PerformanceObjectiveVersion(a,root,n,prior,i.title(),i.objectiveStatement(),i.expectedOutcome(),i.strategyReference(),i.level(),i.organizationId(),o==null?null:o.code(),o==null?null:o.name(),o==null?null:o.areaId(),i.parentObjectiveVersionId(),i.policyVersionId(),i.indicatorVersionId(),i.targetValue(),i.targetFrom(),i.targetTo(),i.unitOfMeasure(),o==null?null:o.sourceFingerprint());}
    private void apply(PerformanceObjectiveVersion v,ObjectiveInput i,AdministrativePerformancePlanningClient.OrganizationTarget o){v.update(i.title(),i.objectiveStatement(),i.expectedOutcome(),i.strategyReference(),i.level(),i.organizationId(),o==null?null:o.code(),o==null?null:o.name(),o==null?null:o.areaId(),i.parentObjectiveVersionId(),i.policyVersionId(),i.indicatorVersionId(),i.targetValue(),i.targetFrom(),i.targetTo(),i.unitOfMeasure(),o==null?null:o.sourceFingerprint());}
    private ObjectiveResponse response(String a,PerformanceObjectiveVersion v){return new ObjectiveResponse(v.getId(),v.getObjectiveId(),root(a,v.getObjectiveId()).getCode(),v.getDefinitionVersion(),v.getSupersedesId(),v.getTitle(),v.getObjectiveStatement(),v.getExpectedOutcome(),v.getStrategyReference(),v.getLevel().name(),v.getOrganizationId(),v.getOrganizationCode(),v.getOrganizationName(),v.getParentAreaId(),v.getParentObjectiveVersionId(),v.getPolicyVersionId(),v.getIndicatorVersionId(),v.getTargetValue(),v.getTargetFrom(),v.getTargetTo(),v.getUnitOfMeasure(),v.getSourceFingerprint(),v.getStatus().name(),v.getEffectiveFrom(),v.getEffectiveTo(),v.getVersion());}
    private ObjectiveResponse audited(String a,String action,PerformanceObjectiveVersion v,ObjectiveResponse before,String c,String reason){ObjectiveResponse after=response(a,v);audit.record(a,action,"SPMS_OBJECTIVE_VERSION",v.getId(),v.getDefinitionVersion(),v.getVersion(),before,after,reason,c);return after;}
    private PerformanceObjectiveVersion version(String a,String id){return versions.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance objective version not found"));}private PerformanceObjective root(String a,String id){return roots.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance objective not found"));}
    private static boolean contains(LocalDate outerFrom,LocalDate outerTo,LocalDate innerFrom,LocalDate innerTo){return outerFrom!=null&&!innerFrom.isBefore(outerFrom)&&(outerTo==null||(innerTo!=null&&!innerTo.isAfter(outerTo)));}private static void check(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticConflictException("Expected recordVersion "+expected+" but current version is "+actual);}
}
