package com.primehr.performancemanagement.application;
import com.primehr.performancemanagement.api.PerformanceManagementTeamDtos.*;import com.primehr.performancemanagement.application.PmtMemberEligibilityService.EligibleMember;import com.primehr.performancemanagement.domain.*;import com.primehr.performancemanagement.infrastructure.*;import com.primehr.shared.api.PageResponse;import com.primehr.shared.audit.PrimeHrAuditService;import com.primehr.shared.exception.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.stream.*;
@Service @Transactional public class PerformanceManagementTeamServiceImpl implements PerformanceManagementTeamService{
 private final PerformanceManagementTeamRepository teams;private final PerformanceManagementTeamMemberRepository members;private final PmtMemberEligibilityService eligibility;private final PrimeHrAuditService audit;
 public PerformanceManagementTeamServiceImpl(PerformanceManagementTeamRepository t,PerformanceManagementTeamMemberRepository m,PmtMemberEligibilityService e,PrimeHrAuditService a){teams=t;members=m;eligibility=e;audit=a;}
 @Override@Transactional(readOnly=true)public PageResponse<TeamResponse>list(String agency,int page,int size){if(page<0||size<1||size>100)throw new IllegalArgumentException("Invalid pagination");return PageResponse.from(teams.findByAgencyId(agency,PageRequest.of(page,size,Sort.by("effectiveFrom").descending())),t->response(agency,t));}
 @Override@Transactional(readOnly=true)public TeamResponse get(String agency,String id){return response(agency,team(agency,id));}
 @Override public TeamResponse create(String agency,SaveTeam r,String token,String correlation){if(r.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");String code=r.code().trim().toUpperCase(Locale.ROOT);if(teams.existsByAgencyIdAndNormalizedCode(agency,code))throw new IllegalArgumentException("PMT code already exists");validatePeriods(r.effectiveFrom(),r.effectiveTo(),r.members());List<EligibleMember> eligible=eligibility.validate(r.members(),token);PerformanceManagementTeam team=teams.saveAndFlush(new PerformanceManagementTeam(agency,r.code(),r.name(),r.mandateReference(),r.effectiveFrom(),r.effectiveTo()));replace(agency,team,r.members(),eligible);team.rosterChanged();team=teams.saveAndFlush(team);TeamResponse after=response(agency,team);audit.record(agency,"CREATE_PMT_DRAFT","SPMS_PMT",team.getId(),null,team.getVersion(),null,after,null,correlation);return after;}
 @Override public TeamResponse update(String agency,String id,SaveTeam r,String token,String correlation){PerformanceManagementTeam team=team(agency,id);PerformancePolicyServiceImpl.requireVersion(team.getVersion(),r.recordVersion());validatePeriods(r.effectiveFrom(),r.effectiveTo(),r.members());List<EligibleMember> eligible=eligibility.validate(r.members(),token);TeamResponse before=response(agency,team);team.update(r.code(),r.name(),r.mandateReference(),r.effectiveFrom(),r.effectiveTo());replace(agency,team,r.members(),eligible);team.rosterChanged();team=teams.saveAndFlush(team);TeamResponse after=response(agency,team);audit.record(agency,"UPDATE_PMT_DRAFT","SPMS_PMT",id,null,team.getVersion(),before,after,null,correlation);return after;}
 @Override public TeamResponse members(String agency,String id,MembersInput r,String token,String correlation){PerformanceManagementTeam team=team(agency,id);PerformancePolicyServiceImpl.requireVersion(team.getVersion(),r.recordVersion());team.requireDraft();validatePeriods(team.getEffectiveFrom(),team.getEffectiveTo(),r.members());List<EligibleMember> eligible=eligibility.validate(r.members(),token);TeamResponse before=response(agency,team);replace(agency,team,r.members(),eligible);team.rosterChanged();team=teams.saveAndFlush(team);TeamResponse after=response(agency,team);audit.record(agency,"REPLACE_PMT_MEMBERS","SPMS_PMT",id,null,team.getVersion(),before,after,null,correlation);return after;}
 @Override public TeamResponse activate(String agency,String id,Transition r,String token,String correlation){PerformanceManagementTeam team=team(agency,id);PerformancePolicyServiceImpl.requireVersion(team.getVersion(),r.recordVersion());List<PerformanceManagementTeamMember> roster=members.findByAgencyIdAndPmtIdOrderByEffectiveFromAscRoleAscEmployeeNoAsc(agency,id);LocalDate activationDate=team.getEffectiveFrom();List<PerformanceManagementTeamMember> active=roster.stream().filter(m->m.effectiveOn(activationDate)).toList();if(active.stream().filter(m->m.getRole()==PerformanceManagementTeamMember.Role.CHAIRPERSON).count()!=1)throw new IllegalArgumentException("Exactly one effective CHAIRPERSON is required");eligibility.validate(roster.stream().map(m->new MemberInput(m.getEmployeeNo(),m.getRole(),m.isVoting(),m.getEffectiveFrom(),m.getEffectiveTo(),m.getDesignationReference(),m.getRemarks())).toList(),token);TeamResponse before=response(agency,team);team.activate(audit.currentActor(),r.reason(),Instant.now());team=teams.saveAndFlush(team);TeamResponse after=response(agency,team);audit.record(agency,"ACTIVATE_PMT","SPMS_PMT",id,null,team.getVersion(),before,after,r.reason(),correlation);return after;}
 @Override public TeamResponse deactivate(String agency,String id,Transition r,String correlation){PerformanceManagementTeam team=team(agency,id);PerformancePolicyServiceImpl.requireVersion(team.getVersion(),r.recordVersion());TeamResponse before=response(agency,team);team.deactivate(audit.currentActor(),r.reason(),Instant.now());team=teams.saveAndFlush(team);TeamResponse after=response(agency,team);audit.record(agency,"DEACTIVATE_PMT","SPMS_PMT",id,null,team.getVersion(),before,after,r.reason(),correlation);return after;}
 private void replace(String agency,PerformanceManagementTeam team,List<MemberInput> inputs,List<EligibleMember> eligible){Map<String,EligibleMember> byNo=eligible.stream().collect(Collectors.toMap(v->v.employeeNo().toUpperCase(Locale.ROOT),v->v,(a,b)->a));members.deleteByAgencyIdAndPmtId(agency,team.getId());members.saveAll(inputs.stream().map(i->{EligibleMember e=byNo.get(i.employeeNo().trim().toUpperCase(Locale.ROOT));return new PerformanceManagementTeamMember(agency,team.getId(),e.employeeId(),e.employeeNo(),e.displayName(),e.jobPositionId(),e.plantillaId(),i.role(),i.voting(),i.effectiveFrom(),i.effectiveTo(),i.designationReference(),i.remarks());}).toList());members.flush();}
 static void validatePeriods(LocalDate teamFrom,LocalDate teamTo,List<MemberInput> values){for(MemberInput value:values){if(value.effectiveFrom().isBefore(teamFrom)||teamTo!=null&&(value.effectiveTo()==null||value.effectiveTo().isAfter(teamTo)))throw new IllegalArgumentException("Member effectivity must be within PMT effectivity");}for(int i=0;i<values.size();i++)for(int j=i+1;j<values.size();j++){MemberInput a=values.get(i),b=values.get(j);if(a.employeeNo().equalsIgnoreCase(b.employeeNo())&&overlap(a.effectiveFrom(),a.effectiveTo(),b.effectiveFrom(),b.effectiveTo()))throw new IllegalArgumentException("Employee PMT membership periods cannot overlap");}}
 private static boolean overlap(LocalDate af,LocalDate at,LocalDate bf,LocalDate bt){LocalDate ae=at==null?LocalDate.MAX:at,be=bt==null?LocalDate.MAX:bt;return !af.isAfter(be)&&!bf.isAfter(ae);}
 private PerformanceManagementTeam team(String a,String id){return teams.findByIdAndAgencyId(id,a).orElseThrow(()->new ResourceNotFoundException("Performance Management Team not found"));}
 private TeamResponse response(String agency,PerformanceManagementTeam t){return new TeamResponse(t.getId(),t.getCode(),t.getName(),t.getMandateReference(),t.getEffectiveFrom(),t.getEffectiveTo(),t.getStatus().name(),t.getRosterRevision(),t.getTransitionReason(),t.getVersion(),members.findByAgencyIdAndPmtIdOrderByEffectiveFromAscRoleAscEmployeeNoAsc(agency,t.getId()).stream().map(m->new MemberResponse(m.getId(),m.getEmployeeId(),m.getEmployeeNo(),m.getEmployeeNameSnapshot(),m.getJobPositionIdSnapshot(),m.getPlantillaIdSnapshot(),m.getRole().name(),m.isVoting(),m.getEffectiveFrom(),m.getEffectiveTo(),m.getDesignationReference(),m.getRemarks())).toList());}
}
