package com.primehr.rsp.screening.application;

import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper;
import com.primehr.rsp.domain.*; import com.primehr.rsp.infrastructure.VacancyPublicationRepository;
import com.primehr.rsp.screening.api.ScreeningPolicyDtos.*; import com.primehr.rsp.screening.domain.*; import com.primehr.rsp.screening.infrastructure.*;
import com.primehr.shared.api.PageResponse; import com.primehr.shared.audit.PrimeHrAuditService; import com.primehr.shared.exception.*;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors;

@Service @Transactional
public class ScreeningPolicyServiceImpl implements ScreeningPolicyService {
 private final ScreeningPolicyRepository policies; private final ScreeningCriterionRepository criteria; private final ScreeningReasonCodeRepository reasons; private final PublicationScreeningPolicyRepository bindings; private final VacancyPublicationRepository publications; private final ScreeningEvidenceEvaluator evaluator; private final PrimeHrAuditService audit; private final ObjectMapper json;
 public ScreeningPolicyServiceImpl(ScreeningPolicyRepository p,ScreeningCriterionRepository c,ScreeningReasonCodeRepository r,PublicationScreeningPolicyRepository b,VacancyPublicationRepository v,ScreeningEvidenceEvaluator e,PrimeHrAuditService a,ObjectMapper j){policies=p;criteria=c;reasons=r;bindings=b;publications=v;evaluator=e;audit=a;json=j;}
 @Override @Transactional(readOnly=true) public PageResponse<PolicyResponse> list(String agency,int page,int size){if(page<0||size<1||size>100)throw new IllegalArgumentException("Invalid pagination");return PageResponse.from(policies.findByAgencyId(agency,PageRequest.of(page,size,Sort.by("createdAt").descending())),p->response(agency,p));}
 @Override @Transactional(readOnly=true) public PolicyResponse get(String agency,String id){return response(agency,policy(agency,id));}
 @Override public PolicyResponse create(String agency,SavePolicy req,String correlation){if(req.recordVersion()!=null)throw new IllegalArgumentException("recordVersion must not be supplied when creating");validateChildren(req.criteria(),req.reasonCodes());String normalized=req.code().trim().toUpperCase(Locale.ROOT);if(policies.existsByAgencyIdAndNormalizedCodeAndDefinitionVersion(agency,normalized,1))throw new IllegalArgumentException("Screening policy code already exists");ScreeningPolicy p=policies.saveAndFlush(new ScreeningPolicy(agency,req.code(),req.name(),req.description(),1,null));replaceChildren(agency,p,req);PolicyResponse after=response(agency,p);audit.record(agency,"CREATE_SCREENING_POLICY_DRAFT","RSP_SCREENING_POLICY",p.getId(),p.getDefinitionVersion(),p.getVersion(),null,after,null,correlation);return after;}
 @Override public PolicyResponse update(String agency,String id,SavePolicy req,String correlation){ScreeningPolicy p=policy(agency,id);requireVersion(p.getVersion(),req.recordVersion());validateChildren(req.criteria(),req.reasonCodes());PolicyResponse before=response(agency,p);p.update(req.code(),req.name(),req.description(),req.effectiveFrom(),req.effectiveTo());p=policies.saveAndFlush(p);replaceChildren(agency,p,req);PolicyResponse after=response(agency,p);audit.record(agency,"UPDATE_SCREENING_POLICY_DRAFT","RSP_SCREENING_POLICY",id,p.getDefinitionVersion(),p.getVersion(),before,after,null,correlation);return after;}
 @Override public PolicyResponse publish(String agency,String id,Publish req,String correlation){ScreeningPolicy p=policy(agency,id);requireVersion(p.getVersion(),req.recordVersion());if(criteria.countByAgencyIdAndPolicyId(agency,id)==0||reasons.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,id).stream().noneMatch(r->r.getOutcomeCompatibility()==ScreeningReasonCode.Outcome.DISQUALIFIED))throw new IllegalArgumentException("A published screening policy requires criteria and a DISQUALIFIED reason code");PolicyResponse before=response(agency,p);ScreeningPolicy prior=p.getSupersedesId()==null?null:policy(agency,p.getSupersedesId());if(prior!=null&&!req.effectiveFrom().isAfter(prior.getEffectiveFrom()))throw new IllegalArgumentException("A successor must become effective after its predecessor");p.publish(req.effectiveFrom(),req.effectiveTo(),audit.currentActor(),Instant.now());p=policies.saveAndFlush(p);if(prior!=null){prior.supersede(req.effectiveFrom());policies.saveAndFlush(prior);}PolicyResponse after=response(agency,p);audit.record(agency,"PUBLISH_SCREENING_POLICY","RSP_SCREENING_POLICY",id,p.getDefinitionVersion(),p.getVersion(),before,after,null,correlation);return after;}
 @Override public PolicyResponse successor(String agency,String id,Transition req,String correlation){ScreeningPolicy prior=policy(agency,id);requireVersion(prior.getVersion(),req.recordVersion());if(prior.getStatus()!=ScreeningPolicy.Status.PUBLISHED)throw new IllegalArgumentException("Only a PUBLISHED policy can have a successor");int version=policies.findByAgencyIdAndNormalizedCodeOrderByDefinitionVersion(agency,prior.getNormalizedCode()).stream().mapToInt(ScreeningPolicy::getDefinitionVersion).max().orElse(0)+1;ScreeningPolicy next=policies.saveAndFlush(new ScreeningPolicy(agency,prior.getCode(),prior.getName(),prior.getDescription(),version,prior.getId()));copyChildren(agency,prior.getId(),next.getId());PolicyResponse after=response(agency,next);audit.record(agency,"CREATE_SCREENING_POLICY_SUCCESSOR","RSP_SCREENING_POLICY",next.getId(),version,next.getVersion(),null,after,null,correlation);return after;}
 @Override public BindingResponse bind(String agency,String publicationId,BindPolicy req,String correlation){if(bindings.existsByAgencyIdAndPublicationId(agency,publicationId))throw new IllegalArgumentException("This vacancy publication already has an immutable screening policy binding");VacancyPublication publication=publications.findByIdAndAgencyId(publicationId,agency).orElseThrow(()->new ResourceNotFoundException("Vacancy publication not found"));requireVersion(publication.getVersion(),req.publicationRecordVersion());if(publication.getStatus()!=VacancyPublicationStatus.PUBLISHED&&publication.getStatus()!=VacancyPublicationStatus.CLOSED)throw new IllegalArgumentException("Only PUBLISHED or CLOSED vacancy publications can be bound for screening");ScreeningPolicy p=policy(agency,req.policyId());requireVersion(p.getVersion(),req.policyRecordVersion());if(p.getStatus()!=ScreeningPolicy.Status.PUBLISHED)throw new IllegalArgumentException("Only a PUBLISHED screening policy can be bound");if(p.getEffectiveFrom().isAfter(publication.getOpeningDate())||(p.getEffectiveTo()!=null&&p.getEffectiveTo().isBefore(publication.getClosingDate())))throw new IllegalArgumentException("The screening policy must be effective for the complete vacancy application window");String snapshot=serialize(response(agency,p));PublicationScreeningPolicy binding=bindings.saveAndFlush(new PublicationScreeningPolicy(agency,publication,p,snapshot,sha256(snapshot),audit.currentActor(),Instant.now()));BindingResponse after=binding(binding);audit.record(agency,"BIND_SCREENING_POLICY","RSP_PUBLICATION_SCREENING_POLICY",binding.getId(),p.getDefinitionVersion(),binding.getVersion(),null,after,null,correlation);return after;}
 @Override @Transactional(readOnly=true) public List<Evaluation> preview(String agency,String policyId,EvidenceFacts facts){ScreeningPolicy p=policy(agency,policyId);if(p.getStatus()!=ScreeningPolicy.Status.PUBLISHED)throw new IllegalArgumentException("Only a PUBLISHED policy can be evaluated");return criteria.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,policyId).stream().map(c->evaluator.evaluate(c,facts)).toList();}
 private void replaceChildren(String agency,ScreeningPolicy p,SavePolicy req){criteria.deleteByAgencyIdAndPolicyId(agency,p.getId());reasons.deleteByAgencyIdAndPolicyId(agency,p.getId());criteria.saveAll(req.criteria().stream().map(c->criterion(agency,p.getId(),c)).toList());reasons.saveAll(req.reasonCodes().stream().map(r->reason(agency,p.getId(),r)).toList());criteria.flush();reasons.flush();}
 private void copyChildren(String agency,String from,String to){criteria.saveAll(criteria.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,from).stream().map(c->new ScreeningCriterion(agency,to,c.getCode(),c.getLabel(),c.getInternalInstructions(),c.getPublicGuidance(),c.getCategory(),c.getEvaluationMode(),c.getSourceKey(),c.getThresholdValue(),c.getThresholdUnit(),c.isMandatory(),c.isDisqualifying(),c.isAllowsNotApplicable(),c.isRequiresRemarks(),c.isRequiresEvidence(),c.getDisplayOrder())).toList());reasons.saveAll(reasons.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,from).stream().map(r->new ScreeningReasonCode(agency,to,r.getCode(),r.getLabel(),r.getPublicSafeText(),r.getOutcomeCompatibility(),r.isRemarksRequired(),r.getDisplayOrder())).toList());criteria.flush();reasons.flush();}
 private ScreeningCriterion criterion(String a,String p,CriterionInput c){return new ScreeningCriterion(a,p,c.code(),c.label(),c.internalInstructions(),c.publicGuidance(),c.category(),c.evaluationMode(),c.sourceKey(),c.thresholdValue(),c.thresholdUnit(),c.mandatory(),c.disqualifying(),c.allowsNotApplicable(),c.requiresRemarks(),c.requiresEvidence(),c.displayOrder());}
 private ScreeningReasonCode reason(String a,String p,ReasonInput r){return new ScreeningReasonCode(a,p,r.code(),r.label(),r.publicSafeText(),r.outcomeCompatibility(),r.remarksRequired(),r.displayOrder());}
 private void validateChildren(List<CriterionInput> cs,List<ReasonInput> rs){unique(cs,CriterionInput::code,CriterionInput::displayOrder,"criterion");unique(rs,ReasonInput::code,ReasonInput::displayOrder,"reason code");}
 private <T> void unique(List<T> list,Function<T,String> code,java.util.function.ToIntFunction<T> order,String label){Set<String> codes=new HashSet<>();Set<Integer> orders=new HashSet<>();for(T item:list)if(!codes.add(code.apply(item).trim().toUpperCase(Locale.ROOT))||!orders.add(order.applyAsInt(item)))throw new IllegalArgumentException("Duplicate "+label+" code or displayOrder");}
 private PolicyResponse response(String agency,ScreeningPolicy p){List<CriterionResponse> cs=criteria.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,p.getId()).stream().map(c->new CriterionResponse(c.getId(),c.getCode(),c.getLabel(),c.getInternalInstructions(),c.getPublicGuidance(),c.getCategory().name(),c.getEvaluationMode().name(),c.getSourceKey(),c.getThresholdValue(),c.getThresholdUnit(),c.isMandatory(),c.isDisqualifying(),c.isAllowsNotApplicable(),c.isRequiresRemarks(),c.isRequiresEvidence(),c.getDisplayOrder())).toList();List<ReasonResponse> rs=reasons.findByAgencyIdAndPolicyIdOrderByDisplayOrderAsc(agency,p.getId()).stream().map(r->new ReasonResponse(r.getId(),r.getCode(),r.getLabel(),r.getPublicSafeText(),r.getOutcomeCompatibility().name(),r.isRemarksRequired(),r.getDisplayOrder())).toList();return new PolicyResponse(p.getId(),p.getCode(),p.getName(),p.getDescription(),p.getDefinitionVersion(),p.getSupersedesId(),p.getStatus().name(),p.getEffectiveFrom(),p.getEffectiveTo(),p.getPublishedBy(),p.getPublishedAt(),p.getVersion(),cs,rs);}
 private BindingResponse binding(PublicationScreeningPolicy b){return new BindingResponse(b.getId(),b.getPublication().getId(),b.getPolicy().getId(),b.getPolicy().getCode(),b.getPolicy().getDefinitionVersion(),b.getPolicyFingerprint(),b.getBoundBy(),b.getBoundAt(),b.getVersion());}
 private ScreeningPolicy policy(String agency,String id){return policies.findByIdAndAgencyId(id,agency).orElseThrow(()->new ResourceNotFoundException("Screening policy not found"));}
 private static void requireVersion(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticConflictException("Expected recordVersion "+expected+" but current version is "+actual);}
 private String serialize(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalStateException("Screening policy snapshot could not be serialized",e);}}
 private static String sha256(String value){try{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(bytes);}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
