package com.primehr.rsp.applicant.application;

import com.primehr.config.PrimeHrProperties;import com.primehr.rsp.applicant.api.ApplicantDtos.*;import com.primehr.rsp.applicant.domain.*;import com.primehr.rsp.applicant.infrastructure.*;import com.primehr.rsp.applicant.storage.DocumentStorage;import com.primehr.rsp.domain.VacancyPublication;import com.primehr.rsp.domain.VacancyPublicationStatus;import com.primehr.rsp.infrastructure.VacancyPublicationRepository;import com.primehr.security.ApplicantTokenService;import com.primehr.shared.audit.PrimeHrAuditService;import com.primehr.shared.exception.*;
import org.springframework.dao.DataIntegrityViolationException;import org.springframework.security.authentication.BadCredentialsException;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import java.io.*;import java.nio.file.Path;import java.security.MessageDigest;import java.time.*;import java.util.*;

@Service @Transactional @ConditionalOnProperty(name="primehr.applicant.enabled",havingValue="true")
public class ApplicantFoundationServiceImpl implements ApplicantFoundationService {
    private final PrimeHrProperties p;private final ApplicantAccountRepository accounts;private final PrivacyNoticeRepository notices;private final ApplicantConsentRepository consents;private final ApplicantProfileRepository profiles;private final ApplicantProfileEntryRepository entries;private final ApplicantDocumentRepository documents;private final VacancyPublicationRepository publications;private final PasswordEncoder passwords;private final ApplicantTokenService tokens;private final DocumentStorage storage;private final PrimeHrAuditService audit;
    public ApplicantFoundationServiceImpl(PrimeHrProperties p,ApplicantAccountRepository a,PrivacyNoticeRepository n,ApplicantConsentRepository c,ApplicantProfileRepository pr,ApplicantProfileEntryRepository e,ApplicantDocumentRepository d,VacancyPublicationRepository v,PasswordEncoder pe,ApplicantTokenService t,DocumentStorage s,PrimeHrAuditService audit){this.p=p;accounts=a;notices=n;consents=c;profiles=pr;entries=e;documents=d;publications=v;passwords=pe;tokens=t;storage=s;this.audit=audit;}
    @Transactional(readOnly=true) public Notice currentNotice(){return notice(effectiveNotice());}
    public Session register(Register r,String ip,String agent){if(!r.consentAccepted())throw new IllegalArgumentException("Privacy consent is required");PrivacyNotice notice=effectiveNotice();if(!notice.getId().equals(r.privacyNoticeId()))throw new IllegalArgumentException("The effective privacy notice must be accepted");String normalized=ApplicantAccount.normalize(r.email());if(accounts.findByAgencyIdAndNormalizedEmail(agency(),normalized).isPresent())throw new DataIntegrityViolationException("Applicant email is already registered");ApplicantAccount account=accounts.saveAndFlush(new ApplicantAccount(agency(),r.email(),passwords.encode(r.password()),r.givenName()+" "+r.familyName()));ApplicantProfile profile=profiles.save(new ApplicantProfile(agency(),account.getId(),r.givenName(),r.familyName()));consents.save(new ApplicantConsent(agency(),account.getId(),notice,Instant.now(),minimize(ip,64),minimize(agent,500)));audit.record(agency(),"REGISTER_APPLICANT","APPLICANT_ACCOUNT",account.getId(),null,account.getVersion(),null,Map.of("profileId",profile.getId(),"noticeVersion",notice.getDefinitionVersion()),null,null);return session(account);}
    @Transactional(noRollbackFor=BadCredentialsException.class)
    public Session login(Login r){Optional<ApplicantAccount> found=accounts.findByAgencyIdAndNormalizedEmail(agency(),ApplicantAccount.normalize(r.email()));if(found.isEmpty()){passwords.matches(r.password(),"$2a$12$eImiTXuWVxfM37uY4JANjQ6uPvj.Ig6.KaYz6xYv2t8rN4f4bQ9uK");throw new BadCredentialsException("Invalid credentials");}ApplicantAccount a=found.get();Instant now=Instant.now();if(a.lockedAt(now)||!passwords.matches(r.password(),a.getPasswordHash())){a.failed(now,p.applicant().maximumFailedAttempts(),p.applicant().lockMinutes());accounts.saveAndFlush(a);throw new BadCredentialsException("Invalid credentials");}a.login(now);accounts.saveAndFlush(a);audit.record(agency(),"APPLICANT_LOGIN","APPLICANT_ACCOUNT",a.getId(),null,a.getVersion(),null,Map.of("successful",true),null,null);return session(a);}
    @Transactional(readOnly=true) public Account me(String id){return account(requireAccount(id));}
    public Account saveAccount(String id,UpdateAccount r){ApplicantAccount a=requireAccount(id);if(a.getVersion()!=r.recordVersion())throw new OptimisticConflictException("Expected recordVersion "+r.recordVersion()+" but current version is "+a.getVersion());String normalized=ApplicantAccount.normalize(r.email());accounts.findByAgencyIdAndNormalizedEmail(agency(),normalized).filter(existing->!existing.getId().equals(a.getId())).ifPresent(existing->{throw new DataIntegrityViolationException("Applicant email is already registered");});a.changeAccount(r.email(),r.displayName());accounts.saveAndFlush(a);audit.record(agency(),"UPDATE_APPLICANT_ACCOUNT","APPLICANT_ACCOUNT",a.getId(),null,a.getVersion(),null,Map.of("emailChanged",true),null,null);return account(a);}
    @Transactional(readOnly=true) public Profile profile(String id){requireAccount(id);return profileResponse(requireProfile(id));}
    public Profile saveProfile(String id,SaveProfile r){ApplicantAccount a=requireAccount(id);ApplicantProfile pr=requireProfile(id);if(pr.getVersion()!=r.recordVersion())throw new OptimisticConflictException("Expected recordVersion "+r.recordVersion()+" but current version is "+pr.getVersion());pr.update(r.givenName(),r.middleName(),r.familyName(),r.suffix(),r.birthDate(),r.mobileNumber(),r.addressLine(),r.city(),r.province(),r.postalCode(),r.citizenship(),r.declarationAccepted());a.changeProfileName(r.givenName()+" "+r.familyName());profiles.saveAndFlush(pr);entries.deleteByAgencyIdAndProfileId(agency(),pr.getId());if(r.entries()!=null)entries.saveAll(r.entries().stream().map(x->new ApplicantProfileEntry(agency(),pr.getId(),x.type(),x.title(),x.organizationName(),x.dateFrom(),x.dateTo(),x.details(),x.displayOrder())).toList());audit.record(agency(),"UPDATE_APPLICANT_PROFILE","APPLICANT_PROFILE",pr.getId(),null,pr.getVersion(),null,Map.of("entryCount",r.entries()==null?0:r.entries().size()),null,null);return profileResponse(pr);}
    public void acceptCurrentNotice(String id,String ip,String agent){requireAccount(id);PrivacyNotice n=effectiveNotice();if(!consents.existsByAgencyIdAndApplicantIdAndNoticeIdAndWithdrawnAtIsNull(agency(),id,n.getId()))consents.save(new ApplicantConsent(agency(),id,n,Instant.now(),minimize(ip,64),minimize(agent,500)));}
    @Transactional(readOnly=true) public List<Document> documents(String id){requireAccount(id);return documents.findByAgencyIdAndApplicantIdAndActiveTrueOrderByUploadedAtDesc(agency(),id).stream().map(this::document).toList();}
    public Document upload(String id,String type,String classification,MultipartFile file,String replaces){requireAccount(id);if(!p.storage().enabled())throw new IllegalStateException("Document uploads are disabled");if(file==null||file.isEmpty()||file.getSize()>p.storage().maximumBytes())throw new IllegalArgumentException("Document size is invalid");String media=Objects.requireNonNullElse(file.getContentType(),"");if(!p.storage().allowedMediaTypes().contains(media))throw new IllegalArgumentException("Document media type is not allowed");byte[] bytes;try{bytes=file.getBytes();}catch(IOException e){throw new IllegalArgumentException("Document could not be read",e);}verifySignature(media,bytes);String filename=safeFilename(file.getOriginalFilename());String key=agency()+"/"+id+"/"+UUID.randomUUID().toString().replace("-","");String checksum=sha256(bytes);ApplicantDocument old=null;if(replaces!=null&&!replaces.isBlank())old=requireDocument(id,replaces);storage.put(key,bytes,media);try{ApplicantDocument d=documents.saveAndFlush(new ApplicantDocument(agency(),id,type,filename,storage.provider(),key,media,bytes.length,checksum,classification,old==null?null:old.getId()));if(old!=null){old.replace();documents.save(old);}audit.record(agency(),old==null?"UPLOAD_APPLICANT_DOCUMENT":"REPLACE_APPLICANT_DOCUMENT","APPLICANT_DOCUMENT",d.getId(),null,d.getVersion(),null,Map.of("type",d.getDocumentType(),"size",d.getByteSize(),"checksum",d.getChecksum()),null,null);return document(d);}catch(RuntimeException e){storage.delete(key);throw e;}}
    public DocumentContent download(String id,String documentId){ApplicantDocument d=requireDocument(id,documentId);audit.record(agency(),"DOWNLOAD_APPLICANT_DOCUMENT","APPLICANT_DOCUMENT",d.getId(),null,d.getVersion(),null,Map.of("owner",id),null,null);return new DocumentContent(d.getOriginalFilename(),d.getMediaType(),d.getByteSize(),storage.get(d.getStorageObjectKey()));}
    public void deactivateDocument(String id,String documentId,long version){ApplicantDocument d=requireDocument(id,documentId);if(d.getVersion()!=version)throw new OptimisticConflictException("Expected recordVersion "+version+" but current version is "+d.getVersion());d.replace();documents.saveAndFlush(d);audit.record(agency(),"DEACTIVATE_APPLICANT_DOCUMENT","APPLICANT_DOCUMENT",d.getId(),null,d.getVersion(),null,Map.of("active",false),null,null);}
    @Transactional(readOnly=true) public List<PublicVacancy> publicVacancies(){LocalDate now=LocalDate.now();return publications.findByAgencyIdAndStatusAndOpeningDateLessThanEqualAndClosingDateGreaterThanEqual(agency(),VacancyPublicationStatus.PUBLISHED,now,now).stream().map(this::vacancy).toList();}
    @Transactional(readOnly=true) public PublicVacancy publicVacancy(String id){VacancyPublication v=publications.findByIdAndAgencyId(id,agency()).filter(x->x.getStatus()==VacancyPublicationStatus.PUBLISHED).orElseThrow(()->new ResourceNotFoundException("Vacancy was not found"));return vacancy(v);}
    private PrivacyNotice effectiveNotice(){LocalDate today=LocalDate.now();return notices.findByAgencyIdAndStatusOrderByDefinitionVersionDesc(agency(),PrivacyNotice.Status.ACTIVE).stream().filter(n->n.effective(today)).findFirst().orElseThrow(()->new ResourceNotFoundException("No effective privacy notice is configured"));}
    private ApplicantAccount requireAccount(String id){return accounts.findByIdAndAgencyId(id,agency()).orElseThrow(()->new ResourceNotFoundException("Applicant account was not found"));}
    private ApplicantProfile requireProfile(String id){return profiles.findByAgencyIdAndApplicantId(agency(),id).orElseThrow(()->new ResourceNotFoundException("Applicant profile was not found"));}
    private ApplicantDocument requireDocument(String id,String doc){return documents.findByIdAndAgencyIdAndApplicantId(doc,agency(),id).orElseThrow(()->new ResourceNotFoundException("Applicant document was not found"));}
    private String agency(){return p.agency().id();} private Session session(ApplicantAccount a){return new Session(tokens.issue(a.getId()),"Bearer",p.applicant().tokenMinutes()*60,account(a));}
    private Account account(ApplicantAccount a){return new Account(a.getId(),a.getEmail(),a.getDisplayName(),a.getStatus().name(),a.getCreatedAt(),a.getVersion());}
    private Notice notice(PrivacyNotice n){return new Notice(n.getId(),n.getTitle(),n.getBody(),n.getRetentionSummary(),n.getDefinitionVersion(),n.getEffectiveFrom(),n.getEffectiveTo());}
    private Profile profileResponse(ApplicantProfile pr){List<Entry> es=entries.findByAgencyIdAndProfileIdOrderByTypeAscDisplayOrderAsc(agency(),pr.getId()).stream().map(e->new Entry(e.getType(),e.getTitle(),e.getOrganizationName(),e.getDateFrom(),e.getDateTo(),e.getDetails(),e.getDisplayOrder())).toList();return new Profile(pr.getId(),pr.getApplicantId(),pr.getGivenName(),pr.getMiddleName(),pr.getFamilyName(),pr.getSuffix(),pr.getBirthDate(),pr.getMobileNumber(),pr.getAddressLine(),pr.getCity(),pr.getProvince(),pr.getPostalCode(),pr.getCitizenship(),pr.isDeclarationAccepted(),pr.getVersion(),es);}
    private Document document(ApplicantDocument d){return new Document(d.getId(),d.getDocumentType(),d.getOriginalFilename(),d.getMediaType(),d.getByteSize(),d.getChecksum(),d.getClassification(),d.getScanStatus().name(),d.getUploadedAt(),d.isActive(),d.getVersion());}
    private PublicVacancy vacancy(VacancyPublication v){return new PublicVacancy(v.getId(),v.getJobPositionName(),v.getPlantillaName(),v.getBusinessUnitName(),v.getPlaceOfAssignment(),v.getSalaryGrade(),v.getSalaryStep(),v.getOpeningDate(),v.getClosingDate(),v.getNoticeText(),v.getInstructions(),v.getContactGuidance(),v.getQualificationStandardVersion(),v.getPositionProfileDefinitionVersion());}
    private static String minimize(String v,int max){return v==null?null:v.substring(0,Math.min(max,v.length()));} private static String safeFilename(String v){String n=v==null?"document":Path.of(v).getFileName().toString().replaceAll("[\\p{Cntrl}]","_");if(n.isBlank())n="document";return n.substring(0,Math.min(255,n.length()));}
    private static String sha256(byte[] b){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
    private static void verifySignature(String media,byte[] b){boolean ok=switch(media){case "application/pdf"->b.length>=5&&b[0]=='%'&&b[1]=='P'&&b[2]=='D'&&b[3]=='F'&&b[4]=='-';case "image/jpeg"->b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255;case "image/png"->b.length>=8&&(b[0]&255)==137&&b[1]=='P'&&b[2]=='N'&&b[3]=='G';default->false;};if(!ok)throw new IllegalArgumentException("Document content does not match its media type");}
}
