package com.humanresource.onboarding;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.humanresource.entitymodels.Employee;
import com.humanresource.entitymodels.EmployeeAppointment;
import com.humanresource.integration.primehr.AppointmentHandoffReceiptRecord;
import com.humanresource.onboarding.OnboardingDtos.*;
import com.humanresource.repositories.*;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.server.ResponseStatusException;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class OnboardingServiceTest {
    JdbcTemplate jdbc;EmployeeRepository employees;EmployeeAppointmentRepository appointments;AdministrativeAppointmentSourceClient sources;PasswordEncoder passwords;OnboardingService service;
    @BeforeEach void setup(){jdbc=new JdbcTemplate(new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2).setName("onboarding;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE").build());employees=mock(EmployeeRepository.class);appointments=mock(EmployeeAppointmentRepository.class);sources=mock(AdministrativeAppointmentSourceClient.class);passwords=mock(PasswordEncoder.class);service=new OnboardingService(jdbc,new ObjectMapper(),employees,appointments,sources,passwords,72);schema();}
    @AfterEach void close(){if(jdbc!=null)((org.springframework.jdbc.datasource.embedded.EmbeddedDatabase)jdbc.getDataSource()).shutdown();}

    @Test void acceptedHandoffCreatesOneCaseWithImmutableTemplateAndItemSnapshot(){TemplateResponse draft=service.createTemplate("agency","configurer",new TemplateCommand("DEFAULT",LocalDate.now().minusDays(1),null,List.of(new TemplateItem("IDENTITY","Verify identity","Review originals",true,true,"CONFIDENTIAL","EMPLOYMENT","HR",1,"INDEPENDENT_VERIFICATION"))));service.publishTemplate("agency",draft.id(),"publisher");var receipt=receipt();service.accepted(receipt);service.accepted(receipt);assertEquals(1,jdbc.queryForObject("select count(*) from hrm_onboarding_case",Integer.class));assertEquals(1,jdbc.queryForObject("select count(*) from hrm_onboarding_item",Integer.class));String snapshot=jdbc.queryForObject("select template_snapshot from hrm_onboarding_case",String.class);assertTrue(snapshot.contains("IDENTITY"));jdbc.update("update hrm_onboarding_template_item set label='Changed later'");assertTrue(jdbc.queryForObject("select template_snapshot from hrm_onboarding_case",String.class).contains("Verify identity"));}

    @Test void evidenceSubmitterCannotVerifyTheirOwnRequiredEvidence(){String caseId=seedCase("IN_REVIEW",0);String itemId=seedItem(caseId);service.checklist("agency",caseId,itemId,new ChecklistCommand("SUBMITTED","vault://evidence/1","a".repeat(64),0),"employee-a");ResponseStatusException error=assertThrows(ResponseStatusException.class,()->service.checklist("agency",caseId,itemId,new ChecklistCommand("VERIFIED",null,null,1),"employee-a"));assertEquals(409,error.getStatusCode().value());service.checklist("agency",caseId,itemId,new ChecklistCommand("VERIFIED",null,null,1),"employee-b");assertEquals("VERIFIED",jdbc.queryForObject("select status from hrm_onboarding_item where id=?",String.class,itemId));}

    @Test void staleAdministrativeSourceFailsBeforeEmployeeOrAppointmentMutation() throws Exception {String id=seedCase("READY_FOR_APPOINTMENT",0);when(sources.resolve(anyString(),eq(10L),eq(30L),eq(40L),any())).thenReturn(new AdministrativeAppointmentSourceClient.Source(999L,"Changed",20L,"Position",30L,"BU","Unit",40L,"P","Permanent",50L,12L,1L,java.math.BigDecimal.ONE,java.math.BigDecimal.ONE,java.math.BigDecimal.ONE,"r".repeat(64),"f".repeat(64)));var command=new AppointmentCommand(40L,LocalDateTime.of(2026,9,1,0,0),LocalDateTime.of(2026,9,2,0,0),"Appointment",0);assertEquals(409,assertThrows(ResponseStatusException.class,()->service.createAppointment("agency",id,command,"actor","Bearer jwt")).getStatusCode().value());verify(employees,never()).saveAndFlush(any());verify(appointments,never()).saveAndFlush(any());assertEquals(0,jdbc.queryForObject("select count(*) from hrm_appointment_provenance",Integer.class));}

    @Test void activationIsExpiringAndSingleUse(){Employee employee=new Employee();employee.setEmployeeId(7L);when(employees.findByIdForUpdate(7L)).thenReturn(Optional.of(employee));when(passwords.encode("long-enough-password")).thenReturn("encoded");String token="single-use-token";jdbc.update("insert into employee_activation_invitation(id,employee_id,onboarding_case_id,token_hash,expires_at,created_at) values('inv',7,'case',?,CURRENT_TIMESTAMP + INTERVAL '1' DAY,CURRENT_TIMESTAMP)",sha(token));service.activate(new ActivationCommand(token,"long-enough-password"));assertEquals("encoded",employee.getEmployeePassword());assertEquals(400,assertThrows(ResponseStatusException.class,()->service.activate(new ActivationCommand(token,"long-enough-password"))).getStatusCode().value());}

    @Test void externalHireCreatesOneStableAppointmentAndOneActivationInvitation(){String id=seedCase("READY_FOR_APPOINTMENT",0);jdbc.update("update hrm_onboarding_case set identity_decision='CREATE_NEW_EMPLOYEE',proposed_employee_no='E-100',proposed_biometric_no='B-100',proposed_role='2' where id=?",id);when(passwords.encode(anyString())).thenReturn("placeholder");when(sources.resolve(anyString(),eq(10L),eq(30L),eq(40L),any())).thenReturn(source());when(appointments.findActiveByPlantillaForUpdate(10)).thenReturn(List.of());when(appointments.findActiveByEmployeeForUpdate(7L)).thenReturn(List.of());when(employees.saveAndFlush(any())).thenAnswer(i->{Employee e=i.getArgument(0);e.setEmployeeId(7L);return e;});when(appointments.saveAndFlush(any())).thenAnswer(i->{EmployeeAppointment a=i.getArgument(0);a.setEmployeeAppointmentId(8L);return a;});AppointmentResult first=service.createAppointment("agency",id,appointmentCommand(),"actor","Bearer jwt");assertEquals(7L,first.employeeId());assertEquals(8L,first.appointmentId());assertNotNull(first.activationToken());assertEquals(1,jdbc.queryForObject("select count(*) from employee_activation_invitation",Integer.class));AppointmentResult retry=service.createAppointment("agency",id,appointmentCommand(),"actor","Bearer jwt");assertEquals(first.employeeId(),retry.employeeId());assertEquals(first.appointmentId(),retry.appointmentId());assertNull(retry.activationToken());verify(employees,times(1)).saveAndFlush(any());verify(appointments,times(1)).saveAndFlush(any());}

    @Test void internalPromotionKeepsEmployeeAndDeactivatesPriorAppointmentAtomically(){String id=seedCase("READY_FOR_APPOINTMENT",0);jdbc.update("update hrm_onboarding_case set identity_decision='LINK_EXISTING_EMPLOYEE',employee_id=7,proposed_employee_no='E-7' where id=?",id);Employee employee=new Employee();employee.setEmployeeId(7L);EmployeeAppointment prior=new EmployeeAppointment();prior.setEmployeeId(7L);prior.setPlantillaId(10);prior.setAssumptionToDutyDate(LocalDateTime.of(2025,1,1,0,0));prior.setActiveAppointment(true);when(sources.resolve(anyString(),eq(10L),eq(30L),eq(40L),any())).thenReturn(source());when(appointments.findActiveByPlantillaForUpdate(10)).thenReturn(List.of(prior));when(employees.findByIdForUpdate(7L)).thenReturn(Optional.of(employee));when(appointments.findActiveByEmployeeForUpdate(7L)).thenReturn(List.of(prior));when(appointments.saveAndFlush(any())).thenAnswer(i->{EmployeeAppointment a=i.getArgument(0);a.setEmployeeAppointmentId(9L);return a;});AppointmentResult result=service.createAppointment("agency",id,appointmentCommand(),"actor","Bearer jwt");assertEquals(9L,result.appointmentId());assertFalse(prior.getActiveAppointment());verify(appointments).saveAll(List.of(prior));verify(employees,never()).saveAndFlush(any());assertEquals(0,jdbc.queryForObject("select count(*) from employee_activation_invitation",Integer.class));}

    private void schema(){for(String sql:List.of("create table hrm_onboarding_template(id varchar(36) primary key,agency_id varchar(64),template_code varchar(80),definition_version int,status varchar(20),effective_from date,effective_to date,published_at timestamp,superseded_at timestamp,created_by varchar(100),created_at timestamp)","create table hrm_onboarding_template_item(id varchar(36),template_id varchar(36),item_code varchar(80),label varchar(200),instructions varchar(500),required_item boolean,evidence_required boolean,evidence_classification varchar(40),retention_tag varchar(80),responsible_role varchar(80),display_order int,completion_rule varchar(40))","create table rsp_appointment_handoff_receipt(id varchar(36),selection_id varchar(36),application_id varchar(36),applicant_id varchar(36),payload_snapshot clob,source_fingerprint varchar(64),state varchar(30),record_version bigint,updated_at timestamp)","create table hrm_onboarding_case(id varchar(36),agency_id varchar(64),handoff_receipt_id varchar(36),handoff_id varchar(36),template_id varchar(36),template_version int,template_snapshot clob,status varchar(30),identity_decision varchar(30),employee_id bigint,proposed_employee_no varchar(100),proposed_biometric_no varchar(100),proposed_role varchar(50),return_reason varchar(500),appointment_id bigint,source_fingerprint varchar(64),record_version bigint,created_at timestamp,updated_at timestamp)","create table hrm_onboarding_item(id varchar(36),onboarding_case_id varchar(36),template_item_id varchar(36),item_code varchar(80),label varchar(200),required_item boolean,evidence_required boolean,evidence_classification varchar(40),retention_tag varchar(80),responsible_role varchar(80),display_order int,completion_rule varchar(40),status varchar(20),evidence_reference varchar(500),evidence_fingerprint varchar(64),completed_by varchar(100),completed_at timestamp,verified_by varchar(100),verified_at timestamp,record_version bigint)","create table hrm_appointment_provenance(id varchar(36),agency_id varchar(64),onboarding_case_id varchar(36),handoff_id varchar(36),selection_id varchar(36),application_id varchar(36),employee_id bigint,employee_appointment_id bigint,plantilla_id int,source_fingerprint varchar(64),administrative_fingerprint varchar(64),created_by varchar(100),created_at timestamp)","create table employee_activation_invitation(id varchar(36),employee_id bigint,onboarding_case_id varchar(36),token_hash varchar(64),expires_at timestamp,consumed_at timestamp,revoked_at timestamp,created_at timestamp)","create table hrm_onboarding_audit_event(id varchar(36),agency_id varchar(64),onboarding_case_id varchar(36),action_code varchar(80),actor varchar(100),safe_summary varchar(500),occurred_at timestamp)"))jdbc.execute(sql);}
    private AppointmentHandoffReceiptRecord receipt(){Instant now=Instant.now();return new AppointmentHandoffReceiptRecord("receipt","agency","handoff",1,"s".repeat(64),"selection","application","applicant","RECEIVED",payload(),now,null,"primehr",0,now);}
    private String seedCase(String status,long version){String id="case";jdbc.update("insert into rsp_appointment_handoff_receipt(id,selection_id,application_id,applicant_id,payload_snapshot,source_fingerprint,state,record_version,updated_at) values('receipt','selection','application','applicant',?,?,'RECEIVED',0,CURRENT_TIMESTAMP)",payload(),"s".repeat(64));jdbc.update("insert into hrm_onboarding_case(id,agency_id,handoff_receipt_id,handoff_id,template_id,template_version,template_snapshot,status,source_fingerprint,record_version,created_at,updated_at) values(?,?,?,?,?,?,?, ?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",id,"agency","receipt","handoff","template",1,"{}",status,"s".repeat(64),version);return id;}
    private String seedItem(String id){jdbc.update("insert into hrm_onboarding_item(id,onboarding_case_id,template_item_id,item_code,label,required_item,evidence_required,responsible_role,display_order,completion_rule,status,record_version) values('item',?,'template-item','DOC','Document',true,true,'HR',1,'INDEPENDENT','PENDING',0)",id);return "item";}
    private String payload(){return "{\"position\":{\"plantillaId\":10,\"plantillaName\":\"Plantilla\",\"jobPositionId\":20,\"jobPositionName\":\"Position\",\"businessUnitId\":30},\"applicant\":{\"givenName\":\"Ada\",\"familyName\":\"Lovelace\",\"email\":\"ada@example.test\"}}";}
    private AdministrativeAppointmentSourceClient.Source source(){return new AdministrativeAppointmentSourceClient.Source(10L,"Plantilla",20L,"Position",30L,"BU","Unit",40L,"P","Permanent",50L,12L,1L,new java.math.BigDecimal("1000.00"),new java.math.BigDecimal("12000.00"),new java.math.BigDecimal("32.88"),"r".repeat(64),"f".repeat(64));}
    private AppointmentCommand appointmentCommand(){return new AppointmentCommand(40L,LocalDateTime.of(2026,9,1,0,0),LocalDateTime.of(2026,9,2,0,0),"Appointment",0);}
    private static String sha(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new RuntimeException(e);}}
}
