package com.primehr.rsp.applicant;

import com.primehr.rsp.applicant.api.ApplicantDtos;import com.primehr.rsp.applicant.application.ApplicantFoundationService;import com.primehr.rsp.applicant.domain.PrivacyNotice;import com.primehr.rsp.applicant.infrastructure.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.mock.web.MockMultipartFile;import org.springframework.security.authentication.BadCredentialsException;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;import java.util.List;
import org.springframework.test.context.ActiveProfiles;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest @Transactional @ActiveProfiles("test")
class ApplicantFoundationIntegrationTest {
 @Autowired ApplicantFoundationService service;@Autowired PrivacyNoticeRepository notices;@Autowired ApplicantAccountRepository accounts;
 @BeforeEach void notice(){notices.save(new PrivacyNotice("TEST-AGENCY","Applicant Privacy Notice","Recruitment privacy terms","Records retained according to agency policy",1,LocalDate.now().minusDays(1),null,PrivacyNotice.Status.ACTIVE));}
 @Test void registrationConsentLoginProfileAndDocumentOwnershipWorkWithoutEmployeeCreation(){var session=service.register(new ApplicantDtos.Register("Person@Example.com","correct-password-123","Ana","Applicant",service.currentNotice().id(),true),"127.0.0.1","test");assertThat(session.token()).isNotBlank();assertThat(accounts.findByAgencyIdAndNormalizedEmail("TEST-AGENCY","person@example.com")).isPresent();assertThat(service.login(new ApplicantDtos.Login("PERSON@example.com","correct-password-123")).account().id()).isEqualTo(session.account().id());var current=service.me(session.account().id());var account=service.saveAccount(session.account().id(),new ApplicantDtos.UpdateAccount("ana.updated@example.com","Ana Updated",current.recordVersion()));assertThat(account.email()).isEqualTo("ana.updated@example.com");assertThat(account.displayName()).isEqualTo("Ana Updated");assertThatThrownBy(()->service.saveAccount(session.account().id(),new ApplicantDtos.UpdateAccount("stale@example.com","Stale",current.recordVersion()))).isInstanceOf(com.primehr.shared.exception.OptimisticConflictException.class);var p=service.profile(session.account().id());var saved=service.saveProfile(session.account().id(),new ApplicantDtos.SaveProfile("Ana",null,"Applicant",null,LocalDate.of(1990,1,1),"09170000000","Address","City","Province","1000","Filipino",true,List.of(new ApplicantDtos.Entry(com.primehr.rsp.applicant.domain.ApplicantProfileEntry.Type.EDUCATION,"Degree","School",LocalDate.of(2006,1,1),LocalDate.of(2010,1,1),"Completed",0)),p.recordVersion()));assertThat(saved.entries()).hasSize(1);byte[] pdf="%PDF-1.7 test".getBytes(java.nio.charset.StandardCharsets.US_ASCII);var document=service.upload(session.account().id(),"PDS","SENSITIVE",new MockMultipartFile("file","pds.pdf","application/pdf",pdf),null);assertThat(document.checksum()).isEqualTo("eddc31937fbdaf708e866af0d20b9fb8c79dd001881c8a11e4c617f2882e779f");assertThat(service.download(session.account().id(),document.id()).stream()).hasBinaryContent(pdf);var replacement=service.upload(session.account().id(),"PDS","SENSITIVE",new MockMultipartFile("file","new.pdf","application/pdf","%PDF-1.7 replacement".getBytes(java.nio.charset.StandardCharsets.US_ASCII)),document.id());assertThat(service.documents(session.account().id())).extracting(ApplicantDtos.Document::id).containsExactly(replacement.id());assertThatThrownBy(()->service.download("another-applicant",replacement.id())).isInstanceOf(com.primehr.shared.exception.ResourceNotFoundException.class);}
 @Test void wrongPasswordHasGenericFailureAndEventuallyLocks(){var s=service.register(new ApplicantDtos.Register("lock@example.com","correct-password-123","Lock","Test",service.currentNotice().id(),true),null,null);for(int attempt=0;attempt<5;attempt++)assertThatThrownBy(()->service.login(new ApplicantDtos.Login("lock@example.com","wrong-password"))).isInstanceOf(BadCredentialsException.class).hasMessage("Invalid credentials");var account=accounts.findById(s.account().id()).orElseThrow();assertThat(account.getFailedAttempts()).isEqualTo(5);assertThat(account.getStatus()).isEqualTo(com.primehr.rsp.applicant.domain.ApplicantAccount.Status.LOCKED);assertThatThrownBy(()->service.login(new ApplicantDtos.Login("lock@example.com","correct-password-123"))).isInstanceOf(BadCredentialsException.class).hasMessage("Invalid credentials");}
 @Test void registrationRejectsStaleOrForgedPrivacyNoticeId(){assertThatThrownBy(()->service.register(new ApplicantDtos.Register("notice@example.com","correct-password-123","Notice","Mismatch","not-current",true),null,null)).isInstanceOf(IllegalArgumentException.class).hasMessage("The effective privacy notice must be accepted");assertThat(accounts.findByAgencyIdAndNormalizedEmail("TEST-AGENCY","notice@example.com")).isEmpty();}
 @Test void signatureMismatchAndStaleProfileAreRejected(){var s=service.register(new ApplicantDtos.Register("safe@example.com","correct-password-123","Safe","Test",service.currentNotice().id(),true),null,null);assertThatThrownBy(()->service.upload(s.account().id(),"PDS","SENSITIVE",new MockMultipartFile("file","fake.pdf","application/pdf","not pdf".getBytes()),null)).isInstanceOf(IllegalArgumentException.class);var p=service.profile(s.account().id());assertThatThrownBy(()->service.saveProfile(s.account().id(),new ApplicantDtos.SaveProfile("Safe",null,"Test",null,null,null,null,null,null,null,null,true,List.of(),p.recordVersion()+1))).isInstanceOf(com.primehr.shared.exception.OptimisticConflictException.class);}
 @Test void oversizedAndUnsupportedDocumentsAreRejected(){var s=service.register(new ApplicantDtos.Register("limits@example.com","correct-password-123","Limits","Test",service.currentNotice().id(),true),null,null);byte[] oversized=new byte[10_485_761];oversized[0]='%';oversized[1]='P';oversized[2]='D';oversized[3]='F';oversized[4]='-';assertThatThrownBy(()->service.upload(s.account().id(),"PDS","SENSITIVE",new MockMultipartFile("file","large.pdf","application/pdf",oversized),null)).isInstanceOf(IllegalArgumentException.class).hasMessage("Document size is invalid");assertThatThrownBy(()->service.upload(s.account().id(),"PDS","SENSITIVE",new MockMultipartFile("file","text.txt","text/plain","text".getBytes()),null)).isInstanceOf(IllegalArgumentException.class).hasMessage("Document media type is not allowed");}
}
