package com.primehr.rsp.screening.api;
import com.primehr.rsp.screening.api.ScreeningPolicyDtos.*; import com.primehr.rsp.screening.application.ScreeningPolicyService; import com.primehr.security.*; import com.primehr.shared.api.PageResponse; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/primehr/v1/rsp")
public class ScreeningPolicyController {private final ScreeningPolicyService service;private final RspScreeningPolicyPermissionGuard permission;private final AgencyScopeResolver scope;public ScreeningPolicyController(ScreeningPolicyService s,RspScreeningPolicyPermissionGuard p,AgencyScopeResolver a){service=s;permission=p;scope=a;}
 @GetMapping("/screening-policies") public PageResponse<PolicyResponse> list(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestParam(name="page",defaultValue="0")int page,@RequestParam(name="size",defaultValue="20")int size){permission.require(PrimeHrAction.ACCESS,t);return service.list(agency(a),page,size);}
 @GetMapping("/screening-policies/{policyId}") public PolicyResponse get(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@PathVariable("policyId") String policyId){permission.require(PrimeHrAction.ACCESS,t);return service.get(agency(a),policyId);}
 @PostMapping("/screening-policies") @ResponseStatus(HttpStatus.CREATED) public PolicyResponse create(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@Valid @RequestBody SavePolicy r){permission.require(PrimeHrAction.ADD,t);return service.create(agency(a),r,c);}
 @PutMapping("/screening-policies/{policyId}") public PolicyResponse update(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable("policyId") String policyId,@Valid @RequestBody SavePolicy r){permission.require(PrimeHrAction.EDIT,t);return service.update(agency(a),policyId,r,c);}
 @PostMapping("/screening-policies/{policyId}/publish") public PolicyResponse publish(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable("policyId") String policyId,@Valid @RequestBody Publish r){permission.require(PrimeHrAction.PUBLISH,t);return service.publish(agency(a),policyId,r,c);}
 @PostMapping("/screening-policies/{policyId}/successors") @ResponseStatus(HttpStatus.CREATED) public PolicyResponse successor(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable("policyId") String policyId,@Valid @RequestBody Transition r){permission.require(PrimeHrAction.ADD,t);return service.successor(agency(a),policyId,r,c);}
 @PostMapping("/screening-policies/{policyId}/preview") public List<Evaluation> preview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@PathVariable("policyId") String policyId,@RequestBody EvidenceFacts r){permission.require(PrimeHrAction.ACCESS,t);return service.preview(agency(a),policyId,r);}
 @PutMapping("/vacancy-publications/{publicationId}/screening-policy") public BindingResponse bind(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable("publicationId") String publicationId,@Valid @RequestBody BindPolicy r){permission.require(PrimeHrAction.PUBLISH,t);return service.bind(agency(a),publicationId,r,c);}
 private String agency(Authentication a){return scope.resolveAgencyId(a);}}
