package com.primehr.rsp.screening.api;
import com.primehr.rsp.screening.api.ScreeningCaseDtos.*; import com.primehr.rsp.screening.application.ScreeningAssignmentEligibilityService; import com.primehr.rsp.screening.application.ScreeningCaseService; import com.primehr.security.*; import com.primehr.shared.api.PageResponse; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/primehr/v1/rsp") public class ScreeningCaseController {
 private final ScreeningCaseService service;private final RspApplicationScreeningPermissionGuard permission;private final AgencyScopeResolver agency;private final ScreeningAssignmentEligibilityService assignmentEligibility;
 public ScreeningCaseController(ScreeningCaseService service,RspApplicationScreeningPermissionGuard permission,AgencyScopeResolver agency,ScreeningAssignmentEligibilityService assignmentEligibility){this.service=service;this.permission=permission;this.agency=agency;this.assignmentEligibility=assignmentEligibility;}
 @GetMapping("/screening-cases") public PageResponse<CaseResponse> list(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestParam(name="page",defaultValue="0")int page,@RequestParam(name="size",defaultValue="20")int size){var p=permission.require(PrimeHrAction.ACCESS,token);return service.list(agency.resolveAgencyId(a),a.getName(),p.administrator(),page,size);}
 @PostMapping("/applications/{applicationId}/screening-cases") @ResponseStatus(HttpStatus.CREATED) public CaseResponse open(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("applicationId") String applicationId,@Valid @RequestBody OpenCase request){permission.require(PrimeHrAction.ADD,token);assignmentEligibility.validate(request.screenerEmployeeNo(),request.validatorEmployeeNo(),token);return service.open(agency.resolveAgencyId(a),applicationId,request,a.getName(),correlation);}
 @GetMapping("/screening-cases/{caseId}") public CaseResponse get(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable("caseId") String caseId){var p=permission.require(PrimeHrAction.ACCESS,token);return service.get(agency.resolveAgencyId(a),caseId,a.getName(),p.administrator());}
 @PostMapping("/screening-cases/{caseId}/successors") @ResponseStatus(HttpStatus.CREATED) public CaseResponse successor(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody Successor request){permission.require(PrimeHrAction.ADD,token);assignmentEligibility.validate(request.screenerEmployeeNo(),request.validatorEmployeeNo(),token);return service.successor(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @PutMapping("/screening-cases/{caseId}/assignments") public CaseResponse assignments(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody Assignments request){permission.require(PrimeHrAction.ADD,token);assignmentEligibility.validate(request.screenerEmployeeNo(),request.validatorEmployeeNo(),token);return service.assignments(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @PutMapping("/screening-cases/{caseId}/findings/{criterionId}") public CaseResponse finding(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@PathVariable("criterionId") String criterionId,@Valid @RequestBody SaveFinding request){permission.require(PrimeHrAction.EDIT,token);return service.finding(agency.resolveAgencyId(a),caseId,criterionId,request,a.getName(),correlation);}
 @PostMapping("/screening-cases/{caseId}/submit") public CaseResponse submit(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody Submit request){permission.require(PrimeHrAction.SUBMIT,token);return service.submit(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @PostMapping("/screening-cases/{caseId}/return") public CaseResponse returnCase(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody Transition request){permission.require(PrimeHrAction.APPROVE,token);return service.returnCase(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @PostMapping("/screening-cases/{caseId}/finalize") public CaseResponse finalizeCase(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody Finalize request){permission.require(PrimeHrAction.APPROVE,token);return service.finalizeCase(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @PostMapping("/screening-cases/{caseId}/override") public CaseResponse overrideCase(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable("caseId") String caseId,@Valid @RequestBody AdminOverride request){var p=permission.require(PrimeHrAction.APPROVE,token);if(!p.administrator())throw new org.springframework.security.access.AccessDeniedException("Administrator authority is required for a screening override");return service.overrideCase(agency.resolveAgencyId(a),caseId,request,a.getName(),correlation);}
 @GetMapping("/screening-cases/{caseId}/history") public PageResponse<CaseResponse> history(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable("caseId") String caseId,@RequestParam(name="page",defaultValue="0")int page,@RequestParam(name="size",defaultValue="20")int size){var p=permission.require(PrimeHrAction.ACCESS,token);return service.history(agency.resolveAgencyId(a),caseId,a.getName(),p.administrator(),page,size);}
}
