package com.primehr.performancemanagement.api;
import com.primehr.performancemanagement.api.PerformanceAppealDtos.*;import com.primehr.performancemanagement.application.PerformanceAppealService;import com.primehr.security.*;import jakarta.validation.Valid;import org.springframework.core.io.InputStreamResource;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.*;
@RestController@RequestMapping("/api/primehr/v1/performance-management")public class PerformanceAppealController{private final PerformanceAppealService service;private final PerformanceRatingPermissionGuard ratingPermission;private final PerformanceCalibrationPermissionGuard calibrationPermission;private final PerformanceAppealPermissionGuard appealPermission;private final AgencyScopeResolver agency;public PerformanceAppealController(PerformanceAppealService s,PerformanceRatingPermissionGuard r,PerformanceCalibrationPermissionGuard c,PerformanceAppealPermissionGuard p,AgencyScopeResolver a){service=s;ratingPermission=r;calibrationPermission=c;appealPermission=p;agency=a;}private static String actor(Authentication a){if(a==null||a.getName()==null||a.getName().isBlank())throw new org.springframework.security.access.AccessDeniedException("Authenticated employee identity is required");return a.getName();}
 @GetMapping("/final-ratings")public List<FinalRatingView>finalRatings(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t){return service.finalRatings(agency.resolveAgencyId(a),actor(a),ratingPermission.require(PrimeHrAction.ACCESS,t));}
 @PostMapping("/final-ratings/{id}/acknowledgment")public AcknowledgmentResponse acknowledge(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody AcknowledgeInput r){var scope=ratingPermission.require(PrimeHrAction.SUBMIT,t);if(r.overrideWindow())calibrationPermission.require(PrimeHrAction.APPROVE,t);return service.acknowledge(agency.resolveAgencyId(a),id,r,actor(a),scope,c);}
 @PostMapping("/final-ratings/{id}/close-without-acknowledgment")public AcknowledgmentResponse close(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody ActionInput r){calibrationPermission.require(PrimeHrAction.FINALIZE,t);return service.closeWithoutAcknowledgment(agency.resolveAgencyId(a),id,r,actor(a),com.primehr.integration.administrative.PermissionDataScope.AGENCY_WIDE,c);}
 @GetMapping("/appeals")public List<AppealResponse>appeals(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t){return service.list(agency.resolveAgencyId(a),actor(a),appealPermission.require(PrimeHrAction.ACCESS,t));}
 @PostMapping("/final-ratings/{id}/appeals")@ResponseStatus(HttpStatus.CREATED)public AppealResponse create(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody AppealInput r){return service.create(agency.resolveAgencyId(a),id,r,actor(a),appealPermission.require(PrimeHrAction.ADD,t),c);}
 @PutMapping("/appeals/{id}")public AppealResponse edit(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody AppealEdit r){return service.edit(agency.resolveAgencyId(a),id,r,actor(a),appealPermission.require(PrimeHrAction.EDIT,t),c);}
 @PostMapping("/appeals/{id}/submit")public AppealResponse submit(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody ActionInput r){return service.submit(agency.resolveAgencyId(a),id,r,actor(a),appealPermission.require(PrimeHrAction.SUBMIT,t),c);}
 @PostMapping("/appeals/{id}/decision")public AppealResponse decide(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@Valid@RequestBody AppealDecision r){return service.decide(agency.resolveAgencyId(a),id,r,actor(a),appealPermission.require(PrimeHrAction.APPROVE,t),c);}
 @PostMapping(value="/appeals/{id}/evidence",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)@ResponseStatus(HttpStatus.CREATED)public EvidenceResponse upload(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@RequestParam String idempotencyKey,@RequestPart("file")MultipartFile file){return service.upload(agency.resolveAgencyId(a),id,idempotencyKey,file,actor(a),appealPermission.require(PrimeHrAction.EDIT,t),c);}
 @GetMapping("/appeals/{id}/evidence/{evidenceId}/content")public ResponseEntity<InputStreamResource>download(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String t,@RequestHeader(value="X-Correlation-Id",required=false)String c,@PathVariable String id,@PathVariable String evidenceId){var x=service.download(agency.resolveAgencyId(a),id,evidenceId,actor(a),appealPermission.require(PrimeHrAction.ACCESS,t),c);return ResponseEntity.ok().contentType(MediaType.parseMediaType(x.mediaType())).contentLength(x.size()).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(x.filename()).build().toString()).header(HttpHeaders.CACHE_CONTROL,"no-store").body(new InputStreamResource(x.stream()));}
}
