package com.primehr.performancemanagement.api;
import jakarta.validation.constraints.*;import java.io.InputStream;import java.math.BigDecimal;import java.time.*;import java.util.*;
public final class PerformanceMonitoringDtos{private PerformanceMonitoringDtos(){}
 public record OpenCaseRequest(@NotBlank@Size(max=100)String idempotencyKey,boolean overrideWindow,@Size(max=2000)String reason){}
 public record UpdateInput(@NotBlank String commitmentItemId,@NotNull LocalDate reportingDate,@NotBlank@Size(max=4000)String narrativeAccomplishment,BigDecimal accomplishedValue,@DecimalMin("0.0000")@DecimalMax("100.0000")BigDecimal progressPercent,@Size(max=3000)String issuesRisks,@Size(max=3000)String supportNeeded,@Size(max=3000)String employeeRemarks,@NotBlank@Size(max=100)String idempotencyKey){}
 public record UpdateEdit(@NotNull Long recordVersion,@NotNull LocalDate reportingDate,@NotBlank@Size(max=4000)String narrativeAccomplishment,BigDecimal accomplishedValue,@DecimalMin("0.0000")@DecimalMax("100.0000")BigDecimal progressPercent,@Size(max=3000)String issuesRisks,@Size(max=3000)String supportNeeded,@Size(max=3000)String employeeRemarks){}
 public record ActionCommand(@NotNull Long recordVersion,@NotBlank@Size(max=100)String idempotencyKey,@Size(max=3000)String reason,boolean overrideWindow){}
 public record EvidenceCommand(@NotBlank@Size(max=100)String idempotencyKey,@Size(max=30)String confidentiality,String replacesEvidenceId){}
 public record FeedbackResponse(String id,String decision,String feedback,String actorEmployeeNo,Instant actedAt){}
 public record EvidenceResponse(String id,String updateId,String itemId,String filename,String mediaType,long byteSize,String checksum,String confidentiality,String supersedesId,String status,String voidReason,String uploadedBy,Instant uploadedAt,long recordVersion){}
 public record CaseItemResponse(String id,String label,String outputDescription,String performanceIndicator,String unitOfMeasure,BigDecimal weightPercent,boolean required,boolean requiresEvidence,String evidenceRequirement,BigDecimal committedValue,BigDecimal committedFrom,BigDecimal committedTo,LocalDate targetStart,LocalDate targetEnd,int displayOrder){}
 public record UpdateResponse(String id,String itemId,String rootUpdateId,int revisionNo,String supersedesId,LocalDate reportingDate,String narrativeAccomplishment,BigDecimal accomplishedValue,BigDecimal progressPercent,String issuesRisks,String supportNeeded,String employeeRemarks,String status,String submittedBy,Instant submittedAt,long recordVersion,List<FeedbackResponse>feedback,List<EvidenceResponse>evidence){}
 public record CaseResponse(String id,String commitmentVersionId,String cycleId,String policyVersionId,String formType,Long ownerEmployeeId,String ownerEmployeeNo,String ownerName,Long businessUnitId,String supervisorEmployeeNo,String routeFingerprint,String commitmentFingerprint,String status,int accomplishmentRevision,String accomplishmentSubmittedBy,Instant accomplishmentSubmittedAt,String returnReason,long recordVersion,List<CaseItemResponse>items,List<UpdateResponse>updates,List<EvidenceResponse>evidence){}
 public record EvidenceContent(String filename,String mediaType,long size,InputStream stream){}
}
