package com.primehr.performancemanagement.api;
import com.primehr.performancemanagement.api.PerformanceCoachingDtos.*;import com.primehr.performancemanagement.application.PerformanceCoachingService;import com.primehr.security.*;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController@RequestMapping("/api/primehr/v1/performance-management")public class PerformanceCoachingController{
 private final PerformanceCoachingService service;private final PerformanceCoachingPermissionGuard permission;private final AgencyScopeResolver agency;public PerformanceCoachingController(PerformanceCoachingService s,PerformanceCoachingPermissionGuard p,AgencyScopeResolver a){service=s;permission=p;agency=a;}private String agency(Authentication a){return agency.resolveAgencyId(a);}private static String actor(Authentication a){if(a==null||a.getName()==null||a.getName().isBlank())throw new org.springframework.security.access.AccessDeniedException("Authenticated employee identity is required");return a.getName();}
 @GetMapping("/monitoring-cases/{id}/coaching-sessions")public List<SessionResponse>sessions(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){return service.sessions(agency(a),id,actor(a),permission.require(PrimeHrAction.ACCESS,token));}
 @PostMapping("/monitoring-cases/{id}/coaching-sessions")@ResponseStatus(HttpStatus.CREATED)public SessionResponse create(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionInput in){return service.createSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.ADD,token),correlation);}
 @PutMapping("/coaching-sessions/{id}")public SessionResponse edit(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionEdit in){return service.editSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/coaching-sessions/{id}/issue")public SessionResponse issue(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionAction in){return service.transitionSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.SUBMIT,token),"ISSUE",correlation);}
 @PostMapping("/coaching-sessions/{id}/acknowledge")public SessionResponse acknowledge(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionAction in){return service.transitionSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.SUBMIT,token),"ACKNOWLEDGE",correlation);}
 @PostMapping("/coaching-sessions/{id}/corrections")@ResponseStatus(HttpStatus.CREATED)public SessionResponse correct(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionInput in){return service.correctSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/coaching-sessions/{id}/void")public SessionResponse voided(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionAction in){return service.transitionSession(agency(a),id,in,actor(a),permission.require(PrimeHrAction.APPROVE,token),"VOID",correlation);}
 @PostMapping("/coaching-sessions/{id}/action-items")@ResponseStatus(HttpStatus.CREATED)public ActionItemResponse addAction(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionItemInput in){return service.addActionItem(agency(a),id,in,actor(a),permission.require(PrimeHrAction.ADD,token),correlation);}
 @PutMapping("/coaching-action-items/{id}")public ActionItemResponse updateAction(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionItemEdit in){return service.updateActionItem(agency(a),id,in,actor(a),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/coaching-action-items/{id}/verify")public ActionItemResponse verify(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionAction in){return service.decideActionItem(agency(a),id,in,actor(a),permission.require(PrimeHrAction.APPROVE,token),true,correlation);}
 @PostMapping("/coaching-action-items/{id}/reopen")public ActionItemResponse reopen(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody SessionAction in){return service.decideActionItem(agency(a),id,in,actor(a),permission.require(PrimeHrAction.APPROVE,token),false,correlation);}
 @GetMapping("/monitoring-cases/{id}/mid-cycle-review")public ReviewResponse review(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){return service.getReview(agency(a),id,actor(a),permission.require(PrimeHrAction.ACCESS,token));}
 @PostMapping("/monitoring-cases/{id}/mid-cycle-review")@ResponseStatus(HttpStatus.CREATED)public ReviewResponse createReview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ReviewInput in){return service.createReview(agency(a),id,in,actor(a),permission.require(PrimeHrAction.ADD,token),correlation);}
 @PutMapping("/mid-cycle-reviews/{id}")public ReviewResponse editReview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ReviewEdit in){return service.editReview(agency(a),id,in,actor(a),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/mid-cycle-reviews/{id}/submit")public ReviewResponse submitReview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ReviewAction in){return service.transitionReview(agency(a),id,in,actor(a),permission.require(PrimeHrAction.SUBMIT,token),"SUBMIT",correlation);}
 @PostMapping("/mid-cycle-reviews/{id}/acknowledge")public ReviewResponse acknowledgeReview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ReviewAction in){return service.transitionReview(agency(a),id,in,actor(a),permission.require(PrimeHrAction.SUBMIT,token),"ACKNOWLEDGE",correlation);}
 @PostMapping("/mid-cycle-reviews/{id}/close-without-acknowledgment")public ReviewResponse closeReview(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ReviewAction in){return service.transitionReview(agency(a),id,in,actor(a),permission.require(PrimeHrAction.APPROVE,token),"CLOSE_WITHOUT_ACKNOWLEDGMENT",correlation);}
}
