package com.primehr.performancemanagement.api;

import com.primehr.performancemanagement.api.PerformanceCommitmentDtos.*;
import com.primehr.performancemanagement.api.PerformanceCommitmentWorkflowDtos.*;
import com.primehr.performancemanagement.application.*;
import com.primehr.security.*;
import jakarta.validation.Valid;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/primehr/v1/performance-management/commitments")
public class PerformanceCommitmentController {
    private final PerformanceCommitmentService service; private final PerformanceCommitmentWorkflowService workflow;
    private final PerformanceCommitmentPermissionGuard permission; private final AgencyScopeResolver agency;
    public PerformanceCommitmentController(PerformanceCommitmentService service,PerformanceCommitmentWorkflowService workflow,PerformanceCommitmentPermissionGuard permission,AgencyScopeResolver agency){this.service=service;this.workflow=workflow;this.permission=permission;this.agency=agency;}
    private String agency(Authentication auth){return agency.resolveAgencyId(auth);} private static String actor(Authentication auth){if(auth==null||auth.getName()==null||auth.getName().isBlank())throw new org.springframework.security.access.AccessDeniedException("Authenticated employee identity is required");return auth.getName();}
    @GetMapping public List<CommitmentResponse> list(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestParam String formType,@RequestParam(required=false)String cycleId,@RequestParam(required=false)String subjectType,@RequestParam(required=false)Long subjectId,@RequestParam(required=false)String ownerEmployeeNo,@RequestParam(required=false)String status,@RequestParam(required=false)Boolean assignedTask){var scope=permission.require(formType,PrimeHrAction.ACCESS,token);return service.list(agency(auth),actor(auth),scope,new CommitmentFilter(formType,cycleId,subjectType,subjectId,ownerEmployeeNo,status,assignedTask));}
    @PostMapping("/from-assignment/{assignmentId}") @ResponseStatus(HttpStatus.CREATED) public CommitmentResponse generate(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String assignmentId,@Valid@RequestBody Generation input){String a=agency(auth);var scope=permission.require(service.formTypeForAssignment(a,assignmentId),PrimeHrAction.ADD,token);return service.generate(a,assignmentId,input.idempotencyKey(),actor(auth),scope,correlation);}
    @GetMapping("/{id}") public CommitmentResponse get(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.ACCESS,token);return service.get(a,id,actor(auth),scope);}
    @GetMapping("/{id}/workflow") public WorkflowResponse workflow(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.ACCESS,token);return workflow.get(a,id,actor(auth),scope);}
    @PutMapping("/{id}/targets") public CommitmentResponse targets(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody TargetReplacement input){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.EDIT,token);return service.replaceTargets(a,id,input,token,actor(auth),scope,correlation);}
    @PutMapping("/{id}/cascades") public CommitmentResponse cascades(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody CascadeReplacement input){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.EDIT,token);return service.replaceCascades(a,id,input,actor(auth),scope,correlation);}
    @GetMapping("/{id}/readiness") public Readiness readiness(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.ACCESS,token);return service.readiness(a,id,token,actor(auth),scope);}
    @PostMapping("/{id}/submit") public WorkflowResponse submit(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){String a=agency(auth),form=service.formTypeForVersion(a,id);var scope=permission.require(form,PrimeHrAction.SUBMIT,token);if(command.overrideWindow())permission.require(form,PrimeHrAction.FINALIZE,token);return workflow.submit(a,id,command,token,actor(auth),scope,correlation);}
    @PostMapping("/{id}/withdraw") public WorkflowResponse withdraw(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.SUBMIT,token);return workflow.withdraw(a,id,command,actor(auth),scope,correlation);}
    @PostMapping("/{id}/recommend") public WorkflowResponse recommend(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){return decision(auth,token,correlation,id,command,"RECOMMEND");}
    @PostMapping("/{id}/return") public WorkflowResponse returnForChanges(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){return decision(auth,token,correlation,id,command,"RETURN");}
    @PostMapping("/{id}/approve") public WorkflowResponse approve(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){return decision(auth,token,correlation,id,command,"APPROVE");}
    @PostMapping("/{id}/reject") public WorkflowResponse reject(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){return decision(auth,token,correlation,id,command,"REJECT");}
    @PostMapping("/{id}/void") public WorkflowResponse voidRecord(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){String a=agency(auth);permission.require(service.formTypeForVersion(a,id),PrimeHrAction.FINALIZE,token);return workflow.voidRecord(a,id,command,actor(auth),correlation);}
    @PostMapping("/{id}/route-rebase") public WorkflowResponse rebase(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody Command command){String a=agency(auth);permission.require(service.formTypeForVersion(a,id),PrimeHrAction.FINALIZE,token);return workflow.rebase(a,id,command,token,actor(auth),correlation);}
    @PostMapping("/{id}/amendments") @ResponseStatus(HttpStatus.CREATED) public CommitmentResponse amend(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody AmendmentCommand command){String a=agency(auth);var scope=permission.require(service.formTypeForVersion(a,id),PrimeHrAction.FINALIZE,token);return service.amend(a,id,command,actor(auth),scope,correlation);}
    private WorkflowResponse decision(Authentication auth,String token,String correlation,String id,Command command,String action){String a=agency(auth),form=service.formTypeForVersion(a,id);permission.require(form,"APPROVE".equals(action)?PrimeHrAction.FINALIZE:PrimeHrAction.APPROVE,token);if(command.overrideWindow())permission.require(form,PrimeHrAction.FINALIZE,token);return switch(action){case "RECOMMEND"->workflow.recommend(a,id,command,token,actor(auth),correlation);case "RETURN"->workflow.returnForChanges(a,id,command,token,actor(auth),correlation);case "APPROVE"->workflow.approve(a,id,command,token,actor(auth),correlation);case "REJECT"->workflow.reject(a,id,command,token,actor(auth),correlation);default->throw new IllegalArgumentException("Unsupported decision");};}
}
