package com.primehr.performancemanagement.api;
import com.primehr.integration.administrative.PermissionDataScope;import com.primehr.performancemanagement.api.PerformanceMonitoringDtos.*;import com.primehr.performancemanagement.application.PerformanceMonitoringService;import com.primehr.security.*;import jakarta.validation.Valid;import org.springframework.core.io.InputStreamResource;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.*;
@RestController@RequestMapping("/api/primehr/v1/performance-management")public class PerformanceMonitoringController{private final PerformanceMonitoringService service;private final PerformanceMonitoringPermissionGuard permission;private final AgencyScopeResolver agency;public PerformanceMonitoringController(PerformanceMonitoringService s,PerformanceMonitoringPermissionGuard p,AgencyScopeResolver a){service=s;permission=p;agency=a;}private String agency(Authentication a){return agency.resolveAgencyId(a);}private static String actor(Authentication a){if(a==null||a.getName()==null||a.getName().isBlank())throw new org.springframework.security.access.AccessDeniedException("Authenticated employee identity is required");return a.getName();}
 @PostMapping("/commitments/{versionId}/monitoring-case")@ResponseStatus(HttpStatus.CREATED)public CaseResponse open(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String versionId,@Valid@RequestBody OpenCaseRequest input){var scope=permission.require(PrimeHrAction.ADD,token);if(input.overrideWindow())permission.require(PrimeHrAction.APPROVE,token);return service.open(agency(auth),versionId,input,actor(auth),scope,correlation);}
 @GetMapping("/monitoring-cases")public List<CaseResponse>list(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token){return service.list(agency(auth),actor(auth),permission.require(PrimeHrAction.ACCESS,token));}
 @GetMapping("/monitoring-cases/mine")public List<CaseResponse>mine(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token){permission.require(PrimeHrAction.ACCESS,token);return service.list(agency(auth),actor(auth),PermissionDataScope.OWN_RECORDS);}
 @GetMapping("/monitoring-cases/{id}")public CaseResponse get(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){return service.get(agency(auth),id,actor(auth),permission.require(PrimeHrAction.ACCESS,token));}
 @PostMapping("/monitoring-cases/{id}/updates")@ResponseStatus(HttpStatus.CREATED)public UpdateResponse add(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody UpdateInput input){return service.addUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.ADD,token),correlation);}
 @PutMapping("/monitoring-updates/{id}")public UpdateResponse edit(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody UpdateEdit input){return service.editUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/monitoring-updates/{id}/submit")public UpdateResponse submit(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){return service.submitUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.SUBMIT,token),correlation);}
 @PostMapping("/monitoring-updates/{id}/accept")public UpdateResponse accept(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){return service.decideUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.APPROVE,token),true,correlation);}
 @PostMapping("/monitoring-updates/{id}/return")public UpdateResponse returned(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){return service.decideUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.APPROVE,token),false,correlation);}
 @PostMapping("/monitoring-updates/{id}/corrections")@ResponseStatus(HttpStatus.CREATED)public UpdateResponse correction(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody UpdateInput input){return service.correctUpdate(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping(value="/monitoring-updates/{id}/evidence",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)@ResponseStatus(HttpStatus.CREATED)public EvidenceResponse evidence(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@RequestParam String idempotencyKey,@RequestParam(defaultValue="SENSITIVE")String confidentiality,@RequestParam(required=false)String replacesEvidenceId,@RequestPart("file")MultipartFile file){return service.uploadEvidence(agency(auth),id,new EvidenceCommand(idempotencyKey,confidentiality,replacesEvidenceId),file,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @GetMapping("/monitoring-evidence/{id}/content")public ResponseEntity<InputStreamResource>download(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id){var value=service.downloadEvidence(agency(auth),id,actor(auth),permission.require(PrimeHrAction.ACCESS,token),correlation);return ResponseEntity.ok().contentType(MediaType.parseMediaType(value.mediaType())).contentLength(value.size()).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(value.filename()).build().toString()).header(HttpHeaders.CACHE_CONTROL,"no-store").body(new InputStreamResource(value.stream()));}
 @PostMapping("/monitoring-evidence/{id}/void")public EvidenceResponse voidEvidence(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){return service.voidEvidence(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/monitoring-cases/{id}/accomplishments/submit")public CaseResponse submitAccomplishments(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){var scope=permission.require(PrimeHrAction.SUBMIT,token);if(input.overrideWindow())permission.require(PrimeHrAction.APPROVE,token);return service.submitAccomplishments(agency(auth),id,input,actor(auth),scope,correlation);}
 @PostMapping("/monitoring-cases/{id}/accomplishments/return")public CaseResponse returnAccomplishments(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody ActionCommand input){return service.returnAccomplishments(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.APPROVE,token),correlation);}
}
