package com.primehr.performancemanagement.api;
import com.primehr.integration.administrative.PermissionDataScope;import com.primehr.performancemanagement.api.PerformanceRatingDtos.*;import com.primehr.performancemanagement.application.PerformanceRatingService;import com.primehr.security.*;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController@RequestMapping("/api/primehr/v1/performance-management")public class PerformanceRatingController{private final PerformanceRatingService service;private final PerformanceRatingPermissionGuard permission;private final AgencyScopeResolver agency;public PerformanceRatingController(PerformanceRatingService service,PerformanceRatingPermissionGuard permission,AgencyScopeResolver agency){this.service=service;this.permission=permission;this.agency=agency;}private String agency(Authentication value){return agency.resolveAgencyId(value);}private static String actor(Authentication value){if(value==null||value.getName()==null||value.getName().isBlank())throw new org.springframework.security.access.AccessDeniedException("Authenticated employee identity is required");return value.getName();}
 @PostMapping("/monitoring-cases/{id}/rating-case")@ResponseStatus(HttpStatus.CREATED)public CaseResponse open(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody OpenCaseInput input){var scope=permission.require(PrimeHrAction.ADD,token);if(input.overrideWindow())permission.require(PrimeHrAction.APPROVE,token);return service.open(agency(auth),id,input,actor(auth),scope,correlation);}
 @GetMapping("/rating-cases")public List<CaseResponse>list(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token){return service.list(agency(auth),actor(auth),permission.require(PrimeHrAction.ACCESS,token));}
 @GetMapping("/rating-cases/mine")public List<CaseResponse>mine(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token){permission.require(PrimeHrAction.ACCESS,token);return service.list(agency(auth),actor(auth),PermissionDataScope.OWN_RECORDS);}
 @GetMapping("/rating-cases/{id}")public CaseResponse get(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@PathVariable String id){return service.get(agency(auth),id,actor(auth),permission.require(PrimeHrAction.ACCESS,token));}
 @PostMapping("/rating-cases/{id}/assessments")@ResponseStatus(HttpStatus.CREATED)public AssessmentResponse create(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody AssessmentInput input){return service.createAssessment(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.ADD,token),correlation);}
 @PutMapping("/rating-assessments/{id}")public AssessmentResponse edit(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody AssessmentEdit input){return service.editAssessment(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/rating-assessments/{id}/corrections")@ResponseStatus(HttpStatus.CREATED)public AssessmentResponse correct(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody AssessmentInput input){return service.correctAssessment(agency(auth),id,input,actor(auth),permission.require(PrimeHrAction.EDIT,token),correlation);}
 @PostMapping("/rating-assessments/{id}/submit")public AssessmentResponse submit(Authentication auth,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@PathVariable String id,@Valid@RequestBody AssessmentAction input){var scope=permission.require(PrimeHrAction.SUBMIT,token);if(input.overrideWindow())permission.require(PrimeHrAction.APPROVE,token);return service.submitAssessment(agency(auth),id,input,actor(auth),scope,correlation);}
}
