-- Phase 5A.1 reviewable Administrative migration for PostgreSQL.
-- Apply once to the Administrative database before changing ddl-auto to validate/none.
CREATE TABLE public.qualification_standard (
    "qualificationStandardId" BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_qualification_standard PRIMARY KEY,
    "jobPositionId" BIGINT NOT NULL,
    "definitionVersion" INTEGER NOT NULL,
    "supersedesId" BIGINT NULL,
    status VARCHAR(20) NOT NULL,
    education VARCHAR(2000) NOT NULL,
    training VARCHAR(2000) NOT NULL,
    experience VARCHAR(2000) NOT NULL,
    eligibility VARCHAR(2000) NOT NULL,
    "licenseRequirement" VARCHAR(2000) NULL,
    "sourceBasis" VARCHAR(1000) NULL,
    "effectiveFrom" DATE NULL,
    "effectiveTo" DATE NULL,
    "createdBy" VARCHAR(100) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updatedBy" VARCHAR(100) NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "publishedBy" VARCHAR(100) NULL,
    "publishedAt" TIMESTAMP WITH TIME ZONE NULL,
    "recordVersion" BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_qs_job_position FOREIGN KEY ("jobPositionId")
        REFERENCES public.job_position("jobPositionId"),
    CONSTRAINT fk_qs_supersedes FOREIGN KEY ("supersedesId")
        REFERENCES public.qualification_standard("qualificationStandardId"),
    CONSTRAINT uk_qs_job_version UNIQUE ("jobPositionId", "definitionVersion"),
    CONSTRAINT ck_qs_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_qs_effectivity CHECK ("effectiveTo" IS NULL OR "effectiveFrom" IS NULL OR "effectiveTo" >= "effectiveFrom")
);

CREATE INDEX ix_qs_job_status_effective
    ON public.qualification_standard("jobPositionId", status, "effectiveFrom", "effectiveTo");
