package com.primehr.rsp.report;

import com.primehr.rsp.applicant.domain.PositionApplication;import com.primehr.rsp.applicant.infrastructure.PositionApplicationRepository;
import com.primehr.rsp.domain.*;import com.primehr.rsp.evaluation.domain.EvaluationProceeding;import com.primehr.rsp.evaluation.infrastructure.*;
import com.primehr.rsp.handoff.domain.*;import com.primehr.rsp.handoff.infrastructure.*;import com.primehr.rsp.infrastructure.VacancyPublicationRepository;
import com.primehr.rsp.screening.domain.ScreeningCase;import com.primehr.rsp.screening.infrastructure.ScreeningCaseRepository;
import com.primehr.rsp.selection.domain.*;import com.primehr.rsp.selection.infrastructure.*;import com.primehr.shared.audit.PrimeHrAuditService;
import com.primehr.rsp.infrastructure.VacancyPublicationChannelRepository;import com.primehr.rsp.screening.infrastructure.ScreeningDecisionRepository;import com.primehr.integration.administrative.AdministrativeOrganizationScopeClient;
import org.junit.jupiter.api.*;import org.springframework.data.domain.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class RspProcessReportServiceImplTest {
    VacancyPublicationRepository publications=mock(VacancyPublicationRepository.class);VacancyPublicationChannelRepository channels=mock(VacancyPublicationChannelRepository.class);PositionApplicationRepository applications=mock(PositionApplicationRepository.class);ScreeningCaseRepository screenings=mock(ScreeningCaseRepository.class);ScreeningDecisionRepository decisions=mock(ScreeningDecisionRepository.class);EvaluationProceedingRepository proceedings=mock(EvaluationProceedingRepository.class);EvaluationCandidateRepository candidates=mock(EvaluationCandidateRepository.class);SelectionCaseRepository selections=mock(SelectionCaseRepository.class);OfferResponseRepository offers=mock(OfferResponseRepository.class);AppointmentHandoffRepository handoffs=mock(AppointmentHandoffRepository.class);AppointmentHandoffAttemptRepository attempts=mock(AppointmentHandoffAttemptRepository.class);RspProcessReportRenderer renderer=mock(RspProcessReportRenderer.class);PrimeHrAuditService audit=mock(PrimeHrAuditService.class);AdministrativeOrganizationScopeClient organizations=mock(AdministrativeOrganizationScopeClient.class);RspProcessReportServiceImpl service=new RspProcessReportServiceImpl(publications,channels,applications,screenings,decisions,proceedings,candidates,selections,offers,handoffs,attempts,renderer,audit,organizations);
    @Test void currentRevisionMetricsReconcileWithdrawalsCorrectionsOutcomesOffersAndHandoffs(){
        VacancyPublication p=publication("p1");when(publications.findByAgencyId(eq("A"),any())).thenReturn(new PageImpl<>(List.of(p)));
        PositionApplication old=application("old","person",1,PositionApplication.Status.QUALIFIED,Instant.parse("2026-01-02T00:00:00Z"));PositionApplication current=application("app","person",2,PositionApplication.Status.WITHDRAWN,Instant.parse("2026-01-03T00:00:00Z"));
        when(applications.findByAgencyIdAndPublicationIdOrderByCreatedAtAsc("A","p1")).thenReturn(List.of(old,current));
        ScreeningCase s1=screen("s1",current,1,ScreeningCase.Status.DISQUALIFIED,Instant.parse("2026-01-04T00:00:00Z"));ScreeningCase s2=screen("s2",current,2,ScreeningCase.Status.QUALIFIED,Instant.parse("2026-01-05T00:00:00Z"));when(screenings.findByAgencyIdAndPublicationIdOrderByOpenedAtAsc("A","p1")).thenReturn(List.of(s1,s2));
        EvaluationProceeding proceeding=mock(EvaluationProceeding.class);when(proceeding.getId()).thenReturn("proc");when(proceeding.getStatus()).thenReturn(EvaluationProceeding.Status.FINALIZED);when(proceedings.findByAgencyIdAndPublicationIdOrderByCreatedAtDesc("A","p1")).thenReturn(List.of(proceeding));when(candidates.countByAgencyIdAndProceedingId("A","proc")).thenReturn(1L);
        SelectionCase selection=selection("sel",2,SelectionCase.Status.FINALIZED,SelectionCase.Outcome.SELECTED,Instant.parse("2026-01-10T00:00:00Z"));when(selections.findByAgencyIdAndPublicationIdOrderByCaseRevisionAsc("A","p1")).thenReturn(List.of(selection));
        OfferResponse offer=mock(OfferResponse.class);when(offer.getStatus()).thenReturn(OfferResponse.Status.DECLINED);when(offers.findByAgencyIdAndSelectionCaseId("A","sel")).thenReturn(Optional.of(offer));
        AppointmentHandoff handoff=mock(AppointmentHandoff.class);when(handoff.getId()).thenReturn("h1");when(handoff.getStatus()).thenReturn(AppointmentHandoff.Status.RETRYABLE_FAILURE);when(handoffs.findByAgencyIdAndSelectionCaseIdOrderByHandoffRevisionDesc("A","sel")).thenReturn(List.of(handoff));
        AppointmentHandoffAttempt failed=mock(AppointmentHandoffAttempt.class);when(failed.getResultCategory()).thenReturn("HTTP_ERROR");when(attempts.findByAgencyIdAndHandoffIdOrderByAttemptNumberAsc("A","h1")).thenReturn(List.of(failed));
        var query=query(false);
        var register=service.register("A",query,"actor","Bearer test","corr");assertThat(register.rows()).singleElement().satisfies(r->{assertThat(r.getApplicationCount()).isOne();assertThat(r.getWithdrawnCount()).isOne();assertThat(r.getQualifiedCount()).isOne();assertThat(r.getCorrectedScreeningCount()).isOne();assertThat(r.getFailedHandoffAttempts()).isOne();});
        var analytics=service.analytics("A",query,"actor","Bearer test","corr");Map<String,RspProcessReportData.Metric> m=new HashMap<>();analytics.metrics().forEach(x->m.put(x.code(),x));assertThat(m.get("APPLICATIONS_SUBMITTED").value()).isEqualByComparingTo("1");assertThat(m.get("APPLICATIONS_WITHDRAWN").value()).isEqualByComparingTo("1");assertThat(m.get("SCREENING_FINALIZED").value()).isEqualByComparingTo("100.00");assertThat(m.get("OUTCOME_SELECTED").value()).isEqualByComparingTo("1");assertThat(m.get("OFFER_DECLINED").value()).isEqualByComparingTo("1");assertThat(m.get("HANDOFF_RETRYABLE_FAILURE").value()).isEqualByComparingTo("1");
    }
    @Test void validatesBoundsAndHistoryIsExplicit(){var bad=new RspProcessReportData.RegisterQuery(LocalDate.parse("2024-01-01"),LocalDate.parse("2026-01-01"),RspProcessReportData.DateBasis.PUBLICATION_CLOSING_DATE,false,0,25,null,null,null,null,null,null,null,null);assertThatThrownBy(()->service.register("A",bad,"actor","Bearer test",null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("366");
        VacancyPublication p=publication("p1");SelectionCase history1=selection("s1",1,SelectionCase.Status.SUPERSEDED,SelectionCase.Outcome.NO_SELECTION,null);SelectionCase history2=selection("s2",2,SelectionCase.Status.FINALIZED,SelectionCase.Outcome.DEFERRED,null);when(publications.findByAgencyId(eq("A"),any())).thenReturn(new PageImpl<>(List.of(p)));when(applications.findByAgencyIdAndPublicationIdOrderByCreatedAtAsc("A","p1")).thenReturn(List.of());when(screenings.findByAgencyIdAndPublicationIdOrderByOpenedAtAsc("A","p1")).thenReturn(List.of());when(proceedings.findByAgencyIdAndPublicationIdOrderByCreatedAtDesc("A","p1")).thenReturn(List.of());when(selections.findByAgencyIdAndPublicationIdOrderByCaseRevisionAsc("A","p1")).thenReturn(List.of(history1,history2));
        var base=query(false);assertThat(service.register("A",base,"actor","Bearer test",null).rows()).singleElement().extracting(RspProcessReportData.RegisterRow::getSelectionRevision).isEqualTo("v2");assertThat(service.register("A",query(true),"actor","Bearer test",null).rows()).hasSize(2);}
    @Test void supportsEveryDateBasisAndExactOrganizationWorkflowFilters(){VacancyPublication p=publication("p1");when(publications.findByAgencyId(eq("A"),any())).thenReturn(new PageImpl<>(List.of(p)));when(applications.findByAgencyIdAndPublicationIdOrderByCreatedAtAsc("A","p1")).thenReturn(List.of());when(screenings.findByAgencyIdAndPublicationIdOrderByOpenedAtAsc("A","p1")).thenReturn(List.of());EvaluationProceeding proceeding=mock(EvaluationProceeding.class);when(proceeding.getId()).thenReturn("proc");when(proceeding.getStatus()).thenReturn(EvaluationProceeding.Status.FINALIZED);when(proceeding.getUpdatedAt()).thenReturn(Instant.parse("2026-02-02T00:00:00Z"));when(proceedings.findByAgencyIdAndPublicationIdOrderByCreatedAtDesc("A","p1")).thenReturn(List.of(proceeding));SelectionCase selection=selection("sel",1,SelectionCase.Status.FINALIZED,SelectionCase.Outcome.SELECTED,Instant.parse("2026-03-02T00:00:00Z"));when(selections.findByAgencyIdAndPublicationIdOrderByCaseRevisionAsc("A","p1")).thenReturn(List.of(selection));AppointmentHandoff handoff=mock(AppointmentHandoff.class);when(handoff.getAcknowledgedAt()).thenReturn(Instant.parse("2026-04-02T00:00:00Z"));when(handoff.getStatus()).thenReturn(AppointmentHandoff.Status.ACKNOWLEDGED);when(handoff.getReceiptState()).thenReturn("RECEIVED");when(handoffs.findByAgencyIdAndSelectionCaseIdOrderByHandoffRevisionDesc("A","sel")).thenReturn(List.of(handoff));when(organizations.businessUnitIdsForArea(9L,"Bearer test")).thenReturn(Set.of(2L));
        for(var basis:RspProcessReportData.DateBasis.values()){var filtered=new RspProcessReportData.RegisterQuery(LocalDate.parse("2026-01-01"),LocalDate.parse("2026-12-31"),basis,false,0,25,VacancyPublicationStatus.CLOSED,EvaluationProceeding.Status.FINALIZED,SelectionCase.Status.FINALIZED,SelectionCase.Outcome.SELECTED,10L,1L,9L,2L);assertThat(service.register("A",filtered,"actor","Bearer test",null).rows()).as(basis.name()).hasSize(1);}
        when(organizations.businessUnitIdsForArea(9L,"Bearer test")).thenReturn(Set.of(99L));var excluded=new RspProcessReportData.RegisterQuery(LocalDate.parse("2026-01-01"),LocalDate.parse("2026-12-31"),RspProcessReportData.DateBasis.PUBLICATION_DATE,false,0,25,null,null,null,null,null,null,9L,null);assertThat(service.register("A",excluded,"actor","Bearer test",null).rows()).isEmpty();}
    private static RspProcessReportData.RegisterQuery query(boolean history){return new RspProcessReportData.RegisterQuery(LocalDate.parse("2026-01-01"),LocalDate.parse("2026-12-31"),RspProcessReportData.DateBasis.PUBLICATION_CLOSING_DATE,history,0,25,null,null,null,null,null,null,null,null);}
    private static VacancyPublication publication(String id){VacancyPublication p=mock(VacancyPublication.class);when(p.getId()).thenReturn(id);when(p.getOpeningDate()).thenReturn(LocalDate.parse("2026-01-01"));when(p.getClosingDate()).thenReturn(LocalDate.parse("2026-01-31"));when(p.getStatus()).thenReturn(VacancyPublicationStatus.CLOSED);when(p.getJobPositionName()).thenReturn("Position");when(p.getJobPositionId()).thenReturn(10L);when(p.getPlantillaName()).thenReturn("Item");when(p.getPlantillaId()).thenReturn(1L);when(p.getBusinessUnitId()).thenReturn(2L);when(p.getBusinessUnitName()).thenReturn("Unit");when(p.getPublishedAt()).thenReturn(Instant.parse("2026-01-02T00:00:00Z"));when(p.getClosedAt()).thenReturn(Instant.parse("2026-01-31T00:00:00Z"));return p;}
    private static PositionApplication application(String id,String applicant,int version,PositionApplication.Status status,Instant submitted){PositionApplication a=mock(PositionApplication.class);when(a.getId()).thenReturn(id);when(a.getApplicantId()).thenReturn(applicant);when(a.getApplicationVersion()).thenReturn(version);when(a.getStatus()).thenReturn(status);when(a.getSubmittedAt()).thenReturn(submitted);return a;}
    private static ScreeningCase screen(String id,PositionApplication app,int revision,ScreeningCase.Status status,Instant finalized){ScreeningCase s=mock(ScreeningCase.class);when(s.getId()).thenReturn(id);when(s.getApplication()).thenReturn(app);when(s.getCaseRevision()).thenReturn(revision);when(s.getStatus()).thenReturn(status);when(s.getFinalizedAt()).thenReturn(finalized);return s;}
    private static SelectionCase selection(String id,int revision,SelectionCase.Status status,SelectionCase.Outcome outcome,Instant finalized){SelectionCase s=mock(SelectionCase.class);when(s.getId()).thenReturn(id);when(s.getCaseRevision()).thenReturn(revision);when(s.getStatus()).thenReturn(status);when(s.getOutcome()).thenReturn(outcome);when(s.getFinalizedAt()).thenReturn(finalized);return s;}
}
