package com.primehr.rsp.report;

import com.primehr.rsp.report.RspProcessReportData.*;
import com.primehr.security.AgencyScopeResolver;
import com.primehr.security.RspProcessReportPermissionGuard;
import com.primehr.shared.audit.PrimeHrAuditService;
import org.springframework.http.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;
import java.util.Map;
import com.primehr.rsp.domain.VacancyPublicationStatus;
import com.primehr.rsp.evaluation.domain.EvaluationProceeding;
import com.primehr.rsp.selection.domain.SelectionCase;

@RestController
@RequestMapping("/api/primehr/v1/rsp/reports")
public class RspProcessReportController {
    private final RspProcessReportService service;private final RspProcessReportPermissionGuard permission;private final AgencyScopeResolver agency;private final PrimeHrAuditService audit;
    public RspProcessReportController(RspProcessReportService service,RspProcessReportPermissionGuard permission,AgencyScopeResolver agency,PrimeHrAuditService audit){this.service=service;this.permission=permission;this.agency=agency;this.audit=audit;}
    @GetMapping("/register") public RegisterPage register(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam(defaultValue="PUBLICATION_CLOSING_DATE")DateBasis dateBasis,@RequestParam(defaultValue="false")boolean includeHistory,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="25")int size,@RequestParam(required=false)VacancyPublicationStatus publicationStatus,@RequestParam(required=false)EvaluationProceeding.Status proceedingStatus,@RequestParam(required=false)SelectionCase.Status selectionStatus,@RequestParam(required=false)SelectionCase.Outcome outcome,@RequestParam(required=false)Long jobPositionId,@RequestParam(required=false)Long plantillaId,@RequestParam(required=false)Long areaId,@RequestParam(required=false)Long businessUnitId){authorize(RspProcessReportPermissionGuard.REGISTER,token,a,correlation);return service.register(agency.resolveAgencyId(a),query(from,to,dateBasis,includeHistory,page,size,publicationStatus,proceedingStatus,selectionStatus,outcome,jobPositionId,plantillaId,areaId,businessUnitId),a.getName(),token,correlation);}
    @GetMapping(value="/register.pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> registerPdf(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam(defaultValue="PUBLICATION_CLOSING_DATE")DateBasis dateBasis,@RequestParam(defaultValue="false")boolean includeHistory,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@RequestParam(required=false)VacancyPublicationStatus publicationStatus,@RequestParam(required=false)EvaluationProceeding.Status proceedingStatus,@RequestParam(required=false)SelectionCase.Status selectionStatus,@RequestParam(required=false)SelectionCase.Outcome outcome,@RequestParam(required=false)Long jobPositionId,@RequestParam(required=false)Long plantillaId,@RequestParam(required=false)Long areaId,@RequestParam(required=false)Long businessUnitId){authorize(RspProcessReportPermissionGuard.REGISTER,token,a,correlation);return pdf("rsp-register-"+from+"-"+to,service.registerPdf(agency.resolveAgencyId(a),query(from,to,dateBasis,includeHistory,page,size,publicationStatus,proceedingStatus,selectionStatus,outcome,jobPositionId,plantillaId,areaId,businessUnitId),a.getName(),token,correlation));}
    @GetMapping("/process-analytics") public Analytics analytics(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam(defaultValue="PUBLICATION_CLOSING_DATE")DateBasis dateBasis,@RequestParam(defaultValue="false")boolean includeHistory,@RequestParam(required=false)VacancyPublicationStatus publicationStatus,@RequestParam(required=false)EvaluationProceeding.Status proceedingStatus,@RequestParam(required=false)SelectionCase.Status selectionStatus,@RequestParam(required=false)SelectionCase.Outcome outcome,@RequestParam(required=false)Long jobPositionId,@RequestParam(required=false)Long plantillaId,@RequestParam(required=false)Long areaId,@RequestParam(required=false)Long businessUnitId){authorize(RspProcessReportPermissionGuard.ANALYTICS,token,a,correlation);return service.analytics(agency.resolveAgencyId(a),query(from,to,dateBasis,includeHistory,0,100,publicationStatus,proceedingStatus,selectionStatus,outcome,jobPositionId,plantillaId,areaId,businessUnitId),a.getName(),token,correlation);}
    @GetMapping(value="/process-analytics.pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> analyticsPdf(Authentication a,@RequestHeader(HttpHeaders.AUTHORIZATION)String token,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam(defaultValue="PUBLICATION_CLOSING_DATE")DateBasis dateBasis,@RequestParam(defaultValue="false")boolean includeHistory,@RequestParam(required=false)VacancyPublicationStatus publicationStatus,@RequestParam(required=false)EvaluationProceeding.Status proceedingStatus,@RequestParam(required=false)SelectionCase.Status selectionStatus,@RequestParam(required=false)SelectionCase.Outcome outcome,@RequestParam(required=false)Long jobPositionId,@RequestParam(required=false)Long plantillaId,@RequestParam(required=false)Long areaId,@RequestParam(required=false)Long businessUnitId){authorize(RspProcessReportPermissionGuard.ANALYTICS,token,a,correlation);return pdf("rsp-process-analytics-"+from+"-"+to,service.analyticsPdf(agency.resolveAgencyId(a),query(from,to,dateBasis,includeHistory,0,100,publicationStatus,proceedingStatus,selectionStatus,outcome,jobPositionId,plantillaId,areaId,businessUnitId),a.getName(),token,correlation));}
    private static RegisterQuery query(LocalDate from,LocalDate to,DateBasis dateBasis,boolean history,int page,int size,VacancyPublicationStatus publicationStatus,EvaluationProceeding.Status proceedingStatus,SelectionCase.Status selectionStatus,SelectionCase.Outcome outcome,Long jobPositionId,Long plantillaId,Long areaId,Long businessUnitId){return new RegisterQuery(from,to,dateBasis,history,page,size,publicationStatus,proceedingStatus,selectionStatus,outcome,jobPositionId,plantillaId,areaId,businessUnitId);}
    private void authorize(String feature,String token,Authentication a,String correlation){try{permission.require(feature,token);}catch(AccessDeniedException e){String agencyId=agency.resolveAgencyId(a);audit.record(agencyId,"DENY_RSP_PROCESS_REPORT","RSP_REPORT_REQUEST",agencyId,null,null,null,Map.of("featureKey",feature,"outcome","DENIED"),null,correlation);throw e;}}
    private static ResponseEntity<byte[]> pdf(String name,byte[] body){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).cacheControl(CacheControl.noStore()).header("X-Content-Type-Options","nosniff").header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.inline().filename(name.replaceAll("[^A-Za-z0-9._-]","_")+".pdf").build().toString()).body(body);}
}
